### ISSUE TITLE
TypeError: 'float' object is not subscriptable

### ISSUE THREAD

**Issue by zhongqianli** [facebookresearch/maskrcnn-benchmark#1013]
## To Reproduce

1. install maskrcnn-benchmark on ubuntu18.04 without CUDA
1. get qizhuli's [vis_model.py](https://gist.githubusercontent.com/qizhuli/6a9deca289a9cf0c3697e65be7cef569/raw/cc0fa6b8c117f9149f2e436356f2f0fd9b467061/vis_model.py)
1. run it by `python vis_model.py configs/retinanet/retinanet_R-50-FPN_P5_1x.yaml`

**error messages:**

```
/home/tim/miniconda2/envs/maskrcnn_benchmark/bin/python /home/tim/maskrcnn-benchmark/tools/vis_model.py
torch.Size([1, 3, 800, 800])
BoxList(num_boxes=1, image_width=800, image_height=800, mode=xyxy)
Traceback (most recent call last):
  File "/home/tim/maskrcnn-benchmark/tools/vis_model.py", line 153, in <module>
    main()
  File "/home/tim/maskrcnn-benchmark/tools/vis_model.py", line 126, in main
    loss_dict = model(dummy_image, [dummy_target])
  File "/home/tim/miniconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tim/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/tim/miniconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tim/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/retinanet/retinanet.py", line 131, in forward
    return self._forward_train(anchors, box_cls, box_regression, targets)
  File "/home/tim/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/retinanet/retinanet.py", line 138, in _forward_train
    anchors, box_cls, box_regression, targets
  File "/home/tim/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/retinanet/loss.py", line 77, in __call__
    labels
  File "/home/tim/miniconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tim/maskrcnn-benchmark/maskrcnn_benchmark/layers/sigmoid_focal_loss.py", line 68, in forward
    loss = loss_func(logits, targets, self.gamma, self.alpha)
  File "/home/tim/maskrcnn-benchmark/maskrcnn_benchmark/layers/sigmoid_focal_loss.py", line 42, in sigmoid_focal_loss_cpu
    gamma = gamma[0]
TypeError: 'float' object is not subscriptable

Process finished with exit code 1
```

## Expected behavior

```
  File "maskrcnn-benchmark/maskrcnn_benchmark/layers/sigmoid_focal_loss.py", line 42, in sigmoid_focal_loss_cpu
    gamma = gamma[0]
TypeError: 'float' object is not subscriptable
```

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.0
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[pip] torchviz==0.0.1
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi
[conda] torchviz                  0.0.1                    pypi_0    pypi

**Comment by zhongqianli** [comment]
File "maskrcnn-benchmark/maskrcnn_benchmark/layers/sigmoid_focal_loss.py", line 42, in sigmoid_focal_loss_cpu：
**delete `gamma = gamma[0]` and `alpha = alpha[0]`**.
Then it works.
