### ISSUE TITLE
FBNet Pre-trained Weights for a Custom Dataset

### ISSUE THREAD

**Issue by mrteera** [facebookresearch/maskrcnn-benchmark#1050]
## ❓ Questions and Help

I'm trying to use FBNet as a [pre-trained weights](https://download.pytorch.org/models/maskrcnn/e2e_mask_rcnn_fbnet_600.pth) for my dataset. But it cannot load the weights using this utils https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/utils/c2_model_loading.py

Do you have any suggestion to load pre-trained FBNet weights for a custom dataset?

**Comment by Dorozhko-Anton** [comment]
`_load_c2_pickled_weights()` is used to load only Caffe2 checkpoints in `.pkl` format
https://github.com/facebookresearch/maskrcnn-benchmark/blob/24c8c90efdb7cc51381af5ce0205b23567c3cd21/maskrcnn_benchmark/utils/checkpoint.py#L132-L134

To load pre-trained weights into the model with different `ROI_BOX_HEAD.NUM_CLASSES` refer to 
https://github.com/facebookresearch/maskrcnn-benchmark#finetuning-from-detectron-weights-on-custom-datasets

To use `trim_detectron_model.py` suggested in README.md with `.pth` file check out #15 , more precisely https://github.com/facebookresearch/maskrcnn-benchmark/issues/15#issuecomment-498575917

**Comment by mrteera** [comment]
@Dorozhko-Anton Thank you. I successfully convert .pth model file using `trim_detectron_model`. These are my changed. I'll update again when I train a model with this pre-train weights.

```
_d =  torch.load(DETECTRON_PATH)
```

```
newdict['model'] = removekey(_d['model'],
['module.roi_heads.box.predictor.cls_score.bias', 'module.roi_heads.box.predictor.cls_score.weight', 'module.roi_heads.box.predictor.bbox_pred.bias', 'module.roi_heads.box.predictor.bbox_pred.weight'])
```

**Comment by simaiden** [comment]
@mrteera Have you trained sucessfull? I did the exact change to cut the final layers but when I try to train I have the following error:

`Traceback (most recent call last):
  File "tools/train_net.py", line 191, in <module>
    main()
  File "tools/train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 85, in train
    arguments,
  File "/home/simisepulveda/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 86, in do_train
    optimizer.step()
  File "/home/simisepulveda/.conda/envs/maskrcnn_benchmark2/lib/python3.7/site-packages/torch/optim/sgd.py", line 100, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: The size of tensor a (81) must match the size of tensor b (14) at non-singleton dimension 0`
