### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by as754770178** [facebookresearch/maskrcnn-benchmark#1080]
I exec `train_net.py`, the parameter `config-file` is `maskrcnn-benchmark/configs/e2e_mask_rcnn_R_50_FPN_1x.yaml`.
I change `maskrcnn-benchmark/configs/e2e_mask_rcnn_R_50_FPN_1x.yaml` as below:
```
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)
```
change `config.py` as below:
```
       "coco_2014_train": {
            "img_dir": "/home/xtz/hard_disk/disk_2/coco/images/train2014",
            "ann_file": "/home/xtz/hard_disk/disk_2/coco/annotations/instances_train2014.json"
        },
        "coco_2014_val": {
            "img_dir": "/home/xtz/hard_disk/disk_2/coco/images/val2014",
            "ann_file": "/home/xtz/hard_disk/disk_2/coco/annotations/instances_val2014.json"
        },
```

The program report error:
```
2019-09-10 21:43:16,942 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/tools/train_net.py", line 191, in <module>
    main()
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/tools/train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/tools/train_net.py", line 85, in train
    arguments,
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xtz/anaconda3/envs/pytorch_cp37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 94, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 223, in clip_to_image
    return self[keep]
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 208, in __getitem__
    bbox.add_field(k, v[item])
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 553, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "/home/xtz/deeplearning/rcnn/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 462, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range
```

**Comment by davemq** [comment]
See pull request #881. That fixed this problem for me.

**Comment by as754770178** [comment]
I change the code and rebuild, the error still exists.
I don't know how to uninstall, so I delete `maskrcnn-benchmark/build`, `maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so` and `maskrcnn-benchmark/maskrcnn_benchmark.egg-info`. After this, I exec `python setup.py build develop` to build

**Comment by davemq** [comment]
Sorry, I looked again, and I'm thinking #1053 is the one I used.

**Comment by davemq** [comment]
Also note similar issue #725.

**Comment by as754770178** [comment]
Thanks, the issue solved.

**Comment by yurui777** [comment]
> Thanks, the issue solved.

hello,I have met this problem ,could u tell me your way to solve it?
