### ISSUE TITLE
running train_net.py error

### ISSUE THREAD

**Issue by Hacker-Icechan** [facebookresearch/maskrcnn-benchmark#1085]
## ❓ Questions and Help
`{
    "images": [
        {
            "height": 2432,
            "width": 3248,
            "id": 1,
            "file_name": "kuangquanshui380ml105.jpg"
        }
    ],
    "categories": [
        {
            "supercategory": "Cancer",
            "id": 1,
            "name": "Nfsq380ml"
        }
    ],
    "annotations": [
        {
            "segmentation": [
                [
                    40.93023255813954,
                    1093.953488372093,
                    53.02325581395349,
                    1064.1860465116279,
                    76.27906976744187,
                    1038.6046511627908,
                    110.69767441860465,
                    1019.0697674418606,
                    145.58139534883722,
                    1001.8604651162791,
                    177.2093023255814,
                    993.953488372093,
                    210.2325581395349,
                    983.7209302325582,
                    253.48837209302326,
                    980.0,
                    285.58139534883725,
                    978.6046511627908,
                    318.13953488372096,
                    983.2558139534884,
                    342.7906976744186,
                    987.9069767441861,
                    367.90697674418607,
                    998.139534883721,
                    392.55813953488376,
                    1016.2790697674419,
                    409.3023255813954,
                    1034.418604651163,
                    421.8604651162791,
                    1059.0697674418604,
                    432.093023255814,
                    1095.3488372093025,
                    436.27906976744185,
                    1126.046511627907,
                    438.60465116279073,
                    1147.906976744186,
                    449.3023255813954,
                    1159.0697674418604,
                    459.0697674418605,
                    1176.2790697674418,
                    461.8604651162791,
                    1199.5348837209303,
                    460.4651162790698,
                    1220.46511627907,
                    453.48837209302326,
                    1232.5581395348838,
                    451.16279069767444,
                    1236.279069767442,
                    479.5348837209302,
                    1257.6744186046512,
                    515.8139534883721,
                    1287.906976744186,
                    546.9767441860465,
                    1319.0697674418604,
                    575.3488372093024,
                    1349.7674418604652,
                    596.2790697674419,
                    1376.7441860465117,
                    617.2093023255815,
                    1401.860465116279,
                    639.0697674418604,
                    1434.8837209302326,
                    656.2790697674419,
                    1467.906976744186,
                    673.953488372093,
                    1504.1860465116279,
                    692.5581395348837,
                    1548.8372093023256,
                    700.9302325581396,
                    1581.860465116279,
                    713.0232558139535,
                    1635.3488372093025,
                    717.2093023255815,
                    1667.906976744186,
                    717.2093023255815,
                    1697.6744186046512,
                    726.046511627907,
                    1741.3953488372094,
                    736.7441860465117,
                    1798.6046511627908,
                    745.1162790697675,
                    1838.139534883721,
                    751.6279069767443,
                    1883.2558139534885,
                    758.139534883721,
                    1914.8837209302326,
                    764.186046511628,
                    1950.6976744186047,
                    768.3720930232558,
                    1983.7209302325582,
                    777.6744186046512,
                    2022.7906976744187,
                    788.8372093023256,
                    2048.837209302326,
                    794.8837209302326,
                    2086.046511627907,
                    795.3488372093024,
                    2128.837209302326,
                    789.7674418604652,
                    2162.3255813953488,
                    780.9302325581396,
                    2203.2558139534885,
                    769.7674418604652,
                    2245.1162790697676,
                    754.4186046511628,
                    2275.813953488372,
                    736.2790697674419,
                    2302.3255813953488,
                    719.5348837209302,
                    2315.813953488372,
                    707.4418604651163,
                    2317.2093023255816,
                    696.7441860465117,
                    2343.2558139534885,
                    686.046511627907,
                    2360.4651162790697,
                    659.5348837209302,
                    2375.813953488372,
                    624.186046511628,
                    2395.813953488372,
                    599.5348837209302,
                    2406.9767441860467,
                    574.8837209302326,
                    2399.0697674418607,
                    568.3720930232558,
                    2399.5348837209303,
                    561.3953488372093,
                    2413.4883720930234,
                    554.4186046511628,
                    2421.860465116279,
                    538.6046511627907,
                    2427.4418604651164,
                    513.0232558139535,
                    2430.232558139535,
                    450.69767441860466,
                    2430.697674418605,
                    431.6279069767442,
                    2426.9767441860467,
                    415.81395348837214,
                    2413.4883720930234,
                    389.30232558139534,
                    2417.6744186046512,
                    369.7674418604651,
                    2408.3720930232557,
                    342.3255813953489,
                    2388.3720930232557,
                    317.6744186046512,
                    2373.4883720930234,
                    285.58139534883725,
                    2339.5348837209303,
                    262.7906976744186,
                    2307.4418604651164,
                    248.37209302325581,
                    2263.2558139534885,
                    237.2093023255814,
                    2230.697674418605,
                    219.53488372093025,
                    2181.3953488372094,
                    205.11627906976744,
                    2135.3488372093025,
                    190.69767441860466,
                    2099.0697674418607,
                    174.88372093023256,
                    2056.279069767442,
                    155.34883720930233,
                    2006.5116279069769,
                    137.67441860465118,
                    1956.7441860465117,
                    116.74418604651163,
                    1904.186046511628,
                    97.67441860465117,
                    1863.2558139534885,
                    78.6046511627907,
                    1833.0232558139535,
                    66.51162790697674,
                    1794.418604651163,
                    52.55813953488372,
                    1753.953488372093,
                    43.25581395348837,
                    1713.4883720930234,
                    40.46511627906977,
                    1672.5581395348838,
                    36.27906976744186,
                    1634.8837209302326,
                    37.674418604651166,
                    1589.7674418604652,
                    42.32558139534884,
                    1546.046511627907,
                    47.44186046511628,
                    1504.1860465116279,
                    58.139534883720934,
                    1457.6744186046512,
                    67.90697674418605,
                    1421.860465116279,
                    82.79069767441861,
                    1375.3488372093025,
                    98.13953488372094,
                    1339.5348837209303,
                    108.37209302325581,
                    1320.46511627907,
                    95.34883720930233,
                    1313.0232558139535,
                    80.93023255813954,
                    1300.9302325581396,
                    71.62790697674419,
                    1290.2325581395348,
                    64.65116279069768,
                    1266.9767441860465,
                    64.65116279069768,
                    1249.3023255813955,
                    72.09302325581396,
                    1237.2093023255813,
                    61.395348837209305,
                    1220.46511627907,
                    53.48837209302326,
                    1193.953488372093,
                    41.86046511627907,
                    1153.0232558139535,
                    36.74418604651163,
                    1125.1162790697674,
                    35.348837209302324,
                    1111.1627906976744,
                    40.93023255813954,
                    1064.1860465116279,
                    53.02325581395349,
                    1093.953488372093
                ]
            ],
            "iscrowd": 0,
            "image_id": 1,
            "bbox": [
                35.0,
                978.0,
                760.0,
                1452.0
            ],
            "area": 1103520.0,
            "category_id": 1,
            "id": 1
        }
    ]
}`

aded from conv1.weight                 of shape (64, 3, 7, 7)
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2019-09-11 20:41:51,037 maskrcnn_benchmark.utils.miscellaneous WARNING: Dataset [ConcatDataset] has no categories attribute, labels.json file won't be created
2019-09-11 20:41:51,037 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 191, in <module>
    main()
  File "tools/train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 85, in train
    arguments,
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 206, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 94, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 223, in clip_to_image
    return self[keep]
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 208, in __getitem__
    bbox.add_field(k, v[item])
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 555, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 463, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range

Traceback (most recent call last):
  File "tools/train_net.py", line 191, in <module>
    main()
  File "tools/train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 85, in train
    arguments,
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 206, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 94, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 223, in clip_to_image
    return self[keep]
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 208, in __getitem__
    bbox.add_field(k, v[item])
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 555, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "/home/文档/JlSupermarket/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 463, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range

Traceback (most recent call last):
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/anaconda3/envs/maskrcnn-market/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/maskrcnn-market/bin/python', '-u', 'tools/train_net.py', '--local_rank=1', '--config-file', 'configs/e2e_mask_rcnn_R_101_FPN_1x.yaml']' returned non-zero exit status 1.

**Comment by Darshan2701** [comment]
@Hacker-Icechan Seems like the issue in #725

**Comment by wufan-zhao** [comment]
still have similar issue,
Traceback (most recent call last):
  File "/home/wufan/Projects/maskrcnn-benchmark/tools/train_net.py", line 201, in <module>
    main()
  File "/home/wufan/Projects/maskrcnn-benchmark/tools/train_net.py", line 194, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/wufan/Projects/maskrcnn-benchmark/tools/train_net.py", line 94, in train
    arguments,
  File "/home/wufan/Projects/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 72, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/wufan/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 551, in __next__
    return self._process_next_batch(batch)
  File "/home/wufan/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 572, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/wufan/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wufan/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wufan/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/wufan/Projects/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 94, in __getitem__
    target = target.clip_to_image(remove_empty=True)
  File "/home/wufan/Projects/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 223, in clip_to_image
    return self[keep]
  File "/home/wufan/Projects/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 208, in __getitem__
    bbox.add_field(k, v[item])
  File "/home/wufan/Projects/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 557, in __getitem__
    selected_instances = self.instances.__getitem__(item)
  File "/home/wufan/Projects/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 466, in __getitem__
    selected_polygons.append(self.polygons[i])
IndexError: list index out of range

current environment: 
pytorch 1.1.0
pytorch-nightly 1.0.0
torchvision 0.2.2
cuda 9.0

tried solutions of #725 #1053 #1080 but still not work. Anyone could help with this, thanks.

**Comment by Zy1013921842** [comment]
@Hi, I am in the same situation as you are and I also use pytorch=1.1. #725 may works for pytorch=1.2 but not ours. I referenced #704 which says it might be the problem with the mismatch of size between item and self.polygons in segmentation_mask.py. I slove this by manually make them match in size like below: 

def __getitem__(self, item):
        if isinstance(item, int):
            selected_polygons = [self.polygons[item]]
        elif isinstance(item, slice):
            selected_polygons = self.polygons[item]
        else:
            # advanced indexing on a single dimension
            selected_polygons = []
            if isinstance(item, torch.Tensor) and item.dtype == torch.uint8:
                item = item.nonzero()
                item = item.squeeze(1) if item.numel() > 0 else item
                item = item.tolist()
            Indexerror_num = 0

            if len(item) != len(self.polygons):
                item = item[:len(self.polygons)]
                
            for i in item:
                    selected_polygons.append(self.polygons[i])
                    Indexerror_num += 1
        return PolygonList(selected_polygons, size=self.size)

 but again I got another ValueError:  Target size (torch.Size([3, 28, 28])) must be the same as input size (torch.Size([5, 28, 28])). You can try my method to see if  you can solve the IndexError and whether it works fine directly or meet the ValueError like I did.

For more detail #1167 in whcih I descriped my problem.

**Comment by nancymao** [comment]
@williamwf  Hi, did you solved the problem? I have exactly the  same problem as you. Could you please tell me the solution?Many Thx!
