### ISSUE TITLE
I have error by running python tools/train_net.py on win10 (UnicodeDecodeError:)

### ISSUE THREAD

**Issue by Hung-Hsiang-617** [facebookresearch/maskrcnn-benchmark#1136]
## To Reproduce

(C:\Users\B\Anaconda3\envs\benchmark) C:\Users\B\test\maskrcnn-benchmark-master>python tools/train_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 S
OLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1 MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN 2000
2019-10-13 18:24:39,137 maskrcnn_benchmark INFO: Using 1 GPUs
2019-10-13 18:24:39,138 maskrcnn_benchmark INFO: Namespace(config_file='configs/e2e_mask_rcnn_R_50_FPN_1x.yaml', distributed=False, local_rank=0, opts=['SOLVER.IMS_PER_BATCH', '2', 'SOL
VER.BASE_LR', '0.0025', 'SOLVER.MAX_ITER', '720000', 'SOLVER.STEPS', '(480000, 640000)', 'TEST.IMS_PER_BATCH', '1', 'MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN', '2000'], skip_test=False)
2019-10-13 18:24:39,139 maskrcnn_benchmark INFO: Collecting env info (might take some time)
Traceback (most recent call last):
  File "tools/train_net.py", line 200, in <module>
    main()
  File "tools/train_net.py", line 180, in main
    logger.info("\n" + collect_env_info())
  File "c:\users\b\test\maskrcnn-benchmark-master\maskrcnn_benchmark\utils\collect_env.py", line 12, in collect_env_info
    env_str = get_pretty_env_info()
  File "C:\Users\B\Anaconda3\envs\benchmark\lib\site-packages\torch\utils\collect_env.py", line 378, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "C:\Users\B\Anaconda3\envs\benchmark\lib\site-packages\torch\utils\collect_env.py", line 276, in get_env_info
    os=get_os(run_lambda),
  File "C:\Users\B\Anaconda3\envs\benchmark\lib\site-packages\torch\utils\collect_env.py", line 196, in get_os
    return get_windows_version(run_lambda)
  File "C:\Users\B\Anaconda3\envs\benchmark\lib\site-packages\torch\utils\collect_env.py", line 180, in get_windows_version
    return run_and_read_all(run_lambda, 'wmic os get Caption | findstr /v Caption')
  File "C:\Users\B\Anaconda3\envs\benchmark\lib\site-packages\torch\utils\collect_env.py", line 54, in run_and_read_all
    rc, out, _ = run_lambda(command)
  File "C:\Users\B\Anaconda3\envs\benchmark\lib\site-packages\torch\utils\collect_env.py", line 45, in run
    output = output.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 21: invalid start byte

## Expected behavior

def run(command):
    """Returns (return-code, stdout, stderr)"""
    p = subprocess.Popen(command, stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE, shell=True)
    output, err = p.communicate()
    rc = p.returncode
    if PY3:
        output = output.decode("utf-8")
        err = err.decode("utf-8")
    return rc, output.strip(), err.strip()

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.1.0
 - OS (e.g., Linux):win10
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):
 - Python version:3.6.3
 - CUDA/cuDNN version:9.0  ,  7.6.3
 - GPU models and configuration:1060ti
 - Any other relevant information:

**Comment by GisuHwang0312** [comment]
I had the same problem.
The fix was as follows.

def run(command):
"""Returns (return-code, stdout, stderr)"""
p = subprocess.Popen(command, stdout=subprocess.PIPE,
stderr=subprocess.PIPE, shell=True)
output, err = p.communicate()
rc = p.returncode
if PY3:
output = output.decode("gbk")
err = err.decode("gbk")
return rc, output.strip(), err.strip()

**Comment by Peter-weng** [comment]
I had the same prolem,it's work on my win10 system

if PY3:
        output = output.decode("utf-8","ignore")
        err = err.decode("utf-8","ignore")
