### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by CindyHuang23** [facebookresearch/maskrcnn-benchmark#1154]
## ❓ Questions and Help

In my code, the input image size is 1024*1024. The config file which I use is e2e_mask_rcnn_R_101_FPN_1x.yaml . For the number of GPU I use is 1，I set lr=0.0025,and batch size =2.

the error happend when training 82800.

who can help me ?Thank you very much!!

 
Traceback (most recent call last):
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/tools/train_net.py", line 191, in <module>
    main()
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/tools/train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/tools/train_net.py", line 85, in train
    arguments,
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 71, in do_train
    loss_dict = model(images, targets)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 39, in forward
    x, detections, loss_mask = self.mask(mask_features, detections, targets)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/mask_head.py", line 77, in forward
    loss_mask = self.loss_evaluator(proposals, mask_logits, targets)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py", line 112, in __call__
    labels, mask_targets = self.prepare_targets(proposals, targets)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py", line 94, in prepare_targets
    segmentation_masks, positive_proposals, self.discretization_size
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py", line 37, in project_masks_on_boxes
    scaled_mask = cropped_mask.resize((M, M))
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 522, in resize
    resized_instances = self.instances.resize(size)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 427, in resize
    resized_polygons.append(polygon.resize(size))
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 307, in resize
    float(s) / float(s_orig) for s, s_orig in zip(size, self.size)
  File "/home/lyy/anaconda3/envs/maskrcnn_benchmark/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 307, in <genexpr>
    float(s) / float(s_orig) for s, s_orig in zip(size, self.size)
ZeroDivisionError: float division by zero

Process finished with exit code 1

**Comment by zlyx525** [comment]
I met the same issue. Did you solve it?

**Comment by JunnnnChen** [comment]
I met the same issue. Did you solve it?

**Comment by AnjuMKaimal** [comment]
how to resolve this?
