### ISSUE TITLE
Test Error with RetinaNet, RuntimeError: shape '[-1, 8]' is invalid for input of size 60

### ISSUE THREAD

**Issue by ZhuoyaYang** [facebookresearch/maskrcnn-benchmark#1155]
## ❓ Questions and Help
Train on my datasets, class_num = 2

  0%|                                                                          | 0/2659 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "tools/test_net.py", line 115, in <module>
    main()
  File "tools/test_net.py", line 109, in main
    output_folder=output_folder,
  File "/data/yzy/maskrcnn_install/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 84, in inference
    predictions = compute_on_dataset(model, data_loader, device, bbox_aug, inference_timer)
  File "/data/yzy/maskrcnn_install/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 27, in compute_on_dataset
    output = im_detect_bbox_aug(model, images, device)
  File "/data/yzy/maskrcnn_install/maskrcnn-benchmark/maskrcnn_benchmark/engine/bbox_aug.py", line 66, in im_detect_bbox_aug
    results.append(post_processor.filter_results(boxlist, cfg.MODEL.ROI_BOX_HEAD.NUM_CLASSES))
  File "/data/yzy/maskrcnn_install/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py", line 120, in filter_results
    boxes = boxlist.bbox.reshape(-1, num_classes * 4)
RuntimeError: shape '[-1, 8]' is invalid for input of size 60

I want to know if anyone has successfully trained on their own dataset with RetinaNet？？
Thanks for any help！！

**Comment by ZhuoyaYang** [comment]
I rebuild again. It works well. 
Don't know why there was a problem before. But I think no problem with the code.
