### ISSUE TITLE
Bug in GroupedBatchSampler

### ISSUE THREAD

**Issue by stevehjc** [facebookresearch/maskrcnn-benchmark#1176]
## To Reproduce

add test case
```python
# tests/test_data_samplers.py
    def test_permute_subset_sampler_ver2(self):
        batch_size = 3
        drop_uneven = False
        dataset = [i for i in range(10)]
        group_ids = [0, 0, 1, 0, 1, 1, 0, 1, 1, 0]
        sampler = SubsetSampler([2, 4, 5, 7, 8])  # Something similar happened in my dataset

        batch_sampler = GroupedBatchSampler(sampler, group_ids, batch_size, drop_uneven)
        result = list(batch_sampler)   # error

        expected = [[2, 4, 5], [7, 8]]
        self.assertEqual(result, expected)
```

## Expected behavior

```shell
...E.....
======================================================================
ERROR: test_permute_subset_sampler_ver2 (__main__.TestGroupedBatchSampler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/han/SSD/mCode/maskrcnn_benchmark/tests/test_data_samplers.py", line 93, in test_permute_subset_sampler_ver2
    result = list(batch_sampler)  # error
  File "/media/han/SSD/mCode/maskrcnn_benchmark/data/samplers/grouped_batch_sampler.py", line 107, in __iter__
    batches = self._prepare_batches()
  File "/media/han/SSD/mCode/maskrcnn_benchmark/data/samplers/grouped_batch_sampler.py", line 79, in _prepare_batches
    first_element_of_batch = [t[0].item() for t in merged]
  File "/media/han/SSD/mCode/maskrcnn_benchmark_fork/FCOS-master/fcos_core/data/samplers/grouped_batch_sampler.py", line 79, in <listcomp>
    first_element_of_batch = [t[0].item() for t in merged]
IndexError: index 0 is out of bounds for dimension 0 with size 0

----------------------------------------------------------------------
Ran 9 tests in 1.468s

FAILED (errors=1)
```

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by 5RJ** [comment]
In the same file, add this sentence 
merged = [ele for ele in merged if len(ele) > 0]
after "merged = tuple(itertools.chain.from_iterable(splits))"
