### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm) ??

### ISSUE THREAD

**Issue by edwardcho** [facebookresearch/maskrcnn-benchmark#1185]
## ❓ Questions and Help
Hello Sir,
I met some errors.

$> python tools/train_net.py --config-file "configs/rpn_R_50_C4_1x.yaml"

error message..
loading annotations into memory...
Done (t=12.23s)
creating index...
index created!
loading annotations into memory...
Done (t=14.55s)
creating index...
index created!
2019-12-11 05:25:20,688 maskrcnn_benchmark.utils.miscellaneous WARNING: Dataset [ConcatDataset] has no categories attribute, labels.json file won't be created
2019-12-11 05:25:21,147 maskrcnn_benchmark.trainer INFO: Start training
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 315, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_2286_2857144775>
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 315, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_2288_348109391>

I wonder what is problem.
How to solve it?

**Comment by edwardcho** [comment]
I changed default value of num_worker in default.py

_C.DATALOADER.NUM_WORKERS = 1

Anyway, this problem should solve it..

**Comment by edwardcho** [comment]
At above comment, I was changed num_workers as default. But this is not correct.
when batch_size = 1, this logic seems operate normally,
but batch_size != 1, this logic was occured shm errors like my first comment.
