### ISSUE TITLE
TypeError When running the demo.py

### ISSUE THREAD

**Issue by PengYida** [facebookresearch/maskrcnn-benchmark#1217]
I have installed the program but when I try to run a demo:
Traceback (most recent call last):
  File "demo.py", line 29, in <module>
    predictions = coco_demo.run_on_opencv_image(img)
  File "/home/yudongran/pyd/mask-rcnn/maskrcnn-benchmark/demo/predictor.py", line 220, in run_on_opencv_image
    result = self.overlay_class_names(result, top_predictions)
  File "/home/yudongran/pyd/mask-rcnn/maskrcnn-benchmark/demo/predictor.py", line 403, in overlay_class_names
    cv2.putText(
TypeError: only integer tensors of a single element can be converted to an index

**Comment by PengYida** [comment]
![image](https://user-images.githubusercontent.com/42318123/76165064-e5fc7800-618e-11ea-9eba-b345d801fad9.png)
The problem is about the methods: overlay_keypoints and overlay_class_names. When I deleted these two methods I got the results but the output image has no label and the accuracy.

**Comment by PengYida** [comment]
I have found the reason:
When you try to put the label in the image using cv2.putTest()
x, y should be Integer. Add a int() to convert the type of x & y, so the program is working.
