### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Coconut443** [facebookresearch/maskrcnn-benchmark#1220]
## ❓ Questions and Help
I‘m training my own datasets for instance segmentation on win10 system.
And the error information:
Traceback (most recent call last):
  File "tools/train_net.py", line 186, in <module>
    main()
  File "tools/train_net.py", line 179, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 77, in train
    do_train(
  File "c:\users\12066\maskrcnn-benchmark\maskrcnn_benchmark\engine\trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "C:\Users\12066\anaconda3\envs\mb\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\12066\anaconda3\envs\mb\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\12066\anaconda3\envs\mb\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\12066\anaconda3\envs\mb\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\12066\anaconda3\envs\mb\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\12066\anaconda3\envs\mb\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "c:\users\12066\maskrcnn-benchmark\maskrcnn_benchmark\data\collate_batch.py", line 17, in __call__
    images = to_image_list(transposed_batch[0], self.size_divisible)
  File "c:\users\12066\maskrcnn-benchmark\maskrcnn_benchmark\structures\image_list.py", line 50, in to_image_list
    max_size = tuple(max(s) for s in zip(*[img.shape for img in tensors]))
  File "c:\users\12066\maskrcnn-benchmark\maskrcnn_benchmark\structures\image_list.py", line 50, in <listcomp>
    max_size = tuple(max(s) for s in zip(*[img.shape for img in tensors]))
AttributeError: 'Image' object has no attribute 'shape'

I'm wondering if it's because my torch version or something else. HELP!

**Comment by minhkhoale** [comment]
I met the same problem and still cant afford to solve it.

**Comment by senthurRam33** [comment]
If you are using Pillow for image interpolation, you can get the shape of the image like width and weight, you can use Image.size That returns a tuple that contains width and height respectively.
