### ISSUE TITLE
How to change the "num_class" when using the pre-trained model?

### ISSUE THREAD

**Issue by zhanxinrui** [facebookresearch/maskrcnn-benchmark#1235]
## ❓ Questions and Help
I want to change the 'num_class' from 81 to 2 based on the pre-trained model. When I simply changed it in config file. I got the error info as followed:

---

Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/hdd/zhanxinrui/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/hdd/zhanxinrui/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/zhanxinrui/MOT/maskrcnn-benchmark/tools/train_net.py", line 208, in <module>
    main()
  File "/home/zhanxinrui/MOT/maskrcnn-benchmark/tools/train_net.py", line 201, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/zhanxinrui/MOT/maskrcnn-benchmark/tools/train_net.py", line 65, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/zhanxinrui/MOT/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 62, in load
    self._load_model(checkpoint)
  File "/home/zhanxinrui/MOT/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 100, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"))
  File "/home/zhanxinrui/MOT/maskrcnn-benchmark/maskrcnn_benchmark/utils/model_serialization.py", line 80, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/home/zhanxinrui/anaconda/envs/mrcnn-benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
	size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([81, 1024]) from checkpoint, the shape in current model is torch.Size([2, 1024]).
	size mismatch for roi_heads.box.predictor.cls_score.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for roi_heads.box.predictor.bbox_pred.weight: copying a param with shape torch.Size([324, 1024]) from checkpoint, the shape in current model is torch.Size([8, 1024]).
	size mismatch for roi_heads.box.predictor.bbox_pred.bias: copying a param with shape torch.Size([324]) from checkpoint, the shape in current model is torch.Size([8]).
	size mismatch for roi_heads.mask.predictor.mask_fcn_logits.weight: copying a param with shape torch.Size([81, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 256, 1, 1]).
	size mismatch for roi_heads.mask.predictor.mask_fcn_logits.bias: copying a param with shape torch.Size([81]) from checkpoint, the shape in current model is torch.Size([2]).

---

I guess I should remove pre-trained predictor weights or not load these weights. But how am I suppose to do this easily,  Can you give me some tips?

**Comment by Kenneth-X** [comment]
https://github.com/facebookresearch/maskrcnn-benchmark/issues/521

**Comment by ZhangHerman** [comment]
#Load the model in python
import torch
model = torch.load("coco_base_pretrained.pth")
#Remove the previous training parameters. 
#del model['iteration']
#del model['scheduler']
#del model['optimizer']
#Remove the output layers in COCO, these are the mismatched layers you saw.
#Second stage prediction//删除两次
#del model["model"]["module.roi_heads.box.predictor.cls_score.weight"]
#del model["model"]["module.roi_heads.box.predictor.cls_score.bias"]
#del model["model"]["roi_heads.box.predictor.bbox_pred.weight"]
#del model["model"]["roi_heads.box.predictor.bbox_pred.bias"]
#mask prediction
#del model["model"]["roi_heads.mask.predictor.mask_fcn_logits.weight"]

#del model["model"]["roi_heads.mask.predictor.mask_fcn_logits.bias"]
#RPN
#del model["model"]["rpn.head.cls_logits.weight"]
#del model["model"]["rpn.head.cls_logits.bias"]
#del model["model"]["rpn.head.bbox_pred.weight"]
#del model["model"]["rpn.head.bbox_pred.bias"]
#save the model
torch.save(model, "coco_base_pretrained.pth")


把每行最前面的＃去掉，pth更换成预训练的模型，删除相应不匹配的层。
