### ISSUE TITLE
python setup.py build develop编译出错

### ISSUE THREAD

**Issue by xiaoli-ai** [facebookresearch/maskrcnn-benchmark#1242]
我的环境：windows10  pytorch1.6  python3.8  VC14.1
我的电脑没有GPU，但是安装了CUDA和cudnn，在编译apex的时候，使用python setup.py install --cuda_ext --cpp_ext会报错，网上有查到去掉--cuda_ext --cpp_ext，可以成功，不知道这个是干嘛用的，但确实去掉会成功，在执行python setup.py build develop的时候，报出了如下错误，暂时还没有解决，求指导 ，感谢
(pytorch) C:\Users\zgli\Desktop\detect\maskrcnn-benchmark>python setup.py build develop
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0'
running build
running build_py
running build_ext
D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py:264: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'maskrcnn_benchmark._C' extension
Emitting ninja build file C:\Users\zgli\Desktop\detect\maskrcnn-benchmark\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\TH -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\THC -ID:\anaconda\envs\pytorch\include -ID:\anaconda\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64 -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.17763.0\shared" "-ID:\Windows Kits\10\Include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\Include\10.0.17763.0\um" "-ID:\Windows Kits\10\Include\10.0.17763.0\winrt" -c C:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\vision.cpp /FoC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\build\temp.win-amd64-3.8\Release\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\vision.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/zgli/Desktop/detect/maskrcnn-benchmark/build/temp.win-amd64-3.8/Release/Users/zgli/Desktop/detect/maskrcnn-benchmark/maskrcnn_benchmark/csrc/vision.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\TH -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\THC -ID:\anaconda\envs\pytorch\include -ID:\anaconda\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64 -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.17763.0\shared" "-ID:\Windows Kits\10\Include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\Include\10.0.17763.0\um" "-ID:\Windows Kits\10\Include\10.0.17763.0\winrt" -c C:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\vision.cpp /FoC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\build\temp.win-amd64-3.8\Release\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\vision.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[2/3] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\TH -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\THC -ID:\anaconda\envs\pytorch\include -ID:\anaconda\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64 -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.17763.0\shared" "-ID:\Windows Kits\10\Include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\Include\10.0.17763.0\um" "-ID:\Windows Kits\10\Include\10.0.17763.0\winrt" -c C:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\ROIAlign_cpu.cpp /FoC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\build\temp.win-amd64-3.8\Release\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\ROIAlign_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/zgli/Desktop/detect/maskrcnn-benchmark/build/temp.win-amd64-3.8/Release/Users/zgli/Desktop/detect/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\TH -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\THC -ID:\anaconda\envs\pytorch\include -ID:\anaconda\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64 -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.17763.0\shared" "-ID:\Windows Kits\10\Include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\Include\10.0.17763.0\um" "-ID:\Windows Kits\10\Include\10.0.17763.0\winrt" -c C:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\ROIAlign_cpu.cpp /FoC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\build\temp.win-amd64-3.8\Release\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\ROIAlign_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[3/3] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\TH -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\THC -ID:\anaconda\envs\pytorch\include -ID:\anaconda\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64 -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.17763.0\shared" "-ID:\Windows Kits\10\Include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\Include\10.0.17763.0\um" "-ID:\Windows Kits\10\Include\10.0.17763.0\winrt" -c C:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\nms_cpu.cpp /FoC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\build\temp.win-amd64-3.8\Release\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\nms_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/zgli/Desktop/detect/maskrcnn-benchmark/build/temp.win-amd64-3.8/Release/Users/zgli/Desktop/detect/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\TH -ID:\anaconda\envs\pytorch\lib\site-packages\torch\include\THC -ID:\anaconda\envs\pytorch\include -ID:\anaconda\envs\pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-ID:\Windows Kits\10\include\10.0.18362.0\ucrt" "-ID:\Windows Kits\10\include\10.0.18362.0\shared" "-ID:\Windows Kits\10\include\10.0.18362.0\um" "-ID:\Windows Kits\10\include\10.0.18362.0\winrt" "-ID:\Windows Kits\10\include\10.0.18362.0\cppwinrt" -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64 -ID:\VisualStudio\VC\Tools\MSVC\14.16.27023\include "-ID:\Windows Kits\10\Include\10.0.17763.0\shared" "-ID:\Windows Kits\10\Include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\Include\10.0.17763.0\um" "-ID:\Windows Kits\10\Include\10.0.17763.0\winrt" -c C:\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\nms_cpu.cpp /FoC:\Users\zgli\Desktop\detect\maskrcnn-benchmark\build\temp.win-amd64-3.8\Release\Users\zgli\Desktop\detect\maskrcnn-benchmark\maskrcnn_benchmark\csrc\cpu\nms_cpu.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1466, in _run_ninja_build
    subprocess.run(
  File "D:\anaconda\envs\pytorch\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    setup(
  File "D:\anaconda\envs\pytorch\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "D:\anaconda\envs\pytorch\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\anaconda\envs\pytorch\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\anaconda\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\anaconda\envs\pytorch\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "D:\anaconda\envs\pytorch\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda\envs\pytorch\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\anaconda\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "D:\anaconda\envs\pytorch\lib\site-packages\cython-3.0a4-py3.8.egg\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\anaconda\envs\pytorch\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 633, in build_extensions
    build_ext.build_extensions(self)
  File "D:\anaconda\envs\pytorch\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\anaconda\envs\pytorch\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\anaconda\envs\pytorch\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\anaconda\envs\pytorch\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 606, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1206, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1484, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by vanessasidrim** [comment]
I have the same problem.

I use:

Ubuntu 18.04
GCC 7.5
CUDA 10.1
Pytorch 1.5

Have you got solved the problem?

**Comment by BlackHandguy** [comment]
请问您解决了吗？我也有相同的问题

**Comment by vanessasidrim** [comment]
Yes, I install torchvision 0.5.0.

When installing torchvision in version 0.5.0, the pytorch version will be downgraded to 1.4.0.

**Comment by liu-zhi97** [comment]
请问您解决了吗，我也是这个问题

**Comment by vanessasidrim** [comment]
Yes, I install torchvision 0.5.0.

conda install pytorch torchvision=0.5.0 cudatoolkit=10.1 -c pytorch

**Comment by liu-zhi97** [comment]
> Yes, I install torchvision 0.5.0.
> 
> conda install pytorch torchvision=0.5.0 cudatoolkit=10.1 -c pytorch

Thank you. According to this, I don't have this problem, but GCC on the server is version 4.8, and I still haven't made it. I don't have permission to switch to GCC

**Comment by vanessasidrim** [comment]
I used GCC 7.3 but I believe that the version you are using will not interfere with the execution

**Comment by cemiboou** [comment]
I had the same problem.Have you got solved the problem?

**Comment by shuang1204** [comment]
我也遇到了同样的问题，你们解决了吗@Vanessasidrim

**Comment by vanessasidrim** [comment]
I install torchvision 0.5.0, the pytorch version will be downgraded to 1.4.0.

**Comment by enaserianhanzaei** [comment]
@vanessasidrim it worked !! thanks

**Comment by DbrRoxane** [comment]
I followed the instruction [there ](https://github.com/amazon-research/siam-mot/blob/main/readme/INSTALL.md) and solved this issue by typing

```
cuda_dir="maskrcnn_benchmark/csrc/cuda"
perl -i -pe 's/AT_CHECK/TORCH_CHECK/' $cuda_dir/deform_pool_cuda.cu $cuda_dir/deform_conv_cuda.cu
# You can then run the regular setup command
python3 setup.py build develop

```
Now it works with CUDA 11.0 and Pytorch 1.7

Hope it helps!

**Comment by gzgz-code** [comment]
> 我按照[那里](https://github.com/amazon-research/siam-mot/blob/main/readme/INSTALL.md)的说明并通过键入解决了这个问题
> 
> ```
> cuda_dir="maskrcnn_benchmark/csrc/cuda"
> perl -i -pe 's/AT_CHECK/TORCH_CHECK/' $cuda_dir/deform_pool_cuda.cu $cuda_dir/deform_conv_cuda.cu
> # You can then run the regular setup command
> python3 setup.py build develop
> ```
> 
> 现在它适用于 CUDA 11.0 和 Pytorch 1.7
> 
> 希望能帮助到你！

Thank you very much for your answer. It helped me！

**Comment by leekwunfung817** [comment]
Do not use the native Python, it will not solve the environmental problems automatically.

Exceute this!
conda install -c jjh_cio_testing/label/in_defaults torchvision-gpu

Any packages should install with an appropriate package manager, the Facebook researcher made the mistake of ignoring the C++ compile issues in various installation combinations and different environments.

**Comment by jiajunhua** [comment]
I have the same problem. 
I have installed CUDA and cudnn，but when compiling apex，however, when run "python setup.py install --cuda_ext --cpp_ext" will occur some problems follows，but when  I remove "--cuda_ext --cpp_ext"，is succeed to install.
D:\Anaconda\envs\scene_graph_benchmark\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(624): note: see reference to class template instantiation 'c10::ArrayRef<c10::IValue>' being compiled
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by jiajunhua** [comment]
When I  run "python setup.py build develop", I have the  same problem as follows:
D:\Anaconda\envs\scene_graph_benchmark\lib\site-packages\torch\include\c10/util/variant.h(2748): note: see reference to function template instantiation 'decltype(auto) c10::detail_::visitation::variant::visit_value<T,V&>(Visitor &&,V &)' being compiled
        with
        [
            T=torch::enumtype::_compute_enum_name,
            V=torch::nn::EmbeddingBagMode,
            Visitor=torch::enumtype::_compute_enum_name
        ]
D:\Anaconda\envs\scene_graph_benchmark\lib\site-packages\torch\include\torch\csrc\api\include\torch/enum.h(164): note: see reference to function template instantiation 'decltype(auto) c10::visit<torch::enumtype::_compute_enum_name,V&>(Visitor &&,V &)' being compiled
        with
        [
            V=torch::nn::EmbeddingBagMode,
            Visitor=torch::enumtype::_compute_enum_name
        ]
D:\Anaconda\envs\scene_graph_benchmark\lib\site-packages\torch\include\torch\csrc\api\include\torch/nn/functional/embedding.h(115): note: see reference to function template instantiation 'std::string torch::enumtype::get_enum_name<torch::nn::EmbeddingBagMode>(V)' being compiled
        with
        [
            V=torch::nn::EmbeddingBagMode
        ]
D:\Anaconda\envs\scene_graph_benchmark\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(624): note: see reference to class template instantiation 'c10::ArrayRef<c10::IValue>' being compiled
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by SYLin117** [comment]
Got the same problem.

using:
>   Ubuntu 20
>     GCC 7.5
>     CUDA 9.2 
>     cudnn 7.4.2
>     Pytorch 1.2
>     torchvision 0.4.0

I have tried `python setup.py install --cuda_ext --cpp_ext` and `pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./` both not working and suddenly `python setup.py install` works.
Got no idea what's going on.

**Comment by MeinhardMark** [comment]
> I followed the instruction [there ](https://github.com/amazon-research/siam-mot/blob/main/readme/INSTALL.md) and solved this issue by typing
> 
> ```
> cuda_dir="maskrcnn_benchmark/csrc/cuda"
> perl -i -pe 's/AT_CHECK/TORCH_CHECK/' $cuda_dir/deform_pool_cuda.cu $cuda_dir/deform_conv_cuda.cu
> # You can then run the regular setup command
> python3 setup.py build develop
> ```
> 
> Now it works with CUDA 11.0 and Pytorch 1.7
> 
> Hope it helps!

I tried this but didn't solve the problem. I use CUDA 11.1, Pytorch 1.8 and Python 3.7
