### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by kaiguoscut** [facebookresearch/maskrcnn-benchmark#1262]
I had problems installing apex extending and maskrcnn-benchmark extending when I installed it according to the Install.md step by step. Some error messages are as follows:
FAILED: /home/guo/WorkSpace/apex/build/temp.linux-x86_64-3.6/csrc/mlp_cuda.o 
/usr/local/cuda-10.1/bin/nvcc -I/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/include -I/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/include/TH -I/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/guo/anaconda3/envs/maskrcnn/include/python3.6m -c -c /home/guo/WorkSpace/apex/csrc/mlp_cuda.cu -o /home/guo/WorkSpace/apex/build/temp.linux-x86_64-3.6/csrc/mlp_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=mlp_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(14): warning: integer conversion resulted in a change of sign

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 419, in <module>
    extras_require=extras,
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/guo/anaconda3/envs/maskrcnn/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by WilliamLLee** [comment]
Have you fix this problem? I meet the same error, too!

**Comment by buaaswf** [comment]
I met this too.

**Comment by du666888999** [comment]
I met this too.
