### ISSUE TITLE
No such file or directory: 'datasets/coco/val2014/COCO_val2014_000000172616.jpg'

### ISSUE THREAD

**Issue by xuemeikim** [facebookresearch/maskrcnn-benchmark#1266]
## ❓ Questions and Help
When I do " python train_net.py --config-file "/root/anaconda3/envs/maskrcnn-benchmark/configs/e2e_faster_rcnn_R_50_FPN_1x.yaml""
I got the problem:
Traceback (most recent call last):
  File "train_net.py", line 201, in <module>
    main()
  File "train_net.py", line 194, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "train_net.py", line 94, in train
    arguments,
  File "/root/anaconda3/envs/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 72, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/root/anaconda3/envs/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 69, in __getitem__
    img, anno = super(COCODataset, self).__getitem__(idx)
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torchvision/datasets/coco.py", line 116, in __getitem__
    img = Image.open(os.path.join(self.root, path)).convert('RGB')
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/PIL/Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/val2014/COCO_val2014_000000172616.jpg'
****
I have symlink the coco dataset, the dataset can be seen in the datasets/coco, I don't know how to solve this problem, please help me, thank you!!

**Comment by pronaykp** [comment]
Bro, How can you solved this issues? I have the same problem. Please help me if you sort out the problem. Please!

**Comment by xuemeikim** [comment]
> Bro, How can you solved this issues? I have the same problem. Please help me if you sort out the problem. Please!

sorry, I forget how I solve this problem. I did not train my own model that time, and used its demo.
