### ISSUE TITLE
python setup.py build develop

### ISSUE THREAD

**Issue by zixuan19971114** [facebookresearch/maskrcnn-benchmark#1298]
## ❓ Questions and Help
running build
running build_py
running build_ext
building 'maskrcnn_benchmark._C' extension
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/xzx/.conda/envs/try/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/xzx/.conda/envs/try/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/xzx/.conda/envs/try/lib/python3.6/site-packages/Cython-3.0a6-py3.6-linux-x86_64.egg/Cython/Distutils/old_build_ext.py", line 187, in run
    _build_ext.build_ext.run(self)
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/xzx/.conda/envs/try/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/xzx/.conda/envs/try/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/xzx/.conda/envs/try/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/xzx/.conda/envs/try/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 486, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/xzx/.conda/envs/try/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 395, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags) +
  File "/home/xzx/.conda/envs/try/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1438, in _get_cuda_arch_flags
    raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (compute) or GPU not supported

Can anyone help me?

**Comment by bohuisir** [comment]
请问解决了吗
