### ISSUE TITLE
ImportError: /home/yangyang/anaconda3/envs/pytorch_4/lib/python3.6/site-packages/syncbn_gpu-0.0.0-py3.6-linux-x86_64.egg/syncbn_gpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by buzhidaoshenme** [facebookresearch/maskrcnn-benchmark#1309]
## ❓ Questions and Help
Traceback (most recent call last):
  File "tools/train_net.py", line 24, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/data/lost+found/gxw/DetNAS-pytorch4/maskrcnn_benchmark/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/data/lost+found/gxw/DetNAS-pytorch4/maskrcnn_benchmark/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/data/lost+found/gxw/DetNAS-pytorch4/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/data/lost+found/gxw/DetNAS-pytorch4/maskrcnn_benchmark/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/data/lost+found/gxw/DetNAS-pytorch4/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/data/lost+found/gxw/DetNAS-pytorch4/maskrcnn_benchmark/modeling/make_layers.py", line 12, in <module>
    from maskrcnn_benchmark.pytorch_distributed_syncbn.syncbn import DistributedSyncBN
  File "/data/lost+found/gxw/DetNAS-pytorch4/maskrcnn_benchmark/pytorch_distributed_syncbn/syncbn.py", line 12, in <module>
    import syncbn_gpu
ImportError: /home/yangyang/anaconda3/envs/pytorch_4/lib/python3.6/site-packages/syncbn_gpu-0.0.0-py3.6-linux-x86_64.egg/syncbn_gpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by tutu-star** [comment]
Have you solve this issue?
