### ISSUE TITLE
ModuleNotFoundError: No module named 'yacs'

### ISSUE THREAD

**Issue by Leo0408** [facebookresearch/maskrcnn-benchmark#1318]
## ❓ Questions and Help
I have installed yacs successfully :
"Installing collected packages: yacs
Successfully installed yacs-0.1.8"

But there are always "modulenotfound" errors:
"Traceback (most recent call last):
  File "webcam.py", line 5, in <module>
    from maskrcnn_benchmark.config import cfg
  File "/home/qian/jiang/TinyBenchmark/tiny_benchmark/maskrcnn_benchmark/config/__init__.py", line 2, in <module>
    from .defaults import _C as cfg
  File "/home/qian/jiang/TinyBenchmark/tiny_benchmark/maskrcnn_benchmark/config/defaults.py", line 4, in <module>
    from yacs.config import CfgNode as CN
ModuleNotFoundError: No module named 'yacs''

Even after i tried to uninstall and reinstall yacs, it still remained the same error.
Would it be the edition of the yacs?

**Comment by Souryadipstan** [comment]
Try installing with conda. Worked for me.

`conda install yacs`
