### ISSUE TITLE
FPN error in train on own dataset

### ISSUE THREAD

**Issue by QiaoranC** [facebookresearch/maskrcnn-benchmark#142]
## ❓ Questions and Help
Hi:
I am trying to compare this project with Detectron on my own dataset. I am interested in whether it can be faster and less memory assumption during inference. 
The dataset is COCO style.
The config is e2e_mask_rcnn_X_101_32x8d_FPN_1x_caffe2.yaml.
The NGPUS =4.
Like Detectron, i softlink the dataset and change the ROI_BOX_HEAD.NUM_CLASSES = 2 (1 more from backround). Adjust the LR,MAX_ITER usual staff. 

run with
`python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file "/data/ubuntu/github/maskrcnn-benchmark/configs/2JiYe/e2e_mask_rcnn_X_101_32x8d_FPN_1x.yaml"
`

But, it give errors during  FPN forward process:

`2018-11-12 20:53:49,427 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 170, in <module>
    main()
  File "tools/train_net.py", line 163, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/data/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 65, in do_train
    loss_dict = model(images, targets)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/parallel/deprecated/distributed.py", line 222, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 49, in forward
    features = self.backbone(images.tensors)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/fpn.py", line 62, in forward
    last_inner = inner_lateral + inner_top_down
RuntimeError: The size of tensor a (51) must match the size of tensor b (52) at non-singleton dimension 2
Traceback (most recent call last):
  File "tools/train_net.py", line 170, in <module>
    main()
  File "tools/train_net.py", line 163, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/data/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 65, in do_train
    loss_dict = model(images, targets)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/parallel/deprecated/distributed.py", line 222, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 49, in forward
    features = self.backbone(images.tensors)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/data/ubuntu/anaconda2/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/fpn.py", line 62, in forward
    last_inner = inner_lateral + inner_top_down
RuntimeError: The size of tensor a (51) must match the size of tensor b (52) at non-singleton dimension 2`

Any ideals? I am not sure where the problem is, cause the dataset should be fine, and the num of class is correct. I don't know why there is a problem during the FPN forward calculation. 
May be i miss something here.
Any suggestions are welcome.

**Comment by fmassa** [comment]
Hi,

You need to specify a [`SIZE_DIVISIBILITY` in the config for FPN](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/config/defaults.py#L72), see for example how [it's done for FPN here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/e2e_faster_rcnn_R_101_FPN_1x.yaml#L26).
Indeed, FPN requires the input size to have a particular size (because it upsamples the intermediate feature maps by a fixed size).

I'm closing this issue because the solution should be simple, but let us know if you have further questions
