### ISSUE TITLE
cat_boxlist doesn't work correctly

### ISSUE THREAD

**Issue by krumo** [facebookresearch/maskrcnn-benchmark#151]
## ❓ Questions and Help
I am trying to concatenate 2 data samples generated from 2 dataloaders in [do_train](https://github.com/facebookresearch/maskrcnn-benchmark/blob/1276d20b249d03ffe1cb6162e4c863b6ee715413/maskrcnn_benchmark/engine/trainer.py#L38) function. Thus, I modify `targets = [target.to(device) for target in targets]` to `targets = [target.to(device) for target in cat_boxlist(list(targets1+targets2))]`. 

However, I encountered following error for this sentence:

> Traceback (most recent call last):
  File "tools/train_net.py", line 200, in <module>
    main()
  File "tools/train_net.py", line 193, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 101, in train
    arguments,
  File "/krumo/detection/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 144, in do_da_train
    targets = [target.to(device) for target in cat_boxlist(list(targets1+targets2))]
  File "/krumo/detection/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 127, in cat_boxlist
    data = _cat([bbox.get_field(field) for bbox in bboxes], dim=0)
  File "/krumo/detection/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 100, in _cat
    return torch.cat(tensors, dim)
TypeError: expected Tensor as element 0 in argument 0, but got list

According to my survey, the problem occurs because the class SegmentationMask cannot be recognized as a tensor in PyTorch. Thus, I wonder when do you call cat_boxlist to concat boxlists and do you have any suggestions for concating a list of SegmentationMask. Thanks in advance!

**Comment by fmassa** [comment]
Hi,

This is a great point.

Indeed, we can't for not concatenate boxes with `SegmentationMask` inside because of exactly the reason you mentioned.
I'd love to fix this, but I didn't yet have the time to do it.


Here is a workaround:
- you create a copy of the fields without the `SegmentationMask`, this can be done with something like
```python
fields = [f for f in boxlist.fields() if f != 'mask']
boxlist_new = boxlist.copy_with_fields(fields)
# concatenate boxlist_new
# concatenate segmentation mask. Might require doing it manually for now
# append segmentation_mask_new to boxlist_new
```

Also, a word of warning: `cat_boxlist` only work if the images have the same size. So if you are trying to cat boxlist coming from images of different sizes, it will fail.

**Comment by krumo** [comment]
Hi, thanks for your suggestion. I finally choose to just read targets from different sources as a list and process them separately in the further generic rcnn model. It seems that transforming segmentation mask to tensor when reading data requires to change the pipeline. A warning at the comments for SegmentationMask class should be reasonable. Thanks for your help!
