### ISSUE TITLE
Wrong index access in RPNPostProcessor.select_over_all_levels()

### ISSUE THREAD

**Issue by miguelvr** [facebookresearch/maskrcnn-benchmark#175]
## 🐛 Bug

Wrong index access in `RPNPostProcessor.select_over_all_levels()`

Any idea of what might be causing this?

```
Traceback (most recent call last):
  File "tools/train_net.py", line 170, in <module>
    main()
  File "tools/train_net.py", line 163, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 66, in do_train
    loss_dict = model(images, targets)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 100, in forward
    return self._forward_train(anchors, objectness, rpn_box_regression, targets)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 116, in _forward_train
    anchors, objectness, rpn_box_regression, targets
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 144, in forward
    boxlists = self.select_over_all_levels(boxlists)
  File "/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 167, in select_over_all_levels
    inds_mask[inds_sorted] = 1
RuntimeError: index 926508 is out of bounds for dimension 0 with size 5
```

## Environment

Docker image
```
PyTorch version: 1.0.0.dev20181119
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-16GB
GPU 1: Tesla V100-DGXS-16GB
GPU 2: Tesla V100-DGXS-16GB
GPU 3: Tesla V100-DGXS-16GB

Nvidia driver version: 384.145
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
```

**Comment by fmassa** [comment]
I think your model didn't train properly, and it is returning inf / nan during forward, which is breaking parts of the code.

Can you double check that this is indeed the issue?

**Comment by miguelvr** [comment]
it is indeed the backbone part of the model that is returning `-infs`

I have no idea why, nevertheless

**Comment by fmassa** [comment]
You probably had a too high learning rate during training. Check https://github.com/facebookresearch/maskrcnn-benchmark/issues/33 for example, it should help you figure out where the issue was.

Let me know if you have further questions.

**Comment by miguelvr** [comment]
it turns out the issue was in the INPUT.MIN_SIZE parameter, because it was too high and my dataset has smaller images than that.

Maybe it is a good idea to raise a warning on this @fmassa ?

**Comment by miguelvr** [comment]
i'm running it on my tensorboard branch, but I'm not currently using the option, so it shouldn't have any effect.

what happens if the images are smaller than the rescaled min size?

**Comment by fmassa** [comment]
They get resized while keeping the aspect ratio

**Comment by miguelvr** [comment]
weird... because it is literally the only thing I changed. The one possible explanation is that the pre-trained model doesn't handle well the rescaled greyscale images, resulting in a faulty inference (with inf values)
