### ISSUE TITLE
This code is only support install it once in one computer?

### ISSUE THREAD

**Issue by dandelionlzx** [facebookresearch/maskrcnn-benchmark#227]
## 🐛 Bug
This code is only support install it once in one computer?
I create a virtual env in my computer and install a maskrcnn-benchmark, it runs no problem.
But when i create another virtual env, it shows error.

1.I use this command :CUDA_VISIBLE_DEVICES=2 python tools/train_net.py --config-file "./configs/fpn_baseline.yaml"
2.Then it happens this error:
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/raid/lzx/detection/maskrcnn2/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 70, in do_train
    loss_dict = model(images, targets)
  File "/home/lzx/.virtualenvs/detection2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/raid/lzx/detection/maskrcnn2/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/lzx/.virtualenvs/detection2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/raid/lzx/detection/maskrcnn2/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 100, in forward
    return self._forward_train(anchors, objectness, rpn_box_regression, targets)
  File "/raid/lzx/detection/maskrcnn2/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 116, in _forward_train
    anchors, objectness, rpn_box_regression, targets
  File "/home/lzx/.virtualenvs/detection2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/raid/lzx/detection/maskrcnn2/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 138, in forward
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "/raid/lzx/detection/maskrcnn2/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 113, in forward_for_single_feature_map
    boxlist = remove_small_boxes(boxlist, self.min_size)
  File "/raid/lzx/detection/maskrcnn2/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 46, in remove_small_boxes
    (ws >= min_size) & (hs >= min_size)
RuntimeError: an illegal memory access was encountered

## Environment
Collecting environment information...
PyTorch version: 1.0.0.dev20181128
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 381.09
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/local/MATLAB/R2017a/bin/glnxa64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-8.0/lib64/libcudnn.so.old
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/cuda-8.0/lib64/libcudnn_static.a.old
/usr/local/lib/libcudnn.so
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudnn-a2b758a6.so.7.0.3
/usr/local/lib/python3.6/site-packages/torch/lib/libcudnn-900fef33.so.7.0.5

**Comment by fmassa** [comment]
This is a problem with PyTorch that was fixed yesterday.
Try updating PyTorch today or tomorrow and the problem will disappear.
