### ISSUE TITLE
get error when run web_cam.py

### ISSUE THREAD

**Issue by jario-jin** [facebookresearch/maskrcnn-benchmark#239]
## ❓ Questions and Help
python webcam.py --min-image-size 300
Traceback (most recent call last):
  File "webcam.py", line 80, in <module>
    main()
  File "webcam.py", line 71, in main
    composite = coco_demo.run_on_opencv_image(img)
  File "/home/jario/spire-net-1810/maskrcnn-benchmark/demo/predictor.py", line 169, in run_on_opencv_image
    predictions = self.compute_prediction(image)
  File "/home/jario/spire-net-1810/maskrcnn-benchmark/demo/predictor.py", line 215, in compute_prediction
    masks = self.masker([masks], [prediction])[0]
  File "/home/jario/spire-net-1810/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py", line 192, in __call__
    result = self.forward_single_image(mask, box)
  File "/home/jario/spire-net-1810/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py", line 172, in forward_single_image
    for mask, box in zip(masks, boxes.bbox)
  File "/home/jario/spire-net-1810/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py", line 135, in paste_mask_in_image
    mask = F.interpolate(mask, size=(h, w), mode='bilinear', align_corners=False)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 2065, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, _output_size(2), align_corners)
TypeError: an integer is required

**Comment by fmassa** [comment]
What is your pytorch version?

**Comment by jario-jin** [comment]
PyTorch version: 1.0.0a0+1f94ce1
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
CMake version: version 3.10.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 396.24.02
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/lib64/libcudnn.so
/usr/local/cuda-9.2/lib64/libcudnn.so.7
/usr/local/cuda-9.2/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (1.0.0a0+1f94ce1)
[pip] torchvision (0.2.1)
[conda] Could not collect
        Pillow (5.1.0)


When I changed:
mask = F.interpolate(mask, size=(int(h), int(w)), mode='bilinear', align_corners=False)
Problem solved.

**Comment by fmassa** [comment]
Can you send a PR changing [this line](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py#L125-L126) so that it is instead
```python
w = int(box[2] - box[0] + TO_REMOVE)
h = int(box[3] - box[1] + TO_REMOVE)
```

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/245#pullrequestreview-181178861
