### ISSUE TITLE
Problems with training with the newest version of pytorch-nightly

### ISSUE THREAD

**Issue by Jacobew** [facebookresearch/maskrcnn-benchmark#240]
## ❓ Questions and Help
Hello, I still have some problems after I changed the version of pytorch-nightly to the newest one.

The command I used:

> python tools/train_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1

The problems:

> Traceback (most recent call last):
  File "tools/train_net.py", line 18, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "/home/wuyangxin/github/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 10, in <module>
    from maskrcnn_benchmark.data.datasets.evaluation import evaluate
  File "/home/wuyangxin/github/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 3, in <module>
    from .coco import coco_evaluation
  File "/home/wuyangxin/github/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py", line 1, in <module>
    from .coco_eval import do_coco_evaluation
  File "/home/wuyangxin/github/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 10, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "/home/wuyangxin/github/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 6, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "/home/wuyangxin/github/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .nms import nms
  File "/home/wuyangxin/github/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /home/wuyangxin/github/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at23getDefaultTensorOptionsEv

I've carefully checked my environment settings below and I have no idea what's wrong.

> 

 

> PyTorch version: 1.0.0.dev20181201
> Is debug build: No
> CUDA used to build PyTorch: 8.0.61
> 
> OS: Ubuntu 16.04.3 LTS
> GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
> CMake version: version 3.5.1
> 
> Python version: 3.7
> Is CUDA available: Yes
> CUDA runtime version: 8.0.61
> GPU models and configuration: 
> GPU 0: GeForce GTX TITAN X
> GPU 1: GeForce GTX TITAN X
> GPU 2: GeForce GTX TITAN X
> GPU 3: GeForce GTX TITAN X
> GPU 4: GeForce GTX TITAN X
> GPU 5: GeForce GTX TITAN X
> GPU 6: GeForce GTX TITAN X
> GPU 7: GeForce GTX TITAN X
> 
> Nvidia driver version: 387.26
> cuDNN version: Probably one of the following:
> /usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
> /usr/local/cuda-8.0/lib64/libcudnn_static.a
> /usr/local/cuda-9.0/lib64/libcudnn.so
> /usr/local/cuda-9.0/lib64/libcudnn.so.7
> /usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
> /usr/local/cuda-9.0/lib64/libcudnn_static.a
> /usr/local/cuda-9.2/lib64/libcudnn.so.7.2.1
> /usr/local/cuda-9.2/lib64/libcudnn_static.a
> 
> Versions of relevant libraries:
> [pip] numpy (1.15.4)
> [pip] numpydoc (0.8.0)
> [pip] torch (1.0.0.dev20181201)
> [pip] torchvision (0.2.1)
> [conda] Could not collect
> 

Do you have any idea? 
Looking forward to your reply :-)

**Comment by Jacobew** [comment]
@fmassa Thanks, I've solved the problem after I removed the `build` folder and changed my CUDA version to 9.0.
