### ISSUE TITLE
Validation during training produces unsupported keys

### ISSUE THREAD

**Issue by Igal20** [facebookresearch/maskrcnn-benchmark#247]
## ❓ Questions and Help
During training once in 20 iterations I perform inference for my validation set.
is same manner as described in  **tools/test_net.py**. In my case I have only one class but during prediction of the validation set I get some other label than 1, usually happening to at first 100 iterations.
```
mapped_labels = [dataset.contiguous_category_id_to_json_id[i] for i in labels]
KeyError: 15
```
Problem is that error occurring randomly.
am I doing something wrong?
How can one overcome this issue?

**Comment by fmassa** [comment]
This looks like a bug in your dataset?

**Comment by Igal20** [comment]
`labels = prediction.get_field("labels").tolist()`
`mapped_labels = [dataset.contiguous_category_id_to_json_id[i] for i in labels]`

**Comment by fmassa** [comment]
How many outputs does your model have? Did you change the number of output classes to be 2 in your case?

**Comment by Igal20** [comment]
I did not, sorry for dummy question but how do I do that?

**Comment by fmassa** [comment]
You need to follow the instructions in https://github.com/facebookresearch/maskrcnn-benchmark/issues/15

**Comment by Igal20** [comment]
Thank you!

**Comment by fmassa** [comment]
I'm closing this issue, but let me know if you have other problems

**Comment by Ruolingdeng** [comment]
@fmassa Hello, I encountered the same issue, I have changed in defaults.py --> _C.MODEL.ROI_BOX_HEAD.NUM_CLASSES = 25, but when I started training, I still encountered this issue. My output class num is 25 including the background. My issues are:
` 2020-04-21 14:44:26,720 maskrcnn_benchmark.inference INFO: Model inference time: 0:00:00.999555 (0.08329623937606812 s / img per device, on 1 devices)
2020-04-21 14:44:26,725 maskrcnn_benchmark.inference INFO: Preparing results for COCO format
2020-04-21 14:44:26,725 maskrcnn_benchmark.inference INFO: Preparing bbox results
Traceback (most recent call last):
  File "tools/train_net.py", line 201, in <module>
    main()
  File "tools/train_net.py", line 197, in main
    run_test(cfg, model, args.distributed)
  File "tools/train_net.py", line 128, in run_test
    output_folder=output_folder,
  File "/home/drl/workspace/spikelet/4/graindetection2/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 120, in inference
    **extra_args)
  File "/home/drl/workspace/spikelet/4/graindetection2/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 22, in evaluate
    return coco_evaluation(**args)
  File "/home/drl/workspace/spikelet/4/graindetection2/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py", line 23, in coco_evaluation
    expected_results_sigma_tol=expected_results_sigma_tol,
  File "/home/drl/workspace/spikelet/4/graindetection2/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 44, in do_coco_evaluation
    coco_results["bbox"] = prepare_for_coco_detection(predictions, dataset)
  File "/home/drl/workspace/spikelet/4/graindetection2/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 88, in prepare_for_coco_detection
    mapped_labels = [dataset.contiguous_category_id_to_json_id[i] for i in labels]
  File "/home/drl/workspace/spikelet/4/graindetection2/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 88, in <listcomp>
    mapped_labels = [dataset.contiguous_category_id_to_json_id[i] for i in labels]
KeyError: 18.0`
Could you please help me.
