### ISSUE TITLE
Modifying trained model, change amount of freezing layers.

### ISSUE THREAD

**Issue by Igal20** [facebookresearch/maskrcnn-benchmark#263]
## ❓ Questions and Help
I trained a model on my own data set with FREEZE_CONV_BODY_AT =2, and saved specific model "**model_0007500.pth**" than I want to take this model and to train on other data set but now freeze more layers i.e. FREEZE_CONV_BODY_AT =4. but I got an error. 

> Traceback (most recent call last):
  File "/home/igaldm/healthy/Spot/python/Spot_deep_learning/maskrcnn_benchmark_scripts/training/train_mrcnn_net.py", line 192, in <module>
    main()
  File "/home/igaldm/healthy/Spot/python/Spot_deep_learning/maskrcnn_benchmark_scripts/training/train_mrcnn_net.py", line 185, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/igaldm/healthy/Spot/python/Spot_deep_learning/maskrcnn_benchmark_scripts/training/train_mrcnn_net.py", line 82, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/igaldm/healthy/3rd_parties/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 65, in load
    self.optimizer.load_state_dict(checkpoint.pop("optimizer"))
  File "/home/igaldm/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/optim/optimizer.py", line 109, in load_state_dict
    raise ValueError("loaded state dict has a different number of "
ValueError: loaded state dict has a different number of parameter groups

Because length of **saved_groups=84** and **groups=52**
How can I overcome this problem? My main goal is transfer learning with different amount freezing layers.

**Comment by fmassa** [comment]
I suppose one possibility is to just load the state dict and delete the `optimizer` and the `scheduler` fields from the checkpoint, and save it again in a new file?

**Comment by saltknox** [comment]
Excuse me, have you solved this problem?

**Comment by saltknox** [comment]
I have solved this problem

modify file:utils/checkpoint.py

`        if "optimizer" in checkpoint and self.optimizer:
            self.logger.info("Loading optimizer from {}".format(f))
            #self.optimizer.load_state_dict(checkpoint.pop("optimizer"))       #commented code
        if "scheduler" in checkpoint and self.scheduler:
            self.logger.info("Loading scheduler from {}".format(f))
            #self.scheduler.load_state_dict(checkpoint.pop("scheduler"))      #commented code`  

we should not use the "scheduler" and "optimizer" parameters saved last time

**Comment by andics** [comment]
Keep in mind that if you train for more than 7500 iterations and reinitialize the Optimizer (which is what's happening here), you'll experience a significant drop in performance that will take a while to stabilize.
