### ISSUE TITLE
I have 'datasets/coco/annotations/instances_train2014.json', but exist this error:

### ISSUE THREAD

**Issue by CachCheng** [facebookresearch/maskrcnn-benchmark#345]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/chenghong/PycharmProjects/ObjectDetection/tools/train_net.py", line 171, in <module>
    main()
  File "/Users/chenghong/PycharmProjects/ObjectDetection/tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/Users/chenghong/PycharmProjects/ObjectDetection/tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/Users/chenghong/PycharmProjects/ObjectDetection/maskrcnn_benchmark/data/build.py", line 154, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
  File "/Users/chenghong/PycharmProjects/ObjectDetection/maskrcnn_benchmark/data/build.py", line 44, in build_dataset
    dataset = factory(**args)
  File "/Users/chenghong/PycharmProjects/ObjectDetection/maskrcnn_benchmark/data/datasets/coco.py", line 13, in __init__
    super(COCODataset, self).__init__(root, ann_file)
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/torchvision/datasets/coco.py", line 97, in __init__
    self.coco = COCO(annFile)
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/pycocotools-2.0-py3.7-macosx-10.7-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_train2014.json'

**Comment by z785042003** [comment]
Traceback (most recent call last):
  File "train_net.py", line 174, in <module>
    main()
  File "train_net.py", line 167, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/opex/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 154, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
  File "/home/opex/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 44, in build_dataset
    dataset = factory(**args)
  File "/home/opex/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 43, in __init__
    super(COCODataset, self).__init__(root, ann_file)
  File "/home/opex/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/datasets/coco.py", line 97, in __init__
  File "/home/opex/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_train2014.json'

I build the datasets folder in maskrcnn-benchmark, but i got this error, help!

**Comment by z785042003** [comment]
> Traceback (most recent call last):
> File "train_net.py", line 174, in 
> main()
> File "train_net.py", line 167, in main
> model = train(cfg, args.local_rank, args.distributed)
> File "train_net.py", line 60, in train
> start_iter=arguments["iteration"],
> File "/home/opex/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 154, in make_data_loader
> datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
> File "/home/opex/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 44, in build_dataset
> dataset = factory(**args)
> File "/home/opex/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 43, in **init**
> super(COCODataset, self).**init**(root, ann_file)
> File "/home/opex/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/datasets/coco.py", line 97, in **init**
> File "/home/opex/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 84, in **init**
> dataset = json.load(open(annotation_file, 'r'))
> FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_train2014.json'
> 
> I build the datasets folder in maskrcnn-benchmark, but i got this error, help!

I put .json in here, like"~/maskrcnn-benchmarch/datasets/coco/annotations/instances_train2014.json"

**Comment by hz-fengpeng** [comment]
I meet the same problem when I use pycharm to run the test_net.py. when I in a console in the first maskrcnn-benchmark fold, use commod:  python tools/test_net.py .Then it works. I think when I run test_net.py in pycharm. the datasets folder can't been seen.

**Comment by BisratM** [comment]
Has anyone managed to resolve this? I am attempting to use COCO's 2017 dataset and receiving the same error. The issue seems to be with the COCO api but I've been unable to fix it.

**Comment by BisratM** [comment]
The issue seems to be that pycocotools is attempting to fetch the annotations from within the site packages folder rather than in the data folder(perhaps switching to an older version of the COCO API would help). I found a temporary fix by adjusting the DATA_DIR accordingly in path_catalog.py inside maskrcnn_benchmark/config.

**Comment by yiColddrink** [comment]
this problem is fixed by cd into tools dir, and then use : python train_net.py ...

**Comment by rwwneu** [comment]
Traceback (most recent call last):
  File "tools/train_net.py", line 205, in <module>
    main()
  File "tools/train_net.py", line 198, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 76, in train
    start_iter=arguments["iteration"],
  File "/home/james/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 156, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train or is_for_period)
  File "/home/james/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 45, in build_dataset
    dataset = factory(**args)
  File "/home/james/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 43, in __init__
    super(COCODataset, self).__init__(root, ann_file)
  File "/home/james/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/torchvision/datasets/coco.py", line 97, in __init__
    self.coco = COCO(annFile)
  File "/home/james/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: "/home/james/V_hardness_kp/maskrcnn-benchmark/datasets/coco/annotations/train2020.json'"

I build the datasets folder in maskrcnn-benchmark, but i got this error, who can help me?

**Comment by rwwneu** [comment]
> Traceback (most recent call last):
> File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in
> main()
> File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
> globals = debugger.run(setup['file'], None, None, is_module)
> File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "/Users/chenghong/PycharmProjects/ObjectDetection/tools/train_net.py", line 171, in
> main()
> File "/Users/chenghong/PycharmProjects/ObjectDetection/tools/train_net.py", line 164, in main
> model = train(cfg, args.local_rank, args.distributed)
> File "/Users/chenghong/PycharmProjects/ObjectDetection/tools/train_net.py", line 60, in train
> start_iter=arguments["iteration"],
> File "/Users/chenghong/PycharmProjects/ObjectDetection/maskrcnn_benchmark/data/build.py", line 154, in make_data_loader
> datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
> File "/Users/chenghong/PycharmProjects/ObjectDetection/maskrcnn_benchmark/data/build.py", line 44, in build_dataset
> dataset = factory(**args)
> File "/Users/chenghong/PycharmProjects/ObjectDetection/maskrcnn_benchmark/data/datasets/coco.py", line 13, in **init**
> super(COCODataset, self).**init**(root, ann_file)
> File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/torchvision/datasets/coco.py", line 97, in **init**
> self.coco = COCO(annFile)
> File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/pycocotools-2.0-py3.7-macosx-10.7-x86_64.egg/pycocotools/coco.py", line 84, in **init**
> dataset = json.load(open(annotation_file, 'r'))
> FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/annotations/instances_train2014.json'

Have you solved it? Can you tell me how to solve it？

**Comment by rwwneu** [comment]
Have you solved it? Can you tell me how to solve it？

**Comment by hxy39** [comment]
In config/paths_catalog.py , set the variable DATA_DIR  changed from 'datasets' to '../datasets'
