### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by zzp321** [facebookresearch/maskrcnn-benchmark#366]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from the
[environment collection script from PyTorch](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

2019-01-22 02:49:52,814 maskrcnn_benchmark INFO: Using 1 GPUs
2019-01-22 02:49:52,823 maskrcnn_benchmark INFO: Namespace(config_file='configs/e2e_mask_rcnn_R_50_FPN_1x.yaml', distributed=False, local_rank=0, opts=['SOLVER.IMS_PER_BATCH', '2', 'SOLVER.BA
SE_LR', '0.0025', 'SOLVER.MAX_ITER', '720000', 'SOLVER.STEPS', '(480000, 640000)', 'TEST.IMS_PER_BATCH', '1'], skip_test=False)2019-01-22 02:49:52,823 maskrcnn_benchmark INFO: Collecting env info (might take some time)
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 156, in main
    logger.info("\n" + collect_env_info())
  File "/maskrcnn-benchmark/maskrcnn_benchmark/utils/collect_env.py", line 12, in collect_env_info
    env_str = get_pretty_env_info()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/collect_env.py", line 351, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/collect_env.py", line 244, in get_env_info
    nvidia_driver_version=get_nvidia_driver_version(run_lambda),
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/collect_env.py", line 94, in get_nvidia_driver_version
    return run_and_parse_first_match(run_lambda, smi, r'Driver Version: (.*?) ')
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/collect_env.py", line 62, in run_and_parse_first_match
    rc, out, _ = run_lambda(command)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/collect_env.py", line 43, in run
    stderr=subprocess.PIPE, shell=True)
  File "/miniconda/envs/py36/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/miniconda/envs/py36/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 28] No space left on device

**Comment by fmassa** [comment]
You were running out of disk space.
A fix is to remove some unnecessary data and try again.
