### ISSUE TITLE
Can't run demo, model filename is too long

### ISSUE THREAD

**Issue by Rizhiy** [facebookresearch/maskrcnn-benchmark#370]
## 🐛 Bug

When I run `webcam.py` the script tries to download weights for the model, but the filaname for cached files is too long.
Max filename is usually 255 characters.

## To Reproduce

1. Install repo
1. Run `python webcam.py`

Error:
```
Downloading: "https://dl.fbaipublicfiles.com/detectron/35858933/12_2017_baselines/e2e_mask_rcnn_R-50-FPN_1x.yaml.01_48_14.DzEQe4wC/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl" to /home/rizhiy/.torch/models/_detectron_35858933_12_2017_baselines_e2e_mask_rcnn_R-50-FPN_1x.yaml.01_48_14.DzEQe4wC_output_train_coco_2014_train%3Acoco_2014_valminusminival_generalized_rcnn_model_final.pkl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 362433370/362433370 [00:32<00:00, 11090137.90it/s]
Traceback (most recent call last):
  File "/home/rizhiy/anaconda3/envs/liveness/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp5d8g6paz' -> '/home/rizhiy/.torch/models/_detectron_35858933_12_2017_baselines_e2e_mask_rcnn_R-50-FPN_1x.yaml.01_48_14.DzEQe4wC_output_train_coco_2014_train%3Acoco_2014_valminusminival_generalized_rcnn_model_final.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "webcam.py", line 80, in <module>
    main()
  File "webcam.py", line 64, in main
    min_image_size=args.min_image_size,
  File "/home/rizhiy/liveness/maskrcnn-benchmark/demo/predictor.py", line 117, in __init__
    _ = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/rizhiy/liveness/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "/home/rizhiy/liveness/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 129, in _load_file
    cached_f = cache_url(f)
  File "/home/rizhiy/liveness/maskrcnn-benchmark/maskrcnn_benchmark/utils/model_zoo.py", line 54, in cache_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/rizhiy/anaconda3/envs/liveness/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 103, in _download_url_to_file
    shutil.move(f.name, dst)
  File "/home/rizhiy/anaconda3/envs/liveness/lib/python3.6/shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "/home/rizhiy/anaconda3/envs/liveness/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/rizhiy/anaconda3/envs/liveness/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 36] File name too long: '/home/rizhiy/.torch/models/_detectron_35858933_12_2017_baselines_e2e_mask_rcnn_R-50-FPN_1x.yaml.01_48_14.DzEQe4wC_output_train_coco_2014_train%3Acoco_2014_valminusminival_generalized_rcnn_model_final.pkl'
```

## Expected behavior

Check filename length and abbreviate if too long.

## Environment

 - PyTorch Version (e.g., 1.0):	 1.0.0
 - OS (e.g., Linux): Ubuntu 16.04

**Comment by fmassa** [comment]
weird, I haven't seen this problem before.
On your particular case, you can rename the weight and the config and this should work.
I'll have a look at why your python is throwing this error

**Comment by fmassa** [comment]
Also, what's your Python version?

**Comment by Rizhiy** [comment]
3.6.7, but I don't think it matters. This is an OS level limitation.

**Comment by fmassa** [comment]
I tried counting the filename and it seems to be smaller than 255 characters
```python
print(len('_detectron_35858933_12_2017_baselines_e2e_mask_rcnn_R-50-FPN_1x.yaml.01_48_14.DzEQe4wC_output_train_coco_2014_train%3Acoco_2014_valminusminival_generalized_rcnn_model_final.pkl'))
> 176
```

Still, it might be good thinking about a better way of handling this. Maybe having a map from strings to a simplified name, or hashing the string name somewhere?

**Comment by Rizhiy** [comment]
This seems to be related: https://stackoverflow.com/questions/34503540/why-does-python-give-oserror-errno-36-file-name-too-long-for-filename-short

**Comment by fmassa** [comment]
I see.

If you'd like to see if you could have a better fix for it, I'd recommend applying a different transformation function in https://github.com/facebookresearch/maskrcnn-benchmark/blob/9b53d15c12cca33764ff218f61e95bb52bc7d0f3/maskrcnn_benchmark/utils/model_zoo.py#L39-L42

It would be good to still keep some reasonably readable and informative name, but I'm not sure what's the best solution here.

**Comment by Rizhiy** [comment]
I don't think there is an easy solution to this if name has to be readable and informative.

One thing I noticed is that there is a lot of redundant information, e.g.:
* `_detectron_35858933_` at the start of the filename
* `_generalized_rcnn_model_final.pkl` at the end of the filename
* `.yaml.01_48_14.DzEQe4wC_output` in the middle

Which can be removed and help save a few characters.

Perhaps someone can look at the complete list of Caffe2 models and decide on a reasonable compromise.

**Comment by srrichter** [comment]
An easy workaround is to point the torch home directory to a suitable directory outside the encrypted home, i.e., `export TORCH_HOME=<some_folder>` before running the demo. Worked for me.

**Comment by apple1987** [comment]
I meet the same problem, I commented out this line : filename = parts.path.replace("/", "_")  and it works.
