### ISSUE TITLE
train error from example

### ISSUE THREAD

**Issue by lixingyi8947** [facebookresearch/maskrcnn-benchmark#394]
## ❓ Questions and Help
Hi, I got the following error when I ran 
python tools/train_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1

Downloading: "https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl" to /home/xingyi/.torch/models/R-50.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 53, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/xingyi/github/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "/home/xingyi/github/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 128, in _load_file
    cached_f = cache_url(f)
  File "/home/xingyi/github/maskrcnn-benchmark/maskrcnn_benchmark/utils/model_zoo.py", line 54, in cache_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/xingyi/miniconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/model_zoo.py", line 73, in _download_url_to_file
    file_size = int(u.headers["Content-Length"])
  File "/home/xingyi/miniconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'

I am confused. I can run test code.

**Comment by fmassa** [comment]
Hi,

You are using an old version of `maskrcnn-benchmark`, the links for the pre-trained models from detectron have changed, see https://github.com/facebookresearch/maskrcnn-benchmark/pull/301

You should update the model URLs, and then everything should work fine.

Let me know if that doesn't solve the problem for you.
