### ISSUE TITLE
How to train on my own coco_like dataset 

### ISSUE THREAD

**Issue by Idolized22** [facebookresearch/maskrcnn-benchmark#434]
## ❓ Questions and Help

I tried to train the model on my own dataset but it failed with the following error: 

**> `loading annotations into memory...
Done (t=0.00s)**
creating index...

Traceback (most recent call last):

  File "<ipython-input-11-a168e36ec3f7>", line 1, in <module>
    runfile('/media/portablelinux/OS/Users/afeka/Pictures/maskrcnn-benchmark/tools/train_net.py', wdir='/media/portablelinux/OS/Users/afeka/Pictures/maskrcnn-benchmark/tools')

  File "/home/portablelinux/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "/home/portablelinux/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/media/portablelinux/OS/Users/afeka/Pictures/maskrcnn-benchmark/tools/train_net.py", line 174, in <module>
    main()

  File "/media/portablelinux/OS/Users/afeka/Pictures/maskrcnn-benchmark/tools/train_net.py", line 167, in main
    model = train(cfg, args.local_rank, args.distributed)

  File "/media/portablelinux/OS/Users/afeka/Pictures/maskrcnn-benchmark/tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],

  File "/media/portablelinux/OS/Users/afeka/Pictures/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 160, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)

  File "/media/portablelinux/OS/Users/afeka/Pictures/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 49, in build_dataset
    dataset = factory(**args)

  File "/media/portablelinux/OS/Users/afeka/Pictures/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 43, in __init__
    super(COCODataset, self).__init__(root, ann_file)

  File "/home/portablelinux/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/datasets/coco.py", line 97, in __init__
    self.coco = COCO(annFile)

  File "/home/portablelinux/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 88, in __init__
    self.createIndex()

  File "/home/portablelinux/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 98, in createIndex
    anns[ann['id']] = ann

**KeyError: 'id'`**

does anyone have an Idea of what causes the problem ? 

attached a sample of the json of the train  set  : 
created using labelme : 
https://github.com/wkentaro/labelme 
  
[annotations_train.zip](https://github.com/facebookresearch/maskrcnn-benchmark/files/2865029/annotations_train.zip)

**Comment by fmassa** [comment]
It looks like LabelMe does not prepare the json in the exact format the COCO API is expecting it, as the error is raised inside `pycocotools`.

I'd recommend manually correcting the fields which have the wrong names. Check http://cocodataset.org/#format-data for the official names.

**Comment by Idolized22** [comment]
> It looks like LabelMe does not prepare the json in the exact format the COCO API is expecting it, as the error is raised inside `pycocotools`.
> 
> I'd recommend manually correcting the fields which have the wrong names. Check http://cocodataset.org/#format-data for the official names.

Thank You very much for your help. 

I have made a very small subset to test if the labelme is suitable for the task. 

can you recommend of other labeling tool that wouldn't require me to make changes in  files inside pycocotools.?

**Comment by fmassa** [comment]
Hi,

I don't actually know which tool to use unfortunately. But I'd expect the changes to the `yaml` file to be minimal.

Maybe @maxsenh could tell what changes he needed to make it work in his case https://github.com/facebookresearch/maskrcnn-benchmark/issues/408#issuecomment-463131520 ?

**Comment by Idolized22** [comment]
> Hi,
> 
> I don't actually know which tool to use unfortunately. But I'd expect the changes to the `yaml` file to be minimal.
> 
> Maybe @maxsenh could tell what changes he needed to make it work in his case [#408 (comment)](https://github.com/facebookresearch/maskrcnn-benchmark/issues/408#issuecomment-463131520) ?

Thank You Very Much , 
It's a good idea, 
I'll ask him if the problem doesn't get solved soon as I might have figured it. 

In MY case if I am not mistaken the problem is with the script I have used to create the annotation file, 
as it decode the polygon dots  : 


![screenshot from 2019-02-14 22-38-57](https://user-images.githubusercontent.com/41726905/52816288-9e014380-30a9-11e9-815b-aa41e10324fe.png)
I am now working on solving  that. 


But a little future problem after running a train once on the coco dataset, 
I can't figure how run another train nor using a different config file (created by changing the dataset from coco2017 to a toy shapes data-set ) it runs evaluation again and again regardless of that the config files has different names and that it's mounted with a different data set. 
```

**Comment by fmassa** [comment]
> can't figure how run another train nor using a different config file (created by changing the dataset from coco2017 to a toy shapes data-set ) it runs evaluation again and again regardless of that the config files has different names and that it's mounted with a different data set.

Maybe you have a checkpoint in the same folder, and this checkpoint is being picked up? I'd recommend changing the `OUTPUT_DIR` folder to be different
