### ISSUE TITLE
there are problems when i use the methond writen in INSTALL.MD , i try every ways to install torchvision,but always be wrong

### ISSUE THREAD

**Issue by liu-ziming** [facebookresearch/maskrcnn-benchmark#47]
## ❓ Questions and Help
>>> import torch
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ziming/github/vision/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/ziming/github/vision/torchvision/models/__init__.py", line 1, in <module>
    from .alexnet import *
  File "/home/ziming/github/vision/torchvision/models/alexnet.py", line 2, in <module>
    import torch.utils.model_zoo as model_zoo
ModuleNotFoundError: No module named 'torch.utils.model_zoo'

**Comment by fmassa** [comment]
Hi,

Did you use conda to install the libraries? Can you try creating a new environment?

Also, what were the commands that you used to install?
