### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by Miracle1991** [facebookresearch/maskrcnn-benchmark#508]
## ❓ Questions and Help
when I run :python webcam.py --min-image-size 800
and i got these:

Traceback (most recent call last):
  File "webcam.py", line 81, in <module>
    main()
  File "webcam.py", line 65, in main
    min_image_size=args.min_image_size,
  File "/home/wangdongwei/mask_env/maskrcnn-benchmark/demo/predictor.py", line 113, in __init__
    self.model.to(self.device)
  File "/home/wangdongwei/anaconda3/envs/py35_maskrcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 384, in to
    return self._apply(convert)
  File "/home/wangdongwei/anaconda3/envs/py35_maskrcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 190, in _apply
    module._apply(fn)
  File "/home/wangdongwei/anaconda3/envs/py35_maskrcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 190, in _apply
    module._apply(fn)
  File "/home/wangdongwei/anaconda3/envs/py35_maskrcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 190, in _apply
    module._apply(fn)
  File "/home/wangdongwei/anaconda3/envs/py35_maskrcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 196, in _apply
    param.data = fn(param.data)
  File "/home/wangdongwei/anaconda3/envs/py35_maskrcnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 382, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: unknown error

I don't know what is wrong.
my env: 
gtx1070
nvidia driver  390.87
CUDA Version 9.0.176
cudnn 7.4.2

backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py36_0  
cffi                      1.12.1           py36h2e261b9_0  
cudatoolkit               9.0                  h13b8566_0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.6                   pypi_0    pypi
decorator                 4.3.2                    py36_0  
intel-openmp              2019.1                      144  
ipython                   7.3.0            py36h39e3cac_0  
ipython_genutils          0.2.0                    py36_0  
jedi                      0.13.3                   py36_0  
kiwisolver                1.0.1                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
maskrcnn-benchmark        0.1                       dev_0    <develop>
matplotlib                3.0.2                    pypi_0    pypi
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
ncurses                   6.1                  he6710b0_1  
ninja                     1.9.0                    pypi_0    pypi
numpy                     1.16.2                   pypi_0    pypi
numpy-base                1.15.4           py36hde5b4d6_0  
opencv-python             4.0.0.21                 pypi_0    pypi
openssl                   1.0.2r               h7b6447c_0  
parso                     0.3.4                    py36_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pillow                    5.4.1                    pypi_0    pypi
pip                       19.0.3                   py36_0  
prompt_toolkit            2.0.9                    py36_0  
ptyprocess                0.6.0                    py36_0  
pycocotools               2.0                      pypi_0    pypi
pycparser                 2.19                     py36_0  
pygments                  2.3.1                    py36_0  
pyparsing                 2.3.1                    pypi_0    pypi
python                    3.6.4                hc3d631a_3  
python-dateutil           2.8.0                    pypi_0    pypi
pytorch-nightly           1.0.0.dev20190228 py3.6_cuda9.0.176_cudnn7.4.2_0    pytorch
pyyaml                    3.13                     pypi_0    pypi
readline                  7.0                  h7b6447c_5  
setuptools                40.8.0                   py36_0  
six                       1.12.0                   py36_0  
sqlite                    3.26.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tqdm                      4.31.1                   pypi_0    pypi
traitlets                 4.3.2                    py36_0  
wcwidth                   0.1.7                    py36_0  
wheel                     0.33.1                   py36_0  
xz                        5.2.4                h14c3975_4  
yacs                      0.1.5                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3

**Comment by fmassa** [comment]
Can you do
```python
import torch
torch.rand(1).cuda()
```
in your machine?
If yes, then I'd say that you might have compiled `maskrcnn-benchmark` using a different CUDA than the one from PyTorch, can you double-check?

**Comment by Miracle1991** [comment]
> Can you do
> 
> ```python
> import torch
> torch.rand(1).cuda()
> ```
> 
> in your machine?
> If yes, then I'd say that you might have compiled `maskrcnn-benchmark` using a different CUDA than the one from PyTorch, can you double-check?

that works，thank you

**Comment by fmassa** [comment]
So you have fixed your problem? If yes, can you close this issue?

**Comment by Miracle1991** [comment]
> So you have fixed your problem? If yes, can you close this issue?
no yet. 
i run the demo you write,
and I got:  tensor([1],device="cuda:0")
how can i compiled maskrcnn-benchmark using the CUDA from Pytorch?

**Comment by Miracle1991** [comment]
> So you have fixed your problem? If yes, can you close this issue?
this is a part of log when I compile the maskrcnn_benchmark:

/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/wangdongwei/maskrcnn-benchmark/maskrcnn_benchmark/csrc -I/home/wangdongwei/anaconda3/lib/python3.7/site-packages/torch/lib/include -I/home/wangdongwei/anaconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/wangdongwei/anaconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/wangdongwei/anaconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/wangdongwei/anaconda3/include/python3.7m -c /home/wangdongwei/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.cu -o build/temp.linux-x86_64-3.7/home/wangdongwei/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cuda/ROIPool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11

**Comment by fmassa** [comment]
Did you compile `maskrcnn-benchmark` using the same CUDA version as the one that you have used for PyTorch?

**Comment by LeviViana** [comment]
Any update on this issue ?

**Comment by pantelismyr** [comment]
> Can you do
> 
> ```python
> import torch
> torch.rand(1).cuda()
> ```
> 
> in your machine?
> If yes, then I'd say that you might have compiled `maskrcnn-benchmark` using a different CUDA than the one from PyTorch, can you double-check?

When I am trying to run torch.rand(1).cuda(), I am getting no response from the device. Do you know how to interpret this?

**Comment by github14343** [comment]
I have met the same problem,have you solved it?

**Comment by fight-think** [comment]
When I run torch.rand(1).cuda(), I get the following error:
Traceback (most recent call last):
  File "vulnerable_MIA_with_MNIST.py", line 31, in <module>
    torch.rand(1).cuda()
RuntimeError: CUDA error: unknown error

**Comment by wx805541464** [comment]
> 

me too, did you slove it?
