### ISSUE TITLE
An Installation for win 10 install maskrcnn-benchmark 

### ISSUE THREAD

**Issue by xixixijie** [facebookresearch/maskrcnn-benchmark#529]
https://www.jianshu.com/p/e9680d0bfa5c

**Comment by xixixijie** [comment]
In Chinese,sorry.

**Comment by fmassa** [comment]
Nice, thanks for the instructions! (even though I don't read chinese, the images made it simpler to understand :-) )

**Comment by elevenjiang1** [comment]
这几天也想跑,但是被卡住了,在执行
python webcam.py --min-image-size 800  中,他报错:
Traceback (most recent call last):
  File "webcam.py", line 5, in <module>
    from maskrcnn_benchmark.config import cfg
ModuleNotFoundError: No module named 'maskrcnn_benchmark'
因此吧maskrcnn_benchmark文件添加的了demo文件中,接下来,重新执行python webcam.py --min-image-size 800时,继续报错:
Traceback (most recent call last):
  File "webcam.py", line 6, in <module>
    from predictor import COCODemo
  File "P:\test\maskrcnn-benchmark-master\demo\predictor.py", line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\detector\__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\detector\detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\detector\generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\backbone\__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\backbone\backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\make_layers.py", line 10, in <module>
    from maskrcnn_benchmark.layers import Conv2d
  File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\layers\__init__.py", line 9, in <module>
    from .nms import nms
  File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\layers\nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\__init__.py)

怎么办,想问问答主有联系方式吗,能帮帮忙吗,被搞得很痛苦

**Comment by ananandai** [comment]
我创建了一个maskrcnn-benchmark-master的快捷方式并将其放入Anaconda3\Lib\site-packages\下，就可以了。

**Comment by jianglin314** [comment]
> 这几天也想跑,但是被卡住了,在执行
> python webcam.py --min-image-size 800 中,他报错:
> Traceback (most recent call last):
> File "webcam.py", line 5, in 
> from maskrcnn_benchmark.config import cfg
> ModuleNotFoundError: No module named 'maskrcnn_benchmark'
> 因此吧maskrcnn_benchmark文件添加的了demo文件中,接下来,重新执行python webcam.py --min-image-size 800时,继续报错:
> Traceback (most recent call last):
> File "webcam.py", line 6, in 
> from predictor import COCODemo
> File "P:\test\maskrcnn-benchmark-master\demo\predictor.py", line 6, in 
> from maskrcnn_benchmark.modeling.detector import build_detection_model
> File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\detector__init__.py", line 2, in 
> from .detectors import build_detection_model
> File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\detector\detectors.py", line 2, in 
> from .generalized_rcnn import GeneralizedRCNN
> File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\detector\generalized_rcnn.py", line 11, in 
> from ..backbone import build_backbone
> File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\backbone__init__.py", line 2, in 
> from .backbone import build_backbone
> File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\backbone\backbone.py", line 7, in 
> from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
> File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\modeling\make_layers.py", line 10, in 
> from maskrcnn_benchmark.layers import Conv2d
> File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\layers__init__.py", line 9, in 
> from .nms import nms
> File "P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark\layers\nms.py", line 3, in 
> from maskrcnn_benchmark import _C
> ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (P:\test\maskrcnn-benchmark-master\demo\maskrcnn_benchmark__init__.py)
> 
> 怎么办,想问问答主有联系方式吗,能帮帮忙吗,被搞得很痛苦
from maskrcnn_benchmark import _C这句改成import maskrcnn_benchmark._C试试

**Comment by elevenjiang1** [comment]
非常感谢，之后在Ubuntu上面跑成了，虽然目前主要用tensoeflow的那个版本。
你的回复也顺带地提醒了我之后有时间也要去上面记录一下自己解决的方法，方便后面的人少跳坑哈哈哈


 
---Original---
