### ISSUE TITLE
AssertionError: assert torch.distributed.deprecated._initialized

### ISSUE THREAD

**Issue by zhangliukun** [facebookresearch/maskrcnn-benchmark#540]
## ❓ Questions and Help

I get an error when I use this command:
```json
python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/train_net.py --config-file "configs/e2e_faster_rcnn_R_101_FPN_1x.yaml"
```

Here is the error information:

```json
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train_net.py", line 176, in <module>
    main()
  File "tools/train_net.py", line 169, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 153, in make_data_loader
    sampler = make_data_sampler(dataset, shuffle, is_distributed)
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 58, in make_data_sampler
    return samplers.DistributedSampler(dataset, shuffle=shuffle)
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/samplers/distributed.py", line 30, in __init__
    num_replicas = dist.get_world_size()
  File "/home/zlk/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/deprecated/__init__.py", line 177, in get_world_size
    assert torch.distributed.deprecated._initialized
AssertionError
loading annotations into memory...
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Done (t=0.04s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train_net.py", line 176, in <module>
    main()
  File "tools/train_net.py", line 169, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 153, in make_data_loader
    sampler = make_data_sampler(dataset, shuffle, is_distributed)
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 58, in make_data_sampler
    return samplers.DistributedSampler(dataset, shuffle=shuffle)
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/samplers/distributed.py", line 30, in __init__
    num_replicas = dist.get_world_size()
  File "/home/zlk/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/deprecated/__init__.py", line 177, in get_world_size
    assert torch.distributed.deprecated._initialized
AssertionError
Traceback (most recent call last):
  File "tools/train_net.py", line 176, in <module>
    main()
  File "tools/train_net.py", line 169, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 153, in make_data_loader
    sampler = make_data_sampler(dataset, shuffle, is_distributed)
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 58, in make_data_sampler
    return samplers.DistributedSampler(dataset, shuffle=shuffle)
  File "/home/zlk/project/maskscoring_rcnn/maskrcnn_benchmark/data/samplers/distributed.py", line 30, in __init__
    num_replicas = dist.get_world_size()
  File "/home/zlk/miniconda3/envs/python36/lib/python3.6/site-packages/torch/distributed/deprecated/__init__.py", line 177, in get_world_size
    assert torch.distributed.deprecated._initialized
AssertionError

```

My environment is good,because there is no problem in running the original version.
But now I don't know why I encounter this problem.
Thank you for your help.

**Comment by fmassa** [comment]
We don't use the deprecated distributed module anymore, maybe you could try updating your install of `maskrcnn-benchmark`?
This should fix your issue
