### ISSUE TITLE
resnet18 backbone error

### ISSUE THREAD

**Issue by CF2220160244** [facebookresearch/maskrcnn-benchmark#566]
I change the resnet50 to resnet18，i change the code and get the right resnet18 structrue，
but have this error：

2019-03-14 14:03:36,553 maskrcnn_benchmark.utils.checkpoint INFO: Loading checkpoint from /home/chenfei/.torch/models/resnet18-5c106cde.pth
2019-03-14 14:03:36,608 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn1.bias                  loaded from layer1.0.bn1.bias                  of shape (64,)
2019-03-14 14:03:36,608 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn1.running_mean          loaded from layer1.0.bn1.running_mean          of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn1.running_var           loaded from layer1.0.bn1.running_var           of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn1.weight                loaded from layer1.0.bn1.weight                of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn2.bias                  loaded from layer1.0.bn2.bias                  of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn2.running_mean          loaded from layer1.0.bn2.running_mean          of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn2.running_var           loaded from layer1.0.bn2.running_var           of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.bn2.weight                loaded from layer1.0.bn2.weight                of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.conv1.weight              loaded from layer1.0.conv1.weight              of shape (64, 64, 3, 3)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.0.conv2.weight              loaded from layer1.0.conv2.weight              of shape (64, 64, 3, 3)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.bn1.bias                  loaded from layer1.1.bn1.bias                  of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.bn1.running_mean          loaded from layer1.1.bn1.running_mean          of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.bn1.running_var           loaded from layer1.1.bn1.running_var           of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.bn1.weight                loaded from layer1.1.bn1.weight                of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.bn2.bias                  loaded from layer1.1.bn2.bias                  of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.bn2.running_mean          loaded from layer1.1.bn2.running_mean          of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.bn2.running_var           loaded from layer1.1.bn2.running_var           of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.bn2.weight                loaded from layer1.1.bn2.weight                of shape (64,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.conv1.weight              loaded from layer1.1.conv1.weight              of shape (64, 64, 3, 3)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer1.1.conv2.weight              loaded from layer1.1.conv2.weight              of shape (64, 64, 3, 3)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.bn1.bias                  loaded from layer2.0.bn1.bias                  of shape (128,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.bn1.running_mean          loaded from layer2.0.bn1.running_mean          of shape (128,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.bn1.running_var           loaded from layer2.0.bn1.running_var           of shape (128,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.bn1.weight                loaded from layer2.0.bn1.weight                of shape (128,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.bn2.bias                  loaded from layer2.0.bn2.bias                  of shape (128,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.bn2.running_mean          loaded from layer2.0.bn2.running_mean          of shape (128,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.bn2.running_var           loaded from layer2.0.bn2.running_var           of shape (128,)
2019-03-14 14:03:36,609 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.bn2.weight                loaded from layer2.0.bn2.weight                of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.conv1.weight              loaded from layer2.0.conv1.weight              of shape (128, 64, 3, 3)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.conv2.weight              loaded from layer2.0.conv2.weight              of shape (128, 128, 3, 3)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.downsample.0.weight       loaded from layer2.0.downsample.0.weight       of shape (128, 64, 1, 1)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.downsample.1.bias         loaded from layer2.0.downsample.1.bias         of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.downsample.1.running_mean loaded from layer2.0.downsample.1.running_mean of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.downsample.1.running_var  loaded from layer2.0.downsample.1.running_var  of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.0.downsample.1.weight       loaded from layer2.0.downsample.1.weight       of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.bn1.bias                  loaded from layer2.1.bn1.bias                  of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.bn1.running_mean          loaded from layer2.1.bn1.running_mean          of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.bn1.running_var           loaded from layer2.1.bn1.running_var           of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.bn1.weight                loaded from layer2.1.bn1.weight                of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.bn2.bias                  loaded from layer2.1.bn2.bias                  of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.bn2.running_mean          loaded from layer2.1.bn2.running_mean          of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.bn2.running_var           loaded from layer2.1.bn2.running_var           of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.bn2.weight                loaded from layer2.1.bn2.weight                of shape (128,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.conv1.weight              loaded from layer2.1.conv1.weight              of shape (128, 128, 3, 3)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer2.1.conv2.weight              loaded from layer2.1.conv2.weight              of shape (128, 128, 3, 3)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.bn1.bias                  loaded from layer3.0.bn1.bias                  of shape (256,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.bn1.running_mean          loaded from layer3.0.bn1.running_mean          of shape (256,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.bn1.running_var           loaded from layer3.0.bn1.running_var           of shape (256,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.bn1.weight                loaded from layer3.0.bn1.weight                of shape (256,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.bn2.bias                  loaded from layer3.0.bn2.bias                  of shape (256,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.bn2.running_mean          loaded from layer3.0.bn2.running_mean          of shape (256,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.bn2.running_var           loaded from layer3.0.bn2.running_var           of shape (256,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.bn2.weight                loaded from layer3.0.bn2.weight                of shape (256,)
2019-03-14 14:03:36,610 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.conv1.weight              loaded from layer3.0.conv1.weight              of shape (256, 128, 3, 3)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.conv2.weight              loaded from layer3.0.conv2.weight              of shape (256, 256, 3, 3)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.downsample.0.weight       loaded from layer3.0.downsample.0.weight       of shape (256, 128, 1, 1)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.downsample.1.bias         loaded from layer3.0.downsample.1.bias         of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.downsample.1.running_mean loaded from layer3.0.downsample.1.running_mean of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.downsample.1.running_var  loaded from layer3.0.downsample.1.running_var  of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.0.downsample.1.weight       loaded from layer3.0.downsample.1.weight       of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.bn1.bias                  loaded from layer3.1.bn1.bias                  of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.bn1.running_mean          loaded from layer3.1.bn1.running_mean          of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.bn1.running_var           loaded from layer3.1.bn1.running_var           of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.bn1.weight                loaded from layer3.1.bn1.weight                of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.bn2.bias                  loaded from layer3.1.bn2.bias                  of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.bn2.running_mean          loaded from layer3.1.bn2.running_mean          of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.bn2.running_var           loaded from layer3.1.bn2.running_var           of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.bn2.weight                loaded from layer3.1.bn2.weight                of shape (256,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.conv1.weight              loaded from layer3.1.conv1.weight              of shape (256, 256, 3, 3)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer3.1.conv2.weight              loaded from layer3.1.conv2.weight              of shape (256, 256, 3, 3)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.bn1.bias                  loaded from layer4.0.bn1.bias                  of shape (512,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.bn1.running_mean          loaded from layer4.0.bn1.running_mean          of shape (512,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.bn1.running_var           loaded from layer4.0.bn1.running_var           of shape (512,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.bn1.weight                loaded from layer4.0.bn1.weight                of shape (512,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.bn2.bias                  loaded from layer4.0.bn2.bias                  of shape (512,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.bn2.running_mean          loaded from layer4.0.bn2.running_mean          of shape (512,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.bn2.running_var           loaded from layer4.0.bn2.running_var           of shape (512,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.bn2.weight                loaded from layer4.0.bn2.weight                of shape (512,)
2019-03-14 14:03:36,611 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.conv1.weight              loaded from layer4.0.conv1.weight              of shape (512, 256, 3, 3)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.conv2.weight              loaded from layer4.0.conv2.weight              of shape (512, 512, 3, 3)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.downsample.0.weight       loaded from layer4.0.downsample.0.weight       of shape (512, 256, 1, 1)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.downsample.1.bias         loaded from layer4.0.downsample.1.bias         of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.downsample.1.running_mean loaded from layer4.0.downsample.1.running_mean of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.downsample.1.running_var  loaded from layer4.0.downsample.1.running_var  of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.0.downsample.1.weight       loaded from layer4.0.downsample.1.weight       of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.bn1.bias                  loaded from layer4.1.bn1.bias                  of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.bn1.running_mean          loaded from layer4.1.bn1.running_mean          of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.bn1.running_var           loaded from layer4.1.bn1.running_var           of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.bn1.weight                loaded from layer4.1.bn1.weight                of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.bn2.bias                  loaded from layer4.1.bn2.bias                  of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.bn2.running_mean          loaded from layer4.1.bn2.running_mean          of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.bn2.running_var           loaded from layer4.1.bn2.running_var           of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.bn2.weight                loaded from layer4.1.bn2.weight                of shape (512,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.conv1.weight              loaded from layer4.1.conv1.weight              of shape (512, 512, 3, 3)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.layer4.1.conv2.weight              loaded from layer4.1.conv2.weight              of shape (512, 512, 3, 3)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.bn1.bias                      loaded from bn1.bias                           of shape (64,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.bn1.running_mean              loaded from bn1.running_mean                   of shape (64,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.bn1.running_var               loaded from bn1.running_var                    of shape (64,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.bn1.weight                    loaded from bn1.weight                         of shape (64,)
2019-03-14 14:03:36,612 maskrcnn_benchmark.utils.model_serialization INFO: backbone.body.stem.conv1.weight                  loaded from conv1.weight                       of shape (64, 3, 7, 7)
2019-03-14 14:03:36,851 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 73, in train
    arguments,
  File "/home/chenfei/github/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 66, in do_train
    loss_dict = model(images, targets)
  File "/home/chenfei/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenfei/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 49, in forward
    features = self.backbone(images.tensors)
  File "/home/chenfei/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenfei/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/chenfei/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenfei/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/resnet.py", line 127, in forward
    x = getattr(self, stage_name)(x)
  File "/home/chenfei/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenfei/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/chenfei/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenfei/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/resnet.py", line 330, in forward
    out += residual
RuntimeError: The size of tensor a (334) must match the size of tensor b (336) at non-singleton dimension 3

 layer1
Sequential(
  (0): BottleneckWithFixedBatchNorm(
    (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), bias=False)
    (bn1): FrozenBatchNorm2d()
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): FrozenBatchNorm2d()
  )
  (1): BottleneckWithFixedBatchNorm(
    (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), bias=False)
    (bn1): FrozenBatchNorm2d()
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): FrozenBatchNorm2d()
  )
)
layer2
Sequential(
  (0): BottleneckWithFixedBatchNorm(
    (downsample): Sequential(
      (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
      (1): FrozenBatchNorm2d()
    )
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), bias=False)
    (bn1): FrozenBatchNorm2d()
    (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): FrozenBatchNorm2d()
  )
  (1): BottleneckWithFixedBatchNorm(
    (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), bias=False)
    (bn1): FrozenBatchNorm2d()
    (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): FrozenBatchNorm2d()
  )
)
layer3
Sequential(
  (0): BottleneckWithFixedBatchNorm(
    (downsample): Sequential(
      (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
      (1): FrozenBatchNorm2d()
    )
    (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), bias=False)
    (bn1): FrozenBatchNorm2d()
    (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): FrozenBatchNorm2d()
  )
  (1): BottleneckWithFixedBatchNorm(
    (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), bias=False)
    (bn1): FrozenBatchNorm2d()
    (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): FrozenBatchNorm2d()
  )
)
layer4
Sequential(
  (0): BottleneckWithFixedBatchNorm(
    (downsample): Sequential(
      (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
      (1): FrozenBatchNorm2d()
    )
    (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), bias=False)
    (bn1): FrozenBatchNorm2d()
    (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): FrozenBatchNorm2d()
  )
  (1): BottleneckWithFixedBatchNorm(
    (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), bias=False)
    (bn1): FrozenBatchNorm2d()
    (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): FrozenBatchNorm2d()
  )
)

**Comment by fmassa** [comment]
The resnet18 structure is not right: you are using the Bottleneck block, and not the BasicBlock.
If you change this it should work

**Comment by magistri** [comment]
Is the BasicBlock already implemented?
