### ISSUE TITLE
When evaluating the results, encounter the problem of JSONDecodeError

### ISSUE THREAD

**Issue by weiyaowu666** [facebookresearch/maskrcnn-benchmark#591]
## ❓ Questions and Help
`Loading and preparing results...
Traceback (most recent call last):
  File "tools/test_net.py", line 97, in <module>
    main()
  File "tools/test_net.py", line 91, in main
    output_folder=output_folder,
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 100, in inference
    **extra_args)
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 22, in evaluate
    return coco_evaluation(**args)
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py", line 20, in coco_evaluation
    expected_results_sigma_tol=expected_results_sigma_tol,
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 60, in do_coco_evaluation
    dataset.coco, coco_results[iou_type], file_path, iou_type
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 319, in evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(str(json_result_file)) if coco_results else COCO()
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 309, in loadRes
    anns = json.load(open(resFile))
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by fmassa** [comment]
This means that your model didn't output anything maybe, or was None?

**Comment by weiyaowu666** [comment]
The model output and eval normally, when the model finished bbox eval process, and it want to eval segm next,  the result like follow(:

`2019-04-06 09:09:41,954 maskrcnn_benchmark.inference INFO: Preparing bbox results
2019-04-06 09:09:42,732 maskrcnn_benchmark.inference INFO: Preparing segm results
3000it [22:19,  2.78it/s]
2019-04-06 09:32:02,360 maskrcnn_benchmark.inference INFO: Evaluating predictions
Loading and preparing results...
DONE (t=1.11s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=39.01s).
Accumulating evaluation results...
DONE (t=8.80s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.504
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.774
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.582
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.277
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.549
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.656
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.094
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.504
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.630
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.460
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.666
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.757
Loading and preparing results...
Traceback (most recent call last):
  File "tools/test_net.py", line 97, in <module>
    main()
  File "tools/test_net.py", line 91, in main
    output_folder=output_folder,
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 100, in inference
    **extra_args)
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 22, in evaluate
    return coco_evaluation(**args)
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py", line 20, in coco_evaluation
    expected_results_sigma_tol=expected_results_sigma_tol,
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 60, in do_coco_evaluation
    dataset.coco, coco_results[iou_type], file_path, iou_type
  File "/workspace/mnt/group/fd-students/weiyaowu/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 319, in evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(str(json_result_file)) if coco_results else COCO()
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 309, in loadRes
    anns = json.load(open(resFile))
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/workspace/mnt/group/fd-students/weiyaowu/anaconda/envs/maskrcnn_benchmark/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
