### ISSUE TITLE
ValueError: last dimension of bbox should have a size of 4, got 0

### ISSUE THREAD

**Issue by TyroneLi** [facebookresearch/maskrcnn-benchmark#600]
## ❓ Questions and Help
I run on my own dataset which is made into pascal voc format.I simply run on the command:
python tools/train_net.py --config-file "experiments/cfgs/e2e_faster_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 1 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 7200 TEST.IMS_PER_BATCH 1

At the beginning, everything went fine,but after several steps, I got this error:
File "tools/train_net.py", line 177, in <module>
    main()
  File "tools/train_net.py", line 170, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 74, in train
    arguments,
  File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 551, in __next__
    return self._process_next_batch(batch)
  File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 572, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 83, in __getitem__
    target = self.get_groundtruth(index)
  File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 104, in get_groundtruth
    target = BoxList(anno["boxes"], (width, height), mode="xyxy")
  File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 37, in __init__
    "size of 4, got {}".format(bbox.size(-1))
ValueError: last dimension of bbox should have a size of 4, got 0

I did chek my dataset,and I can't find something wrong in file format or anything different with formal pascal voc.But I still got this error.However when I run formal pascal voc,this would not happen.Someone met this problem before?How can I fix this?

**Comment by TyroneLi** [comment]
Beacuse in bounding_box.py source code,I made some changes:
original:
if bbox.ndimension() != 2:
            raise ValueError(
                "bbox should have 2 dimensions, got {}".format(bbox.ndimension())
            )
changed:
if bbox.ndimension() != 2:
            # print("wrong bbox:")
            # print(bbox)
            bbox = torch.unsqueeze(bbox, 0)
            # print(bbox)
If I didn't made this change,I would got this error:
File "tools/train_net.py", line 177, in <module>
    main()
  File "tools/train_net.py", line 170, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 74, in train
    arguments,
  File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 551, in __next__
    return self._process_next_batch(batch)
  File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 572, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 83, in __getitem__
    target = self.get_groundtruth(index)
  File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 105, in get_groundtruth
    target = BoxList(anno["boxes"], (width, height), mode="xyxy")
  File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 25, in __init__
    "bbox should have 2 dimensions, got {}".format(bbox.ndimension())
ValueError: bbox should have 2 dimensions, got 1

someone could help me to figure out why?

**Comment by TyroneLi** [comment]
**Beacuse in bounding_box.py source code,I made some changes:**
**original:**
if bbox.ndimension() != 2:
raise ValueError(
"bbox should have 2 dimensions, got {}".format(bbox.ndimension())
)
**changed:**
if bbox.ndimension() != 2:
# print("wrong bbox:")
# print(bbox)
bbox = torch.unsqueeze(bbox, 0)
# print(bbox)
If I didn't made this change,I would got this error:
File "tools/train_net.py", line 177, in 
main()
File "tools/train_net.py", line 170, in main
model = train(cfg, args.local_rank, args.distributed)
File "tools/train_net.py", line 74, in train
arguments,
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 551, in next
return self._process_next_batch(batch)
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 572, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in 
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 83, in getitem
target = self.get_groundtruth(index)
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 105, in get_groundtruth
target = BoxList(anno["boxes"], (width, height), mode="xyxy")
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 25, in init
"bbox should have 2 dimensions, got {}".format(bbox.ndimension())
ValueError: bbox should have 2 dimensions, got 1

**someone could help me to figure out why?**

**Comment by TyroneLi** [comment]
**Beacuse in bounding_box.py source code,I made some changes:**
_original_:
if bbox.ndimension() != 2:
raise ValueError(
"bbox should have 2 dimensions, got {}".format(bbox.ndimension())
)
_changed_:
if bbox.ndimension() != 2:
# print("wrong bbox:")
# print(bbox)
bbox = torch.unsqueeze(bbox, 0)
# print(bbox)
If I didn't made this change,I would got this error:
File "tools/train_net.py", line 177, in 
main()
File "tools/train_net.py", line 170, in main
model = train(cfg, args.local_rank, args.distributed)
File "tools/train_net.py", line 74, in train
arguments,
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 551, in next
return self._process_next_batch(batch)
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 572, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in 
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 83, in getitem
target = self.get_groundtruth(index)
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 105, in get_groundtruth
target = BoxList(anno["boxes"], (width, height), mode="xyxy")
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 25, in init
"bbox should have 2 dimensions, got {}".format(bbox.ndimension())
ValueError: bbox should have 2 dimensions, got 1

**someone could help me to figure out why?**

**Comment by TyroneLi** [comment]
**Beacuse in bounding_box.py source code,I made some changes:**
original:
if bbox.ndimension() != 2:
raise ValueError(
"bbox should have 2 dimensions, got {}".format(bbox.ndimension())
)
changed:
if bbox.ndimension() != 2:
# print("wrong bbox:")
# print(bbox)
bbox = torch.unsqueeze(bbox, 0)
# print(bbox)
If I didn't made this change,I would got this error:
File "tools/train_net.py", line 177, in 
main()
File "tools/train_net.py", line 170, in main
model = train(cfg, args.local_rank, args.distributed)
File "tools/train_net.py", line 74, in train
arguments,
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 551, in next
return self._process_next_batch(batch)
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 572, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/king/anaconda3/envs/pytorch_maskrcnn_benchmark/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in 
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 83, in getitem
target = self.get_groundtruth(index)
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/voc.py", line 105, in get_groundtruth
target = BoxList(anno["boxes"], (width, height), mode="xyxy")
File "/home/king/githubToolkit/maskrcnn-benchmark/maskrcnn_benchmark/structures/bounding_box.py", line 25, in init
"bbox should have 2 dimensions, got {}".format(bbox.ndimension())
ValueError: bbox should have 2 dimensions, got 1

**someone could help me to figure out why?**

**Comment by TyroneLi** [comment]
I solved this now,because one of my dataset has no object bounding box,so it cann't work in RPN.I will delete this problem.

**Comment by chengyangfu** [comment]
Hi @TyroneLi 
  I'm closing this issue, please let me know if you need any further help.

**Comment by TyroneLi** [comment]
That's aahh so embarrased,it seems I have no control to delete this issue,except the admin..

**Comment by lanfeng4659** [comment]
hi, how did you solve this problem when no target exists on an image?
