### ISSUE TITLE
Testing image -- RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1]

### ISSUE THREAD

**Issue by Phyllis9811** [facebookresearch/maskrcnn-benchmark#615]
## ❓ Questions and Help
When I tried to test images, I got 
Traceback (most recent call last):
  File "tools/train_net.py", line 180, in <module>
    main()
  File "tools/train_net.py", line 176, in main
    test(cfg, model, args.distributed)
  File "tools/train_net.py", line 112, in test
    output_folder=output_folder,
  File "/home/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 79, in inference
    predictions = compute_on_dataset(model, data_loader, device)
  File "/home/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 27, in compute_on_dataset
    output = model(images)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 56, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 26, in forward
    x, detections, loss_box = self.box(features, proposals, targets)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/box_head.py", line 46, in forward
    x = self.feature_extractor(features, proposals)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_feature_extractors.py", line 75, in forward
    x = x.view(x.size(0), -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1]
Does anyone have the same issue?

**Comment by LeviViana** [comment]
I'm not sure I understood: what are you trying to test ? why your error log shows errors related to `tools/train_net.py` ?

**Comment by dylanlee101** [comment]
I have the same issue,how to solve it?

**Comment by Phyllis9811** [comment]
I reinstalled the package and then everything worked fine.

**Comment by DuncanChen2018** [comment]
I have the same issue when I use GN in the Mask R-CNN, however it works when GN is eliminated.

**Comment by jyohei** [comment]
I have the same issue,how to solve it?

**Comment by jyohei** [comment]
> I reinstalled the package and then everything worked fine.
I have the same issue，Can you tell the specific solution?

**Comment by jyohei** [comment]
> I reinstalled the package and then everything worked fine.

I have the same issue，Can you tell the specific solution?

**Comment by ShihuaiXu** [comment]
123

**Comment by chang010453** [comment]
I have the same issue when I train on COCO dataset, but not on my own dataset.
How to solve it?
