### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Iamal1** [facebookresearch/maskrcnn-benchmark#668]
## ❓ Questions and Help
Firstly I run the first training script given and met segmentation fault .

Then I run with `python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/train_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml"
` and I get
 
`2019-04-12 17:28:09,076 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/maskrcnn_benchmark/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/e2e_mask_rcnn_R_50_FPN_1x.yaml']' died with <Signals.SIGSEGV: 11>.
`
Or run with 
`python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/train_net.py --config-file "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml" SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 SOLVER.MAX_ITER 720000 SOLVER.STEPS "(480000, 640000)" TEST.IMS_PER_BATCH 1`

I get:
`AssertionError: SOLVER.IMS_PER_BATCH ({}) must be divisible by the number
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 167, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/versa/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 113, in make_data_loader
    ), "SOLVER.IMS_PER_BATCH ({}) must be divisible by the number "
AssertionError: SOLVER.IMS_PER_BATCH ({}) must be divisible by the number
Traceback (most recent call last):
  File "tools/train_net.py", line 174, in <module>
    main()
  File "tools/train_net.py", line 167, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/versa/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py", line 113, in make_data_loader
    ), "SOLVER.IMS_PER_BATCH ({}) must be divisible by the number "
AssertionError: SOLVER.IMS_PER_BATCH ({}) must be divisible by the number
Traceback (most recent call last):
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/root/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/maskrcnn_benchmark/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/e2e_mask_rcnn_R_50_FPN_1x.yaml', 'SOLVER.IMS_PER_BATCH', '2', 'SOLVER.BASE_LR', '0.0025', 'SOLVER.MAX_ITER', '720000', 'SOLVER.STEPS', '(480000, 640000)', 'TEST.IMS_PER_BATCH', '1']' returned non-zero exit status 1.
`
I'm new to this, so for the last one I think I will find how to solve it later by modifying some settings, but I could not understand the previous ones
Actually I followed the instructions from INSTALL.md and it will install python3.7 by default and install both pytorch and nightly release, maybe this is where the problem is.
I'll check them next week, I'd appreciate if anyone knows the solution and would help

**Comment by Iamal1** [comment]
The segmentation fault can be solved by setting the gcc to right version: >=4.9 as in other issues. And temporarily I don't use multi-gpu now so I'm not sure for other problems.

**Comment by VCBE123** [comment]
you set  SOLVER.IMS_PER_BATCH = 2 , Maybe you use more than 2 GPUs.

**Comment by Iamal1** [comment]
The last problem comes from the SOLVER.IMS_PER_BATCH setting, it should be divisible by #gpus, as it suggest: `AssertionError: SOLVER.IMS_PER_BATCH ({}) must be divisible by the number`
