### ISSUE TITLE
The error occurred with 2 gpus and the server became very dull。help me,please!

### ISSUE THREAD

**Issue by my-hello-world** [facebookresearch/maskrcnn-benchmark#682]
## ❓ Questions and Help
`$ python -m torch.distributed.launch --nproc_per_node=2 tools/train_net.py --config-file config/e2e_keypoint_rcnn_R_50_FPN_1x.yaml
Traceback (most recent call last):
  File "tools/train_net.py", line 211, in <module>
    main()
  File "tools/train_net.py", line 178, in main
    backend="nccl", init_method="env://"
  File "/home/xxx/anaconda3/envs/torch1n/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 386, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/xxx/anaconda3/envs/torch1n/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/torch1n/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxx/anaconda3/envs/torch1n/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/anaconda3/envs/torch1n/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/xxx/anaconda3/envs/torch1n/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/xxx/anaconda3/envs/torch1n/bin/python', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'config/e2e_keypoint_rcnn_R_50_FPN_1x.yaml']' returned non-zero exit status 1.
(torch1n) xxx@xxx-Super-Server:/media/hello/helloworld/maskrcnn-keypoint$ 
Traceback (most recent call last):
  File "tools/train_net.py", line 211, in <module>
    main()
  File "tools/train_net.py", line 180, in main
    synchronize()
  File "/media/hello/helloworld/maskrcnn-keypoint/maskrcnn_benchmark/utils/comm.py", line 45, in synchronize
    dist.barrier()
  File "/home/xxx/anaconda3/envs/torch1n/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1226, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:409, unhandled cuda error
`
i also ：
```

1. 

CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node 2 --master_addr 127.0.0.2  --master_port 29501 tools/train_net.py --config-file /config/e2e_keypoint_rcnn_R_50_FPN_l.yaml
不动 CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node=2 tools/train_net.py --config-file config/e2e_keypoint_rcnn_R_50_FPN_light-Small-nms-fusion.yaml
不动 python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_port='25999' tools/train_net.py --config-file configs/e2e_keypoint_rcnn_R_50_FPN_light-Small-nms-fusion.yaml
```

python -m torch.distributed.launch --nproc_per_node=2 --nnodes=2 --node_rank=0 --master_port='18887' tools/train_net.py --config-file configs/e2e_keypoint_rcnn_R_50_FPN.yaml

**Comment by my-hello-world** [comment]
or can use hyperparameter NUM_GPUS？ like ：https://github.com/roytseng-tw/Detectron.pytorch
