### ISSUE TITLE
Issue with Demo

### ISSUE THREAD

**Issue by bebenoz** [facebookresearch/maskrcnn-benchmark#691]
## 🐛 Bug

Hello,
After following the steps in installation Option 1 Step by step installation. Everything seems to be ok installation wise however when I try to run the demo code for webcam I get the following error. 
python webcam.py --min-image-size 800
Traceback (most recent call last):
  File "webcam.py", line 6, in <module>
    from predictor import COCODemo
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/demo/predictor.py", line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/make_layers.py", line 10, in <module>
    from maskrcnn_benchmark.layers import Conv2d
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 9, in <module>
    from .nms import nms
  File "/home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /home/nova/mask-rcnn/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd
My specs are as follows

![image](https://user-images.githubusercontent.com/37660284/56365830-712cf200-61fa-11e9-8284-693cd136aeb5.png)

Thanks

**Comment by chengyangfu** [comment]
Hi @bebenoz , 
   This is caused when you use different PyTorch versions to compile and execute the code. 
    Make sure you use the same PyTorch version/library to compile and run the code. Then remove the build directory and recompile the maskrcnn-benchmark. 
```
rm -rf build
python setup.py build develop
```

**Comment by Dorozhko-Anton** [comment]
Hi @bebenoz . were you able to solve the problem ?
If no, could you provide environment info using `collect_env.py` script ?

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
