### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by hughes20** [facebookresearch/maskrcnn-benchmark#712]
## ❓ Questions and Help
I have my own custom model with one class. I have first trained on this model + the coco dataset and set the number of classes to 82 (80 coco, 1 mine, 1 for background)
I then go to train only on my one class and i get the following error message:

> 2019-04-24 01:36:51,830 maskrcnn_benchmark.trainer INFO: Start training
/opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_$
Traceback (most recent call last):
  File "/home/mav/Hughes/rrg/src/perception/detectron/pytorch-implementation/maskrcnn-benchmark/tools/train_net.py", l$
    main()
  File "/home/mav/Hughes/rrg/src/perception/detectron/pytorch-implementation/maskrcnn-benchmark/tools/train_net.py", l$
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/mav/Hughes/rrg/src/perception/detectron/pytorch-implementation/maskrcnn-benchmark/tools/train_net.py", l$
    arguments,
  File "/home/mav/Hughes/rrg/src/perception/detectron/pytorch-implementation/maskrcnn-benchmark/maskrcnn_benchmark/eng$
    loss_dict = model(images, targets)
  File "/home/mav/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489,$
    result = self.forward(*input, **kwargs)
  File "/home/mav/Hughes/rrg/src/perception/detectron/pytorch-implementation/maskrcnn-benchmark/maskrcnn_benchmark/mod$
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/mav/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489,$
    result = self.forward(*input, **kwargs)
  File "/home/mav/Hughes/rrg/src/perception/detectron/pytorch-implementation/maskrcnn-benchmark/maskrcnn_benchmark/mod$
    x, detections, loss_box = self.box(features, proposals, targets)
  File "/home/mav/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489,$
    result = self.forward(*input, **kwargs)
  File "/home/mav/Hughes/rrg/src/perception/detectron/pytorch-implementation/maskrcnn-benchmark/maskrcnn_benchmark/mod$
    [class_logits], [box_regression]
  File "/home/mav/Hughes/rrg/src/perception/detectron/pytorch-implementation/maskrcnn-benchmark/maskrcnn_benchmark/mod$
    sampled_pos_inds_subset = torch.nonzero(labels > 0).squeeze(1)
RuntimeError: copy_if failed to synchronize: device-side assert triggered

The only thing changing between config files is ROI_BOX_HEAD.NUM_CLASSES which is changed to 2 for just my class and background... using the R-50-FPN pretrained model for both. Any possible fixes to try?

CONFIG for reference:

> MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "./my_model.pkl"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2 #will change during code
DATASETS:
  TRAIN: ('Custom_train',)
  TEST: ('Custom_val',)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  MAX_ITER: 10000
  STEPS: (6000, 8000)
  CHECKPOINT_PERIOD: 1000
TEST:
  IMS_PER_BATCH: 1

>

**Comment by hughes20** [comment]
Also needed to modify retinanet num_classes

**Comment by vishal-prgmr** [comment]
> Also needed to modify retinanet num_classes

@hughes20 , where did you change this ?

**Comment by alongGS** [comment]
could you point out where you did ? thanks, I don't know which one you mean.

**Comment by alongGS** [comment]
em...Thanks, I have sloved this problem, by changing num_classes in defaults.py, and fix up my datasets problem.

**Comment by botcs** [comment]
Eeeeey @alongGS why did you change the defaults?
Just change it in the YAML config file
