### ISSUE TITLE
i use coco 2014 to train rpn network, when training happen same train image can't load, did any body know?

### ISSUE THREAD

**Issue by mlinxiang** [facebookresearch/maskrcnn-benchmark#73]
## ❓ Questions and Help
i ls coco/train2014 dir has 82385 images, and i debug to cocoapi load annotation json parse 82783 images.  in coco api has filter image has no annotation , but do't has filter has annotation but image not exist? 
i down load instances_minival2014.json instances_valminusminival2014.json from internet， will this has same problem?
![image](https://user-images.githubusercontent.com/6283983/47776782-27c11700-dd2e-11e8-8193-98104e90da94.png)

**Comment by fmassa** [comment]
Did you set the symlinks for the dataset, as explained in the README?

**Comment by mlinxiang** [comment]
@fmassa  yes i do that as readme, and i train success serval steps
![image](https://user-images.githubusercontent.com/6283983/47776972-9ef6ab00-dd2e-11e8-9e09-cd9e7990f8df.png)
![image](https://user-images.githubusercontent.com/6283983/47777001-b33aa800-dd2e-11e8-8e4a-afc0be708646.png)

**Comment by fmassa** [comment]
This is very weird, looks like your image folders doesn't match the annotations, or that some images were not downloaded

This shouldn't happen with a new download from the COCO website.

**Comment by mlinxiang** [comment]
@fmassa the axel breakpoint resume cause some image not download， i doesn't check the final md5, redownload from coco fix my fault. very thanks

**Comment by aishetty** [comment]
I have the same issue. I have a new download from COCO website as well. 

_loading annotations into memory...
Done (t=4.30s)
creating index...
index created!
2019-06-21 13:32:46,203 maskrcnn_benchmark.utils.miscellaneous WARNING: Dataset [ConcatDataset] has no categories attribute, labels.json file won't be created
2019-06-21 13:32:46,482 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "./tools/train_net.py", line 191, in <module>
    main()
  File "./tools/train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "./tools/train_net.py", line 85, in train
    arguments,
  File "/home/aishwarya/thesis/facebook-detectron/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/aishwarya/thesis/facebook-detectron/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 69, in __getitem__
    img, anno = super(COCODataset, self).__getitem__(idx)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/coco.py", line 112, in __getitem__
    img = Image.open(os.path.join(self.root, path)).convert('RGB')
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/coco/train2014/COCO_train2014_000000365261.jpg'_

Kindly help out with this. This happens during training. I have followed all the steps in the ReadMe
