### ISSUE TITLE
EOF error

### ISSUE THREAD

**Issue by YuhanLiu11** [facebookresearch/maskrcnn-benchmark#730]
## ❓ Questions and Help
Hi, 

We first encountered the issue of 

Traceback (most recent call last):
  File "tools/train_net.py", line 26, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/srv/home/whao/torchMaskRCNN/run2/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/srv/home/whao/torchMaskRCNN/run2/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from torch.utils.model_zoo import _download_url_to_file
ImportError: cannot import name '_download_url_to_file'

And then after replacing the  torch.utils.model_zoo import _download_url_to_file by from torch.utils.model_zoo import _download_url_to_file as indicated by https://github.com/facebookresearch/maskrcnn-benchmark/issues/674

We encountered another error: 

Traceback (most recent call last):
  File "tools/train_net.py", line 179, in <module>
    main()
  File "tools/train_net.py", line 172, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 78, in train
    arguments,
  File "/srv/home/whao/torchMaskRCNN/run1/maskrcnn_benchmark/engine/trainer.py", line 56, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/srv/home/whao/anaconda3/envs/torchMask/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

Any suggestions on what might be wrong?

Thank you so much for your help!

**Comment by tjzjp** [comment]
hello，have you fixed it?

**Comment by YuhanLiu11** [comment]
> hello，have you fixed it?

No. I still didn't solve the problem....

**Comment by tjzjp** [comment]
> hello，have you fixed it?
> 
> No. I still didn't solve the problem....

just make some changes in this: https://github.com/facebookresearch/maskrcnn-benchmark/pull/673/files#diff-1252846857806d2e6071bf2681a76631

it works for me!

**Comment by YuhanLiu11** [comment]
Yeah, I tried this, but then it fails by raising the EOFError....
