### ISSUE TITLE
single GPU training error

### ISSUE THREAD

**Issue by lshangguan** [facebookresearch/maskrcnn-benchmark#743]
## ❓ Questions and Help
I follow the example to train coco on a single GPU using the provided model config. However, when it starts training, the following errors occur. Could you help to point the potential problems here? Thank you!

> loading annotations into memory...
> Done (t=21.11s)
> creating index...
> index created!
> 2019-05-01 14:31:47,059 maskrcnn_benchmark.trainer INFO: Start training
> C:/w/1/s/tmp_conda_3.7_131644/conda/conda-bld/pytorch-nightly_1556630481283/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
> C:/w/1/s/tmp_conda_3.7_131644/conda/conda-bld/pytorch-nightly_1556630481283/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
> C:/w/1/s/tmp_conda_3.7_131644/conda/conda-bld/pytorch-nightly_1556630481283/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
> C:/w/1/s/tmp_conda_3.7_131644/conda/conda-bld/pytorch-nightly_1556630481283/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
> C:/w/1/s/tmp_conda_3.7_131644/conda/conda-bld/pytorch-nightly_1556630481283/work/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
> Traceback (most recent call last):
>   File ".\tools\train_net.py", line 186, in <module>
>     main()
>   File ".\tools\train_net.py", line 179, in main
>     model = train(cfg, args.local_rank, args.distributed)
>   File ".\tools\train_net.py", line 85, in train
>     arguments,
>   File "c:\users\loshangg\maskrcnn\maskrcnn-benchmark\maskrcnn_benchmark\engine\trainer.py", line 67, in do_train
>     loss_dict = model(images, targets)
>   File "C:\tools\anaconda\envs\maskrcnn\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\tools\anaconda\envs\maskrcnn\lib\site-packages\apex-0.1-py3.7-win-amd64.egg\apex\amp\_initialize.py", line 194, in new_fwd
>     **applier(kwargs, input_caster))
>   File "c:\users\loshangg\maskrcnn\maskrcnn-benchmark\maskrcnn_benchmark\modeling\detector\generalized_rcnn.py", line 52, in forward
>     x, result, detector_losses = self.roi_heads(features, proposals, targets)
>   File "C:\tools\anaconda\envs\maskrcnn\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "c:\users\loshangg\maskrcnn\maskrcnn-benchmark\maskrcnn_benchmark\modeling\roi_heads\roi_heads.py", line 26, in forward
>     x, detections, loss_box = self.box(features, proposals, targets)
>   File "C:\tools\anaconda\envs\maskrcnn\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "c:\users\loshangg\maskrcnn\maskrcnn-benchmark\maskrcnn_benchmark\modeling\roi_heads\box_head\box_head.py", line 56, in forward
>     [class_logits], [box_regression]
>   File "c:\users\loshangg\maskrcnn\maskrcnn-benchmark\maskrcnn_benchmark\modeling\roi_heads\box_head\loss.py", line 151, in __call__
>     sampled_pos_inds_subset = torch.nonzero(labels > 0).squeeze(1)
> RuntimeError: copy_if failed to synchronize: device-side assert triggered

**Comment by domarps** [comment]
Can you share the steps to reproduce this? Curious to know if you made any changes to the number of classes [here](https://github.com/facebookresearch/maskrcnn-benchmark/issues/297#issuecomment-449138630)
