### ISSUE TITLE
AssertionError: tensor([172.5300, 795.3013, 173.0343, 795.1953])

### ISSUE THREAD

**Issue by lmybaobao** [facebookresearch/maskrcnn-benchmark#759]
## ❓ Questions and Help
When I trained the mask-rcnn with my dataset, I got a unexpected error like the title in the 92620 iteration. I prepared my dataset with coco-style. 

The error:
```
2019-05-07 23:39:24,612 maskrcnn_benchmark.trainer INFO: eta: 4 days, 19:31:34  iter: 92520  loss: 0.1519 (0.2161)  loss_classifier: 0.0421 (0.0560)  loss_box_reg: 0.0192 (0.0351)  loss_mask: 0.0809 (0.1112)  loss_objectness: 0.0010 (0.0053)  loss_rpn_box_reg: 0.0029 (0.0086)  time: 0.6952 (0.6628)  data: 0.0066 (0.0081)  lr: 0.002500  max mem: 2653
2019-05-07 23:39:38,111 maskrcnn_benchmark.trainer INFO: eta: 4 days, 19:31:27  iter: 92540  loss: 0.1478 (0.2161)  loss_classifier: 0.0384 (0.0560)  loss_box_reg: 0.0201 (0.0351)  loss_mask: 0.0848 (0.1111)  loss_objectness: 0.0009 (0.0053)  loss_rpn_box_reg: 0.0036 (0.0086)  time: 0.6888 (0.6628)  data: 0.0067 (0.0081)  lr: 0.002500  max mem: 2653
2019-05-07 23:39:50,748 maskrcnn_benchmark.trainer INFO: eta: 4 days, 19:30:58  iter: 92560  loss: 0.1157 (0.2160)  loss_classifier: 0.0238 (0.0560)  loss_box_reg: 0.0128 (0.0350)  loss_mask: 0.0702 (0.1111)  loss_objectness: 0.0010 (0.0053)  loss_rpn_box_reg: 0.0018 (0.0086)  time: 0.6425 (0.6628)  data: 0.0048 (0.0081)  lr: 0.002500  max mem: 2653
2019-05-07 23:40:04,297 maskrcnn_benchmark.trainer INFO: eta: 4 days, 19:30:52  iter: 92580  loss: 0.1641 (0.2160)  loss_classifier: 0.0363 (0.0560)  loss_box_reg: 0.0217 (0.0350)  loss_mask: 0.0885 (0.1111)  loss_objectness: 0.0010 (0.0053)  loss_rpn_box_reg: 0.0037 (0.0086)  time: 0.6855 (0.6628)  data: 0.0062 (0.0081)  lr: 0.002500  max mem: 2653
2019-05-07 23:40:17,301 maskrcnn_benchmark.trainer INFO: eta: 4 days, 19:30:32  iter: 92600  loss: 0.1428 (0.2159)  loss_classifier: 0.0278 (0.0560)  loss_box_reg: 0.0150 (0.0350)  loss_mask: 0.0845 (0.1111)  loss_objectness: 0.0005 (0.0053)  loss_rpn_box_reg: 0.0026 (0.0086)  time: 0.6580 (0.6628)  data: 0.0054 (0.0081)  lr: 0.002500  max mem: 2653
2019-05-07 23:40:30,868 maskrcnn_benchmark.trainer INFO: eta: 4 days, 19:30:27  iter: 92620  loss: 0.1557 (0.2159)  loss_classifier: 0.0408 (0.0560)  loss_box_reg: 0.0156 (0.0350)  loss_mask: 0.0839 (0.1111)  loss_objectness: 0.0003 (0.0053)  loss_rpn_box_reg: 0.0026 (0.0086)  time: 0.6612 (0.6628)  data: 0.0064 (0.0081)  lr: 0.002500  max mem: 2653

Traceback (most recent call last):
  File "tools/train_net.py", line 186, in <module>
    main()
  File "tools/train_net.py", line 179, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 85, in train
    arguments,
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 67, in do_train
    loss_dict = model(images, targets)
  File "/home/lmy/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lmy/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/amp/_initialize.py", line 194, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/lmy/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 39, in forward
    x, detections, loss_mask = self.mask(mask_features, detections, targets)
  File "/home/lmy/anaconda3/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/mask_head.py", line 77, in forward
    loss_mask = self.loss_evaluator(proposals, mask_logits, targets)
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py", line 112, in __call__
    labels, mask_targets = self.prepare_targets(proposals, targets)
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py", line 94, in prepare_targets
    segmentation_masks, positive_proposals, self.discretization_size
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py", line 36, in project_masks_on_boxes
    cropped_mask = segmentation_mask.crop(proposal)
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 481, in crop
    cropped_instances = self.instances.crop(box)
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 385, in crop
    cropped_polygons.append(polygon.crop(box))
  File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 249, in crop
    assert xmin <= xmax and ymin <= ymax, str(box)
AssertionError: tensor([172.5300, 795.3013, 173.0343, 795.1953])
```

I only have 2-bit segmentation labels at the beginning, and I use the following code transform my label to the coco-style polygon segmentation and bbox:

```
def xmerge(a, b):
    alen, blen = len(a), len(b)
    mlen = min(alen, blen)
    for i in range(mlen):
        yield a[i]
        yield b[i]


def Subtraction(x):
    if x < 1 :
        return 0
    else:
        return (x-1)


def get_outline_(label_tif_path):
    # 这个函数用来得到每张图片的各个object的轮廓
    # label_tif_path：标记图片的路径
    img = io.imread(label_tif_path)  # 打开标记二值图片
    BLACK = [0, 0, 0]
    constant = cv2.copyMakeBorder(img, 1, 1, 1, 1, cv2.BORDER_CONSTANT, value=BLACK)
    contours = measure.find_contours(constant, 125)  # 获得连通域轮廓
    i = 0  # 计数
    dict_pos = {} # 存放object的信息

    for each in contours:  # 遍历每一个object的轮廓
        dict_position = [i for i in xmerge(list(map(Subtraction,each[:, 1])), list(map(Subtraction,each[:, 0])))]
        dict_pos[i] = dict_position
        i += 1  # 计数 加1


    return dict_pos


def get_boxes(label_tif_path):
    img = io.imread(label_tif_path)  # 打开标记二值图片
    BLACK = [0, 0, 0]
    constant = cv2.copyMakeBorder(img, 1, 1, 1, 1, cv2.BORDER_CONSTANT, value=BLACK)
    contours = measure.find_contours(constant, 125)  # 获得连通域轮廓
    i = 0  # 计数
    dict_id = {}  # 存放object的信息
    for each in contours:  # 遍历每一个object的轮廓
        dict_position = [0]*4 # 存放每一个object的信息
        dict_position[0]=min(list(map(Subtraction,each[:, 1]))) # x_min
        dict_position[1]=min(list(map(Subtraction,each[:, 0])))  # y_min
        dict_position[2] = max(list(map(Subtraction,each[:, 1])))# x_max
        dict_position[3] = max(list(map(Subtraction,each[:, 0])))# y_max
        dict_id[i]= dict_position
        i+=1
    return i,dict_id
```

Is it the result of mistakes in my label conversion process? please help me, thank you!

**Comment by ccxu** [comment]
does this problem solved? our data appeared the same error.

**Comment by lmybaobao** [comment]
@ccxu no, I haven't. The code for label conversion worked well in a dataset and the error didn't appeared. But the error occured in the other dataset with the same code for label conversion...

**Comment by Redaimao** [comment]
hi, does the problem solved? I also meet this problem when training using my data, but it occurs during a certain step. is it because the label error?

**Comment by lmybaobao** [comment]
No, I haven't solved. I don't know what go wrong. So, I changed to use another code and the same label. everything is working fine. 




------------------ 原始邮件 ------------------
发件人: "Redaimao"<notifications@github.com>; 
发送时间: 2019年9月4日(星期三) 上午10:15
收件人: "facebookresearch/maskrcnn-benchmark"<maskrcnn-benchmark@noreply.github.com>; 
抄送: "＼ 淰、笑 ｀"<893510630@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [facebookresearch/maskrcnn-benchmark] AssertionError:tensor([172.5300, 795.3013, 173.0343, 795.1953]) (#759)




hi, does the problem solved? I also meet this problem when training using my data, but it occurs during a certain step. is it because the label error?

**Comment by synsis** [comment]
@lmybaobao @ccxu @Redaimao Hi, guys, I meet the same problem today. I figure out the reason is  the bbox labels I loaded into the model is wrong, which means 'xmin > xmax and ymin > ymax'. It may caused by error labels of the data set. Also, it may caused by the processing of the image and labels, for example, when you rotate the image and the label, the label may let min and max values in wrong positions.

My problem may not be same as yours, but I hope it can give you some sprite.

**Comment by XYudong** [comment]
I got the same issue. According to `File "/home/lmy/mask_rcnn/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py", line 36, in project_masks_on_boxes
    cropped_mask = segmentation_mask.crop(**proposal**)`, it seems this comes from the model proposals, other than our data label error?
