### ISSUE TITLE
 can not debug on train_net?

### ISSUE THREAD

**Issue by xwjBupt** [facebookresearch/maskrcnn-benchmark#760]
## ❓ Questions and Help
hi,guys,when i use the debug model in pycharm to run train_net.py ,it show :
```
/home/xwj/anaconda3/envs/MR/bin/python /home/xwj/pycharm-pro/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 39343 --file /media/xwj/Programm/Python/maskrcnn-benchmark/tools/train_net.py
Traceback (most recent call last):
  File "/home/xwj/pycharm-pro/helpers/pydev/pydevd.py", line 40, in <module>
    from _pydevd_bundle.pydevd_trace_dispatch import trace_dispatch as _trace_dispatch, global_cache_skips, global_cache_frame_skips, show_tracing_warning
  File "/home/xwj/pycharm-pro/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch.py", line 53, in <module>
    from _pydevd_bundle.pydevd_cython_wrapper import trace_dispatch as _trace_dispatch, global_cache_skips, global_cache_frame_skips
  File "/home/xwj/pycharm-pro/helpers/pydev/_pydevd_bundle/pydevd_cython_wrapper.py", line 2, in <module>
    from _pydevd_bundle_ext.pydevd_cython import trace_dispatch, PyDBAdditionalThreadInfo, global_cache_skips, global_cache_frame_skips
  File "_pydevd_bundle/pydevd_cython.pyx", line 63, in init _pydevd_bundle.pydevd_cython
AttributeError: type object '_pydevd_bundle.pydevd_cython.PyDBAdditionalThreadI' has no attribute '__reduce_cython__'

```

what should i do ? thanks~~

**Comment by fmassa** [comment]
This probably happens because you are using multi-gpu. Try debugging in single GPU and it should work.

**Comment by wxfsd** [comment]
Hello, have you solved it? I also had this situation.
