### ISSUE TITLE
ImportError: cannot import name rnn_compat

### ISSUE THREAD

**Issue by jiaobingle** [facebookresearch/maskrcnn-benchmark#781]
## ❓ Questions and Help

when i run 'python webcam.py --min-image-size 300 MODEL.DEVICE cpu ', it shows:
Traceback (most recent call last):
  File "webcam.py", line 11, in <module>
    from predictor import COCODemo
  File "/home/workplace/maskrcnn-benchmark/demo/predictor.py", line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/make_layers.py", line 10, in <module>
    from maskrcnn_benchmark.layers import Conv2d
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 5, in <module>
    from apex import amp
  File "build/bdist.linux-x86_64/egg/apex/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/apex/amp/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/apex/amp/amp.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/apex/amp/rnn_compat.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/apex/amp/wrap.py", line 4, in <module>
ImportError: cannot import name rnn_compat
lele@jiaobingle:/home/workplace/maskrcnn-benchmark/demo$ sudo python webcam.py --min-image-size 300 MODEL.DEVICE cpu
Traceback (most recent call last):
  File "webcam.py", line 11, in <module>
    from predictor import COCODemo
  File "/home/workplace/maskrcnn-benchmark/demo/predictor.py", line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/modeling/make_layers.py", line 10, in <module>
    from maskrcnn_benchmark.layers import Conv2d
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/home/workplace/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 5, in <module>
    from apex import amp
  File "build/bdist.linux-x86_64/egg/apex/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/apex/amp/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/apex/amp/amp.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/apex/amp/rnn_compat.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/apex/amp/wrap.py", line 4, in <module>
ImportError: cannot import name rnn_compat

**Comment by jiaobingle** [comment]
i have solved this issue, with python3 (not python2). i think the reason it python3 is needed by apex.

**Comment by sunpeng981712364** [comment]
I used the python2, and meet the same bug.

**Comment by saadehmd** [comment]
I am having this same issue, tried both cuda-9.0 and cuda-10.0. both apex and masrrcnn-benchmark compile just fine. But when i run webcam.py and it tries to import some module from maskrcnn_benchmark like a conv2d layer module etc, the trace falls intro a series of ImportErrors all leading upto this 
ImportError: cannot import name rnn_compat

**Comment by saadehmd** [comment]
Is this project supposed to only work with python >= 3. Is there any issue on here, that confirms this ?
