### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'deprecated'

### ISSUE THREAD

**Issue by warpspeed6** [facebookresearch/maskrcnn-benchmark#8]
Installed everything as per INSTALL.md and on ubuntu 16.04, no CUDA and on a VM.
Any thoughts? :/
```
root@anshu-VirtualBox:~/github/maskrcnn-benchmark/demo# python webcam.py --min-image-size 300 MODEL.DEVICE cpu
Traceback (most recent call last):
  File "webcam.py", line 80, in <module>
    main()
  File "webcam.py", line 64, in main
    min_image_size=args.min_image_size,
  File "/root/github/maskrcnn-benchmark/demo/predictor.py", line 114, in __init__
    _ = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/root/github/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "/root/github/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 128, in _load_file
    cached_f = cache_url(f)
  File "/root/github/maskrcnn-benchmark/maskrcnn_benchmark/utils/model_zoo.py", line 44, in cache_url
    if not os.path.exists(cached_file) and is_main_process():
  File "/root/github/maskrcnn-benchmark/maskrcnn_benchmark/utils/comm.py", line 22, in is_main_process
    if not torch.distributed.deprecated.is_initialized():
AttributeError: module 'torch.distributed' has no attribute 'deprecated'

```

**Comment by soumith** [comment]
@warpspeed6 you must've installed pytorch stable. This is the part of INSTALL.md that you might've missed: 

```
# follow PyTorch installation in https://pytorch.org/get-started/locally/
# we give the instructions for CUDA 9.0
conda install pytorch-nightly -c pytorch
```

Alternatively, something is wrong in our instructions where your PyTorch is getting downgraded.

Can you give us two pieces of information:

1. The output of the following commands:

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

2. The output of `python -c "import torch; print(torch.__version__)"`

**Comment by warpspeed6** [comment]
That was the case. system had stable (from before) as well as nightly. All good. Thanks!:)

**Comment by sphinx-jiang** [comment]
Same Issue: AttributeError: module 'torch.distributed' has no attribute 'deprecated' 
Installed everything as per INSTALL.md on Mac OSX / CPU.
Any suggestion to run it on Mac OS? @warpspeed6 

(maskrcnn_benchmark) gift:maskrcnn-benchmark admin$ python collect_env.py 
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.10.1

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.12.1)
[pip3] numpydoc (0.6.0)
[pip3] torchvision (0.2.1)
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2018.0.3                      1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.0.6            py37hb8a8100_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.0.1            py37h5d10147_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] **pytorch-nightly**           1.0.0.dev20181210         py3.7_0    pytorch
[conda] **torch**                     1.0.0                     <pip>

(maskrcnn_benchmark) gift:maskrcnn-benchmark admin$ **python -c "import torch; print(torch.__version__)"**
**1.0.0**

**Comment by fmassa** [comment]
We have normally removed all instances of `torch.distributed.deprecated` from the codebase, so if you update `maskrcnn-benchmark` to latest version (via a `git pull origin master`), you'll probably not see this error anymore.

**Comment by TimZaman** [comment]
> We have normally removed all instances of torch.distributed.deprecated
On pytorch 1.0.0, python 3.7 through pip on mac osx, `dir(torch.distributed)` gives: (note the deprecated)

`['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'deprecated', 'is_available', 'torch']`

**Comment by jinfagang** [comment]
I still got this even pull from master:

```
    from apex.amp import float_function
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/apex-0.1-py3.5.egg/apex/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/apex-0.1-py3.5.egg/apex/parallel/__init__.py", line 8, in <module>
AttributeError: module 'torch.distributed' has no attribute 'deprecated'
```
