### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jiangkeng123** [facebookresearch/maskrcnn-benchmark#848]
## ❓ Questions and Help
Traceback (most recent call last):
  File "tools/train_net.py", line 186, in <module>
    main()
  File "tools/train_net.py", line 179, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 85, in train
    arguments,
  File "/home/jiang/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/jiang/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/jiang/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/jiang/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 108, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jiang/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 108, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jiang/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/jiang/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/coco.py", line 84, in __getitem__
    masks = SegmentationMask(masks, img.size, mode='poly')
  File "/home/jiang/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 471, in __init__
    self.instances = PolygonList(instances, size)
  File "/home/jiang/maskrcnn-benchmark/maskrcnn_benchmark/structures/segmentation_mask.py", line 348, in __init__
    assert isinstance(polygons[0][0], (list, tuple)), str(
IndexError: list index out of range

**Comment by LeviViana** [comment]
It looks like your annotations aren't in coco-style.

**Comment by LYH-YNU** [comment]
same problem

**Comment by hasayake007** [comment]
Have you solved it? I met the same question. It is the dataset problem?
