### ISSUE TITLE
Problems with Demo running

### ISSUE THREAD

**Issue by LinLene** [facebookresearch/maskrcnn-benchmark#85]
## ❓ Questions and Help
**Environment:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
cuda 9.0**

**After the installation followed by  the INSTALL.md, when running 'Inference in a few lines' step, I encounter the errors as following . Hoping get the instruction for solving it .** 

Traceback (most recent call last):
  File "../maskrnn/maskrcnn-benchmark-master/MyDemo/Inference.py", line 18, in <module>
    predictions = coco_demo.run_on_opencv_image(image)
  File "../maskrnn/maskrcnn-benchmark-master/demo/predictor.py", line 169, in run_on_opencv_image
    predictions = self.compute_prediction(image)
  File "../maskrnn/maskrcnn-benchmark-master/demo/predictor.py", line 193, in compute_prediction
    image = self.transforms(original_image)
  File "../python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/transforms.py", line 58, in __call__
  File "../python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/transforms.py", line 119, in __call__
  File "../python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/functional.py", line 109, in to_pil_image
TypeError: pic should be Tensor or ndarray. Got <class 'ellipsis'>.

**Comment by z785042003** [comment]
> ## question Questions and Help
> 
> **Environment: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609 cuda 9.0**
> 
> **After the installation followed by the INSTALL.md, when running 'Inference in a few lines' step, I encounter the errors as following . Hoping get the instruction for solving it .**
> 
> Traceback (most recent call last):
> File "../maskrnn/maskrcnn-benchmark-master/MyDemo/Inference.py", line 18, in
> predictions = coco_demo.run_on_opencv_image(image)
> File "../maskrnn/maskrcnn-benchmark-master/demo/predictor.py", line 169, in run_on_opencv_image
> predictions = self.compute_prediction(image)
> File "../maskrnn/maskrcnn-benchmark-master/demo/predictor.py", line 193, in compute_prediction
> image = self.transforms(original_image)
> File "../python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/transforms.py", line 58, in **call**
> File "../python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/transforms.py", line 119, in **call**
> File "../python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/functional.py", line 109, in to_pil_image
> TypeError: pic should be Tensor or ndarray. Got <class 'ellipsis'>.

Hi!  I have the same problem. Can you tell me how you solved this problem. Thank you in advance!

**Comment by fmassa** [comment]
opencv is returning an ellipsis instead of a np.array.
Check that you can read from your webcam, this should help you identify the issue

**Comment by z785042003** [comment]
Traceback (most recent call last):
  File "picture.py", line 18, in <module>
    predictions = coco_demo.run_on_opencv_image(image)
  File "/home/opex/maskrcnn-benchmark/demo/predictor.py", line 172, in run_on_opencv_image
    predictions = self.compute_prediction(image)
  File "/home/opex/maskrcnn-benchmark/demo/predictor.py", line 198, in compute_prediction
    image = self.transforms(original_image)
  File "/home/opex/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/transforms/transforms.py", line 60, in __call__
  File "/home/opex/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/transforms/transforms.py", line 126, in __call__
  File "/home/opex/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/transforms/functional.py", line 112, in to_pil_image
TypeError: pic should be Tensor or ndarray. Got <class 'str'>.

I would like to run  'inference in a few lines' on my own picture. I just changed `image = ("30.jpg")`. Then I got this error. I can run webcam exactly. Could you help me, I am a new of this. Thank you very much!

**Comment by fmassa** [comment]
You should pass a numpy array, not a string. Check https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/Mask_R-CNN_demo.ipynb for more details
