### ISSUE TITLE
ImportError: cannot import name 'functional'

### ISSUE THREAD

**Issue by xiaohao2907** [facebookresearch/maskrcnn-benchmark#850]
I have been looking for a long time on Google and issue and have not found the answer to my question. Does anyone know how to solve this problem? I will be very grateful. I configured it according to install.md. This is my environment version and error log.
Cuda 9.0
Ipython 6.1.0 py36_0,
Cudatoolkit 9.0 h8171c6c_0 seibert
Pytorch 0.1.12 py36_0
Torchvision 0.1.8 py36_0 ,
Apex==0.1
Error log:
(maskrcnn_benchmark) ronhau@ronhau-pc:~/maskrcnn-benchmark$ cd demo/
(maskrcnn_benchmark) ronhau@ronhau-pc:~/maskrcnn-benchmark/demo$ python webcam.py --min-image-size 800
Traceback (most recent call last):
   File "webcam.py", line 6, in <module>
     From predictor import COCODemo
   File "/home/ronhau/maskrcnn-benchmark/demo/predictor.py", line 5, in <module>
     From torchvision.transforms import functional as F
ImportError: cannot import name 'functional'

**Comment by pengyuan101** [comment]
hello,have you solved this problem? i have met the same problem

**Comment by allenwangcheng** [comment]
heool,i have also meet the same problem

**Comment by allenwangcheng** [comment]
I have solved this problem ,because i install torchvison by conda ,and then install it by build,so i think two version torchvison make the problem

**Comment by DLLXW** [comment]
I meet the same problem,I think it's the version of your torchvison,you can uninstall the old one,and the  
torchvison==0.2.2 can work well
