### ISSUE TITLE
Problem : GN dimension when evaluating mask_R_50_3x_gn

### ISSUE THREAD

**Issue by stigma0617** [facebookresearch/maskrcnn-benchmark#852]
## ❓ Questions and Help

When I trained and evaluate by using [scratch_e2e_mask_rcnn_R_50_FPN_Xconv1fc_3x_gn](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/gn_baselines/scratch_e2e_mask_rcnn_R_50_FPN_Xconv1fc_3x_gn.yaml), This problem occurred.

> 2019-06-03 17:19:46,170 maskrcnn_benchmark.inference INFO: Start evaluation on coco_2014_minival dataset(5000 images).
 30%|██████████████████████████████████████████████▏                                                                                                           | 1501/5000 [03:06<06:53,  8.47it/s]
Traceback (most recent call last):
  File "tools/test_net.py", line 107, in <module>
    main()
  File "tools/test_net.py", line 101, in main
    output_folder=output_folder,
  File "/home/lsrock1/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 84, in inference
    predictions = compute_on_dataset(model, data_loader, device, inference_timer)
  File "/home/lsrock1/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 30, in compute_on_dataset
    output = model(images.to(device))
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lsrock1/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lsrock1/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 39, in forward
    x, detections, loss_mask = self.mask(mask_features, detections, targets)
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lsrock1/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/mask_head.py", line 70, in forward
    x = self.feature_extractor(features, proposals)
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lsrock1/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/roi_mask_feature_extractors.py", line 63, in forward
    x = F.relu(getattr(self, layer_name)(x))
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/modules/normalization.py", line 232, in forward
    input, self.num_groups, self.weight, self.bias, self.eps)
  File "/home/lsrock1/anaconda3/envs/pytorch1.1/lib/python3.7/site-packages/torch/nn/functional.py", line 1736, in group_norm
    torch.backends.cudnn.enabled)
RuntimeError: cannot reshape tensor of 0 elements into shape [1, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by stigma0617** [comment]
@zimenglan-sysu-512 Do you have an idea this problem?

**Comment by zimenglan-sysu-512** [comment]
hi @stigma0617 
i guess the problem is caused by the empty boxes from box-head. so u need to deal with the case of empty boxes for mask-branch or keypoint-branch.
hope it can help u.

**Comment by stigma0617** [comment]
@zimenglan-sysu-512 thanks for your reply.

Have you experienced this problem when you test [it](https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/configs/gn_baselines#performance) ? 

I just trained and tested by using [this config file](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/configs/gn_baselines/scratch_e2e_mask_rcnn_R_50_FPN_Xconv1fc_3x_gn.yaml)

**Comment by zimenglan-sysu-512** [comment]
yet, i met this problem, and deal with empty bbox to fix it.

**Comment by stigma0617** [comment]
@zimenglan-sysu-512 Could you share your solution?
Since this is the problem many people faced, your solution will surely help us.

Thanks in advance.

**Comment by zimenglan-sysu-512** [comment]
hi @stigma0617 
i just simply do this to solve empty bbox for mask branch when inference in the forward func of the mask_head file
```
        if not self.training and features[0].shape[0] == 0:
            return None, proposals, {}
```
maybe u can add the empty mask to the proposals like this:
```
proposals.add_field("mask", empty_masks)
```
hope it can help u.

**Comment by stigma0617** [comment]
Hi @zimenglan-sysu-512

First of all, thanks for your reply.

I tried to modify `mask_head`file with your tips, but I failed to fix this problem.

Could you let me know your modified code details?

Thanks

**Comment by pkhigh** [comment]
@stigma0617 were you able to solve the issue with GN models ?
It seems to be working fine with BN models.

**Comment by stigma0617** [comment]
@pkhigh As you said, BN models are working fine. 

But, GN models still have this problem.

**Comment by pkhigh** [comment]
has anyone found a solution for this ? 
I don't think this is an issue of 0 bounding boxes detections. Because i set the threshold to 0 even then I got same error.

**Comment by ShihuaiXu** [comment]
Does someone slove this problem? I met the same problem

**Comment by VinACE** [comment]
> /home/madhevan/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py(28)forward()
-> x = self.avgpool(x)
(Pdb) x
tensor([], size=(0, 2048, 7, 7))
(Pdb) n
> /home/madhevan/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py(29)forward()
-> x = x.view(x.size(0), -1)
(Pdb) n
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
> /home/madhevan/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py(29)forward()
-> x = x.view(x.size(0), -1)

**Comment by VinACE** [comment]
I am also getting a similar error
