### ISSUE TITLE
Batch size > 1 error

### ISSUE THREAD

**Issue by shlokk** [facebookresearch/maskrcnn-benchmark#865]
When i'm increasing batch size to 2, I recive following error. 
python tools/train_net.py --config-file configs/pascal_voc/e2e_faster_rcnn_R_50_C4_1x_1_gpu_voc.yaml SOLVER.IMS_PER_BATCH 2
2019-06-05 19:59:39,495 maskrcnn_benchmark INFO: Using 1 GPUs
2019-06-05 19:59:39,495 maskrcnn_benchmark INFO: Namespace(config_file='configs/pascal_voc/e2e_faster_rcnn_R_50_C4_1x_1_gpu_voc.yaml', distributed=False, local_rank=0, opts=['SOLVER.IMS_PER_BATCH', '2'], skip_test=False)
2019-06-05 19:59:39,495 maskrcnn_benchmark INFO: Collecting env info (might take some time)
2019-06-05 19:59:45,227 maskrcnn_benchmark INFO:
PyTorch version: 1.1.0.dev20190430
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Quadro P6000
Nvidia driver version: 430.14
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[pip] torch==1.1.0.dev20190430
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl-service               1.1.2            py36he904b0f_5
[conda] mkl_fft                   1.0.6            py36hd81dba3_0
[conda] mkl_random                1.0.2            py36hd81dba3_0
[conda] pytorch                   1.0.1           py3.6_cuda9.0.176_cudnn7.4.2_2    pytorch
[conda] pytorch-nightly           1.1.0.dev20190430 py3.6_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] torch                     1.0.1.post2               <pip>
[conda] torchvision               0.2.2                      py_3    pytorch
        Pillow (5.3.0)
2019-06-05 19:59:45,228 maskrcnn_benchmark INFO: Loaded configuration file configs/pascal_voc/e2e_faster_rcnn_R_50_C4_1x_1_gpu_voc.yaml
2019-06-05 19:59:45,228 maskrcnn_benchmark INFO:
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
    ANCHOR_SIZES: (128, 256, 512)
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, )
  MAX_ITER: 70000
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1

2019-06-05 19:59:45,229 maskrcnn_benchmark INFO: Running with config:
AMP_VERBOSE: False
DATALOADER:
  ASPECT_RATIO_GROUPING: True
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 0
DATASETS:
  TEST: ('voc_2007_test',)
  TRAIN: ('voc_2007_train', 'voc_2007_val')
DTYPE: float32
INPUT:
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  HUE: 0.0
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (800,)
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1.0, 1.0, 1.0]
  SATURATION: 0.0
  TO_BGR255: True
MODEL:
  BACKBONE:
    CONV_BODY: R-50-C4
    FREEZE_CONV_BODY_AT: 2
    USE_GN: False
  CLS_AGNOSTIC_BBOX_REG: False
  DEVICE: cuda
  FBNET:
    ARCH: default
    ARCH_DEF:
    BN_TYPE: bn
    DET_HEAD_BLOCKS: []
    DET_HEAD_LAST_SCALE: 1.0
    DET_HEAD_STRIDE: 0
    DW_CONV_SKIP_BN: True
    DW_CONV_SKIP_RELU: True
    KPTS_HEAD_BLOCKS: []
    KPTS_HEAD_LAST_SCALE: 0.0
    KPTS_HEAD_STRIDE: 0
    MASK_HEAD_BLOCKS: []
    MASK_HEAD_LAST_SCALE: 0.0
    MASK_HEAD_STRIDE: 0
    RPN_BN_TYPE:
    RPN_HEAD_BLOCKS: 0
    SCALE_FACTOR: 1.0
    WIDTH_DIVISOR: 1
  FPN:
    USE_GN: False
    USE_RELU: False
  GROUP_NORM:
    DIM_PER_GP: -1
    EPSILON: 1e-05
    NUM_GROUPS: 32
  KEYPOINT_ON: False
  MASK_ON: False
  META_ARCHITECTURE: GeneralizedRCNN
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    DEFORMABLE_GROUPS: 1
    NUM_GROUPS: 1
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STAGE_WITH_DCN: (False, False, False, False)
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: True
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    WIDTH_PER_GROUP: 64
    WITH_MODULATED_DCN: False
  RETINANET:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDES: (8, 16, 32, 64, 128)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BBOX_REG_BETA: 0.11
    BBOX_REG_WEIGHT: 4.0
    BG_IOU_THRESHOLD: 0.4
    FG_IOU_THRESHOLD: 0.5
    INFERENCE_TH: 0.05
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
    NMS_TH: 0.4
    NUM_CLASSES: 81
    NUM_CONVS: 4
    OCTAVE: 2.0
    PRE_NMS_TOP_N: 1000
    PRIOR_PROB: 0.01
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: 0
    USE_C5: True
  RETINANET_ON: False
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 21
    NUM_STACKED_CONVS: 4
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    PREDICTOR: FastRCNNPredictor
    USE_GN: False
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    BG_IOU_THRESHOLD: 0.5
    DETECTIONS_PER_IMG: 100
    FG_IOU_THRESHOLD: 0.5
    NMS: 0.5
    POSITIVE_FRACTION: 0.25
    SCORE_THRESH: 0.05
    USE_FPN: False
  ROI_KEYPOINT_HEAD:
    CONV_LAYERS: (512, 512, 512, 512, 512, 512, 512, 512)
    FEATURE_EXTRACTOR: KeypointRCNNFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    PREDICTOR: KeypointRCNNPredictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: True
  ROI_MASK_HEAD:
    CONV_LAYERS: (256, 256, 256, 256)
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: (0.0625,)
    POSTPROCESS_MASKS: False
    POSTPROCESS_MASKS_THRESHOLD: 0.5
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: True
    USE_GN: False
  RPN:
    ANCHOR_SIZES: (128, 256, 512)
    ANCHOR_STRIDE: (16,)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_PER_BATCH: True
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 12000
    RPN_HEAD: SingleConvRPNHead
    STRADDLE_THRESH: 0
    USE_FPN: False
  RPN_ONLY: False
  WEIGHT:
OUTPUT_DIR:
PATHS_CATALOG: /vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 2500
  GAMMA: 0.1
  IMS_PER_BATCH: 2
  MAX_ITER: 70000
  MOMENTUM: 0.9
  STEPS: (50000,)
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
TEST:
  DETECTIONS_PER_IMG: 100
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  IMS_PER_BATCH: 1
Selected optimization level O0:  Pure FP32 training.

Defaults for this optimization level are:
enabled                : True
opt_level              : O0
cast_model_type        : torch.float32
patch_torch_functions  : False
keep_batchnorm_fp32    : None
master_weights         : False
loss_scale             : 1.0
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O0
cast_model_type        : torch.float32
patch_torch_functions  : False
keep_batchnorm_fp32    : None
master_weights         : False
loss_scale             : 1.0
2019-06-05 19:59:53,460 maskrcnn_benchmark.data.build WARNING: When using more than one image per GPU you may encounter an out-of-memory (OOM) error if your GPU does not have sufficient memory. If this happens, you can reduce SOLVER.IMS_PER_BATCH (for training) or TEST.IMS_PER_BATCH (for inference). For training, you must also adjust the learning rate and schedule length according to the linear scaling rule. See for example: https://github.com/facebookresearch/Detectron/blob/master/configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml#L14
2019-06-05 19:59:55,529 maskrcnn_benchmark.trainer INFO: Start training
1
torch.Size([2, 1024, 50, 76])
len of featrues in rpn head
1
shape of featrues in rpn head
torch.Size([2, 1024, 50, 76])
len of x in RPNhead
1
torch.Size([2, 1024, 50, 76])
in boxlist ops
(1204, 800) 1
(BoxList(num_boxes=1670, image_width=1204, image_height=800, mode=xyxy),)
in boxlist ops
(1204, 800) 1
(BoxList(num_boxes=1185, image_width=1204, image_height=800, mode=xyxy),)
shape of proposal in cat_boxlist
2
[BoxList(num_boxes=1670, image_width=1204, image_height=800, mode=xyxy), BoxList(num_boxes=1185, image_width=1204, image_height=800, mode=xyxy)]
shape of gt_box in cat_boxlist
2
[BoxList(num_boxes=1, image_width=1066, image_height=800, mode=xyxy), BoxList(num_boxes=1, image_width=1204, image_height=800, mode=xyxy)]
in boxlist ops
(1204, 800) 2
(BoxList(num_boxes=1670, image_width=1204, image_height=800, mode=xyxy), BoxList(num_boxes=1, image_width=1066, image_height=800, mode=xyxy))
Traceback (most recent call last):
  File "tools/train_net.py", line 247, in <module>
    main()
  File "tools/train_net.py", line 240, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 146, in train
    arguments,
  File "/vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 72, in do_train
    loss_dict = model(images.tensors, targets)
  File "/vulcan/scratch/shlok/Ana/envs/python_3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/vulcan/scratch/shlok/Ana/envs/python_3.6/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/amp/_initialize.py", line 194, in new_fwd
    **applier(kwargs, input_caster))
  File "/vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 62, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/vulcan/scratch/shlok/Ana/envs/python_3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 167, in forward
    return self._forward_train(anchors, objectness, rpn_box_regression, targets)
  File "/vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 183, in _forward_train
    anchors, objectness, rpn_box_regression, targets
  File "/vulcan/scratch/shlok/Ana/envs/python_3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 157, in forward
    boxlists = self.add_gt_proposals(boxlists, targets)
  File "/vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 78, in add_gt_proposals
    for proposal, gt_box in zip(proposals, gt_boxes)
  File "/vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 78, in <listcomp>
    for proposal, gt_box in zip(proposals, gt_boxes)
  File "/vulcan/scratch/shlok/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 117, in cat_boxlist
    assert all(bbox.size == size for bbox in bboxes)
AssertionError and Help

**Comment by tangze5258** [comment]
hi,bro, do u konw how to modify these parameters MIN_SIZE_TRAIN, MAX_SIZE_TRAIN, if my custom imgs shape larger than 1333*800?

**Comment by jasonRichter** [comment]
@shlokk were you ever able to solve this error?  I am seeing the exact same error and I am stumped.
