### ISSUE TITLE
ZeroDivisionError: float division by zero during training

### ISSUE THREAD

**Issue by 3xqygd** [facebookresearch/maskrcnn-benchmark#873]
rom layer4.2.conv3.weight        of shape (2048, 512, 1, 1)
Traceback (most recent call last):
  File "tools/train_net.py", line 186, in <module>
    main()
  File "tools/train_net.py", line 179, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 72, in train
    start_iter=arguments["iteration"],
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\data\build.py", line 160, in make_data_loader
    dataset, sampler, aspect_grouping, images_per_gpu, num_iters, start_iter
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\data\build.py", line 91, in make_batch_data_sampler
    aspect_ratios = _compute_aspect_ratios(dataset)
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\data\build.py", line 80, in _compute_aspect_ratios
    aspect_ratio = float(img_info["height"]) / float(img_info["width"])
ZeroDivisionError: float division by zero

The aspect ratio calculation error, 
when I set DATALOADER.ASPECT_RATIO_GROUPING to false, ratios = tuple(float(s) / float(s_orig) again shows the calculation error ZeroDivisionError. But I checked the data set without problems, and used this data set Training on other programs, no errors.

2019-06-10 11:45:24,019 maskrcnn_benchmark.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 186, in <module>
    main()
  File "tools/train_net.py", line 179, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 85, in train
    arguments,
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\engine\trainer.py", line 57, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "P:\study file\Anaconda3\envs\torch1.0\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "P:\study file\Anaconda3\envs\torch1.0\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ZeroDivisionError: Traceback (most recent call last):
  File "P:\study file\Anaconda3\envs\torch1.0\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "P:\study file\Anaconda3\envs\torch1.0\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "P:\study file\Anaconda3\envs\torch1.0\lib\site-packages\torch\utils\data\dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\data\datasets\voc.py", line 74, in __getitem__
    img, target = self.transforms(img, target)
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\data\transforms\transforms.py", line 15, in __call__
    image, target = t(image, target)
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\data\transforms\transforms.py", line 60, in __call__
    target = target.resize(image.size)
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\structures\bounding_box.py", line 99, in resize
    ratios = tuple(float(s) / float(s_orig) for s, s_orig in zip(size, self.size))
  File "f:\maskrcnn-benchmark\maskrcnn_benchmark\structures\bounding_box.py", line 99, in <genexpr>
    ratios = tuple(float(s) / float(s_orig) for s, s_orig in zip(size, self.size))
ZeroDivisionError: float division by zero

**Comment by 3xqygd** [comment]
The xml is Annotated incorrectly because the value of ‘size’ is 0.

**Comment by zlyx525** [comment]
Yes, this is a problem of annotations. There are some invalid annotations because the height or the width of the bounding box is 0.

**Comment by zlyx525** [comment]
How do you filter these invalid annotations ?  @3xqygd
