### ISSUE TITLE
ImportError: cannot import name 'save_config'

### ISSUE THREAD

**Issue by JSharp4273** [facebookresearch/maskrcnn-benchmark#886]
## ❓ Questions and Help
Hello

I would like to a multigpu training.
I check if my version of pytorch supported the multigpu training thanks to the command:
`torch.distributed.is_available()`
Its the case.
But when I try:
` python -m torch.distributed.launch --nproc_per_node=2 tools/train_net.py --config-file "configs/dcn/e2e_mask_rcnn_dconv_R_50_FPN_1x.yaml"
`
I receive the following error:
```
Traceback (most recent call last):
  File "tools/train_net.py", line 26, in <module>
    from maskrcnn_benchmark.utils.miscellaneous import mkdir, save_config
ImportError: cannot import name 'save_config'
```

The thing is I arrive to call `save_config` from the interpreter.
Any idea how I could make it works for multi-gpu.

**Comment by miguelvr** [comment]
can you re-install the `maskrcnn-benchmark` package and install it with `python setup.py develop`, then try again?

**Comment by wrs777** [comment]
> ## ❓ Questions and Help
> Hello
> 
> I would like to a multigpu training.
> I check if my version of pytorch supported the multigpu training thanks to the command:
> `torch.distributed.is_available()`
> Its the case.
> But when I try:
> `python -m torch.distributed.launch --nproc_per_node=2 tools/train_net.py --config-file "configs/dcn/e2e_mask_rcnn_dconv_R_50_FPN_1x.yaml"`
> I receive the following error:
> 
> ```
> Traceback (most recent call last):
>   File "tools/train_net.py", line 26, in <module>
>     from maskrcnn_benchmark.utils.miscellaneous import mkdir, save_config
> ImportError: cannot import name 'save_config'
> ```
> 
> The thing is I arrive to call `save_config` from the interpreter.
> Any idea how I could make it works for multi-gpu.

I encountered the same problem with you. Have you solved it?

**Comment by wykhan** [comment]
I have the same problem

**Comment by JSharp4273** [comment]
Sorry for the delay.
Actually I did not have fix that issue.
I moved forward, I should soon go back to that topic, If I find anything I will inform you.

**Comment by ahsan44411** [comment]
Has anyone solved this problem? I check online this kind of error shows when there is a circular dependency.

**Comment by bbrookie** [comment]
> Sorry for the delay.
> Actually I did not have fix that issue.
> I moved forward, I should soon go back to that topic, If I find anything I will inform you.

Do you have a solution to this problem now?

**Comment by ShaneYS** [comment]
any solution?
I encountered this problem when I train a model with terminal command, but it's ok with pycharm.

**Comment by jaemin93** [comment]
I know why this problem occurred.
install seems to be working, but it is not.
Make sure to place the maskrcnn packages properly in your Python environment.

1. Install
`$ python setup.py build develop`

2. Find maskrcnn packages location
`$ find / -name 'miscellaneous.py'`
```
/root/maskrcnn-benchmark/build/lib.linux-x86_64-3.6/maskrcnn_benchmark/utils/miscellaneous.py
/root/maskrcnn-benchmark/maskrcnn_benchmark/utils/miscellaneous.py
/opt/conda/lib/python3.6/site-packages/maskrcnn_benchmark/utils/miscellaneous.py
/opt/pytorch/examples/maskrcnn/pytorch/maskrcnn_benchmark/utils/miscellaneous.py
/workspace/examples/maskrcnn/pytorch/maskrcnn_benchmark/utils/miscellaneous.py
```

3. Remove and Copy
```
$ rm -rf /opt/conda/lib/python3.6/site-packages/maskrcnn_benchmark
$ cp -r maskrcnn-benchmark/build/lib.linux-x86_64-3.6/maskrcnn_benchmark /opt/conda/lib/python3.6/site-packages/
```

It worked in my case.

**Comment by wanghao14** [comment]
@jaemin93 Thanks a lot! Your solution works for me, too.
