### ISSUE TITLE
bounding_box

### ISSUE THREAD

**Issue by abcxs** [facebookresearch/maskrcnn-benchmark#892]
I just add one line behind the [bbox = BoxList([[0, 0, 10, 10], [0, 0, 5, 5]], (10, 10))], and the line is print(bbox[0])
The result is not my expected result, because of __getitem__ function

the output error is :
Traceback (most recent call last):
  File "/data/zfp/test/test.py", line 260, in <module>
    print(bbox[0])
  File "/data/zfp/test/test.py", line 206, in __getitem__
    bbox = BoxList(self.bbox[item], self.size, self.mode)
  File "/data/zfp/test/test.py", line 24, in __init__
    "bbox should have 2 dimensions, got {}".format(bbox.ndimension())
ValueError: bbox should have 2 dimensions, got 1

I think the bbox is 2 dims, so bbox[0] wiil return 1 dim, so got the error
If i'm wrong, i'm sorry and please tell me.

**Comment by buxpeng** [comment]
hi.I also encountered this problem, did you solve it?Can you tell me if it is solved? Thank you

**Comment by abcxs** [comment]
In general, this does not affect the use.
If you want to print bbox[0], you can change it to bbox[[0]]

**Comment by buxpeng** [comment]
I look at the code written by others, but I run it wrong. Can you help me see how to modify it? I want to extract the features of fc. output is  BoxList(num_boxes=100, image_width=800, image_height=848, mode=xyxy)
![image](https://user-images.githubusercontent.com/53242456/75766340-f9b57200-5d7b-11ea-9520-f8f4b2153e8c.png)

**Comment by abcxs** [comment]
These should be based on how you wrote it up.
