### ISSUE TITLE
cannot import name 'cv2_util'

### ISSUE THREAD

**Issue by miao728808470** [facebookresearch/maskrcnn-benchmark#898]
(maskrcnn_benchmark) mxy@4055:~/maskscoring_rcnn$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 29, in <module>
    from predictor import COCODemo
  File "/home/mxy/maskscoring_rcnn/predictor.py", line 11, in <module>
    from maskrcnn_benchmark.utils import cv2_util
ImportError: cannot import name 'cv2_util' from 'maskrcnn_benchmark.utils' (/home/mxy/maskscoring_rcnn/maskrcnn_benchmark/utils/__init__.py)

how to solve it?

**Comment by amy-98** [comment]
Hi there, I'm having the same issue. cv2_util is in the utils folder but it is not importing. Any help would be appreciated.

**Comment by wenhwu** [comment]
I met the same problem and solved it. may be because the old version of maskrcnn_benchmark you used is missing `cv2_util. py`in the folder of `utils`, but the latest version of maskrcnn_benchmark has `cv2_util.py`. so,move the `cv2_util. py` into `utils`. hope it helps
