### ISSUE TITLE
Docker Install error

### ISSUE THREAD

**Issue by ipa-mah** [facebookresearch/maskrcnn-benchmark#901]
I try to build the maskrcnn-benchmark using Docker and got the error:
```
Step 14/23 : RUN pip install requests ninja yacs cython matplotlib opencv-python tqdm
 ---> Running in ea049575a15c
Collecting requests
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
Collecting ninja
  Downloading https://files.pythonhosted.org/packages/cc/bf/32e5dd5cce6543374e4050a7292099402ab80787eddf3732810a55b37763/ninja-1.9.0.post1-py3-none-manylinux1_x86_64.whl (98kB)
Collecting yacs
  Downloading https://files.pythonhosted.org/packages/2f/51/9d613d67a8561a0cdf696c3909870f157ed85617fea3cff769bb7de09ef7/yacs-0.1.6-py3-none-any.whl
Collecting cython
  Downloading https://files.pythonhosted.org/packages/5d/7e/d2a81d821193c88113e3613f2df456a4d7b1b15bd4551e97978e8107e3ef/Cython-0.29.10-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
Collecting matplotlib
  Downloading https://files.pythonhosted.org/packages/da/83/d989ee20c78117c737ab40e0318ea221f1aed4e3f5a40b4f93541b369b93/matplotlib-3.1.0-cp36-cp36m-manylinux1_x86_64.whl (13.1MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/miniconda/envs/py36/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/miniconda/envs/py36/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/miniconda/envs/py36/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/miniconda/envs/py36/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/miniconda/envs/py36/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/miniconda/envs/py36/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/download.py", line 886, in unpack_url
    progress_bar=progress_bar
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/download.py", line 746, in unpack_http_url
    progress_bar)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/download.py", line 954, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/download.py", line 683, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/download.py", line 651, in written_chunks
    for chunk in chunks:
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 156, in iter
    for x in it:
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_internal/download.py", line 640, in resp_read
    decode_content=False):
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/miniconda/envs/py36/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
The command '/bin/sh -c pip install requests ninja yacs cython matplotlib opencv-python tqdm' returned a non-zero code: 2

```
Do you have any idea how this happened?
Thanks

**Comment by keineahnung2345** [comment]
Maybe this could help you: https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port.

**Comment by ipa-mah** [comment]
The problem is solved. It was internet connection issue as I guess.
