### ISSUE TITLE
Error when training custom dataset

### ISSUE THREAD

**Issue by fuzzyBatman** [facebookresearch/maskrcnn-benchmark#919]
## ❓ Questions and Help

Installed maskrcnn_benchmark successfully on
- GCP VM running Debian9
- nVidia Tesla P100
- CUDA 10.0

When I run the commands to train I get

```
Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.engine.trainer import do_train
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 60
    logger.error(f"Iteration={iteration + 1} || Image Ids used for training {_} || targets Length={[len(target) for target in targets]}")
                                                                                                                                       ^
SyntaxError: invalid syntax
```

and at other times

```
Traceback (most recent call last):
  File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.engine.trainer import do_train
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 60
    logger.error(f"Iteration={iteration + 1} || Image Ids used for training {_} || targets Length={[len(target) for target in targets]}")
                                                                                                                                       ^
SyntaxError: invalid syntax
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7ff628252378>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

**Comment by fuzzyBatman** [comment]
Commented out the line and it works.

**Comment by samson-wang** [comment]
```f"Iteration={iteration + 1} || Image Ids used for training {_} || targets Length={[len(target) for target in targets]}"```

It's a new feature in python3.6. https://www.python.org/dev/peps/pep-0498/

**Comment by fuzzyBatman** [comment]
Ah. I am using Python 3.7

**Comment by VinACE** [comment]
make sure the image, the json file for augmentation are read properly
