### ISSUE TITLE
Export Faster R-CNN to ONNX

### ISSUE THREAD

**Issue by fuzzyBatman** [facebookresearch/maskrcnn-benchmark#922]
## ❓ Questions and Help

Is there support for exporting Faster R-CNN models to ONNX?
The ONNX/models repo contains [a model](https://github.com/onnx/models/tree/master/faster_rcnn) from this repo.

I am trying to export a single class detection model trained on a custom dataset.

**Comment by fuzzyBatman** [comment]
I tried the export code from [this](https://pytorch.org/docs/stable/onnx.html) and [this](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchTensorflowMnist.ipynb) by integrating it to a new method called `export_to_onnx` in the COCODemo class, which always results in a RuntimeError of the form

```
C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\tensor.py:435: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)

c:\Users\saaty\Workspace\src\maskrcnn-benchmark\maskrcnn_benchmark\structures\bounding_box.py:21: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use
this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  bbox = torch.as_tensor(bbox, dtype=torch.float32, device=device)

c:\Users\saaty\Workspace\src\maskrcnn-benchmark\maskrcnn_benchmark\structures\bounding_box.py:26: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of
Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bbox.size(-1) != 4:

Traceback (most recent call last):
  File "c:/Users/saaty/Workspace/src/maskrcnn-benchmark/infer.py", line 24, in <module>
    rbc_demo.export_to_onnx()
  File "c:\Users\saaty\Workspace\src\maskrcnn-benchmark\demo\predictor.py", line 59, in export_to_onnx
    torch.onnx.export(self.model.cuda(), dummy_input, "frcnn_rbc.onnx", verbose=True)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\onnx\__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\onnx\utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\onnx\utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\onnx\utils.py", line 266, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\onnx\utils.py", line 225, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\jit\__init__.py", line 231, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\jit\__init__.py", line 294, in forward
    out = self.inner(*trace_inputs)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\nn\modules\module.py", line 481, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "c:\Users\saaty\Workspace\src\maskrcnn-benchmark\maskrcnn_benchmark\modeling\detector\generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\nn\modules\module.py", line 481, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "c:\Users\saaty\Workspace\src\maskrcnn-benchmark\maskrcnn_benchmark\modeling\rpn\rpn.py", line 156, in forward
    anchors = self.anchor_generator(images, features)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\Users\saaty\scoop\apps\python\current\lib\site-packages\torch\nn\modules\module.py", line 481, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "c:\Users\saaty\Workspace\src\maskrcnn-benchmark\maskrcnn_benchmark\modeling\rpn\anchor_generator.py", line 122, in forward
    self.add_visibility_to(boxlist)
  File "c:\Users\saaty\Workspace\src\maskrcnn-benchmark\maskrcnn_benchmark\modeling\rpn\anchor_generator.py", line 105, in add_visibility_to
    & (anchors[..., 3] < image_height + self.straddle_thresh)
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'
```

**Comment by iceflame89** [comment]
Look this:
https://github.com/BowenBao/maskrcnn-benchmark/tree/onnx_stage

**Comment by fuzzyBatman** [comment]
@iceflame89 
Interesting. Thank you!
So it is necessary to train using the caffe2 configs?

**Comment by fuzzyBatman** [comment]
Unable to make this (caffe2Detectron) config work with custom number of classes. The weights require NUM_CLASSES to be set to 81.

**Comment by fuzzyBatman** [comment]
@iceflame89 Have you used this branch?
When I run `python3 demo/export_to_onnx.py` I get

```
Traceback (most recent call last):
  File "demo/export_to_onnx.py", line 17, in <module>
    import pytorch_export_patch
  File "/home/jupyter/src/maskrcnn-benchmark/demo/pytorch_export_patch.py", line 245, in <module>
    register_custom_op()
  File "/home/jupyter/src/maskrcnn-benchmark/demo/pytorch_export_patch.py", line 241, in register_custom_op
    from torch.onnx import register_custom_op_symbolic
ImportError: cannot import name 'register_custom_op_symbolic'
```

**Comment by fuzzyBatman** [comment]
> ImportError: cannot import name 'register_custom_op_symbolic'

Fixed this. Make sure you install pytorch and then pytorch-nightly.

Now I get

```
Traceback (most recent call last):
  File "demo/export_to_onnx.py", line 14, in <module>
    from predictor import COCODemo
  File "/home/jupyter/src/maskrcnn-benchmark/demo/predictor.py", line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 10, in <module>
    from ..backbone import build_backbone
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/modeling/make_layers.py", line 10, in <module>
    from maskrcnn_benchmark.layers import Conv2d
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .nms import nms
  File "/home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: /home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Device8validateEv
```

**Comment by fuzzyBatman** [comment]
> ImportError: /home/jupyter/src/maskrcnn-benchmark/maskrcnn_benchmark/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Device8validateEv

Fixed using a reinstall

**Comment by fuzzyBatman** [comment]
The branch works. Thank you so much!

**Comment by fuzzyBatman** [comment]
@iceflame89 Do you know if there is support for exporting Mask R-CNN to ONNX?

**Comment by haochange** [comment]
when converting：

maskrcnn_benchmark/modeling/rpn/inference.py:213: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  objectness, post_nms_top_n, dim=0, sorted=True
/maskrcnn_benchmark/modeling/poolers.py:72: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  target_lvls = torch.floor(self.lvl0 + torch.log2(torch.tensor(self.eps, dtype=torch.float32) + s / self.s0))
/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py:96: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  boxes_per_image = [len(box) for box in boxes]
/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py:162: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for j in range(1, num_classes):
maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py:70: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  (torch.tensor([self.detections_per_img], dtype=torch.long),
/maskrcnn_benchmark/modeling/roi_heads/box_head/inference.py:74: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  scores, number_to_keep, dim=0, sorted=True)
/python3.6/site-packages/torch/onnx/symbolic_helper.py:194: UserWarning: ONNX export failed on Sort because Cannot sort in ascending order not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
graph(%image : Float(3, 960, 1280),
      %2733 : Long(1),
      %2734 : Long(1),
      %2735 : Long(1),
      %2736 : Long(1),
      %2737 : Long(1),
      %2738 : Long(1),
      %2739 : Long(1),
      %2740 : Long(1),
      %2741 : Long(1),
      %2742 : Long(1),

**Comment by clw5180** [comment]
> @iceflame89
> Interesting. Thank you!
> So it is necessary to train using the caffe2 configs?

Same problem! Do you use the caffe2 configs to solve this problem? Thanks a lot !!

**Comment by adizhol** [comment]
has anyone tried exporting DeformConvFunction layer (dcn) to onnx?
