### ISSUE TITLE
Dataset Index Error

### ISSUE THREAD

**Issue by M-Alami** [facebookresearch/maskrcnn-benchmark#926]
Hi ! 

I tried to train the model on Coco using this command:
python /path_to_maskrcnn_benchmark/tools/train_net.py --config-file "/path/to/config/file.yaml"

It results on the following error.
Traceback (most recent call last):
  File "train_net.py", line 191, in <module>
    main()
  File "train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "train_net.py", line 72, in train
    start_iter=arguments["iteration"],
  File "/home/malamich/maskrcnn-benchmark-master/maskrcnn_benchmark/data/build.py", line 157, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
  File "/home/malamich/maskrcnn-benchmark-master/maskrcnn_benchmark/data/build.py", line 53, in build_dataset
    dataset = datasets[0]
IndexError: list index out of range

When trying to investigate, it appears that dataset_list comes from this line in build.py:
 dataset_list = cfg.DATASETS.TRAIN if is_train else cfg.DATASETS.TEST

However in cfg (defaults.py), we have: _C.DATASETS.TRAIN = ()
Therefore the error seems logical. But How is this supposed to work.

Thanks for your help.

**Comment by M-Alami** [comment]
Update: i had to set Datasetlist to dataset_list=['coco_2017_train'] manually to make it work. If anyone knows how to make it work without this, your help is welcome.

Thanks
