### ISSUE TITLE
Errer After "Loading and preparing results..." 

### ISSUE THREAD

**Issue by hgsyo76** [facebookresearch/maskrcnn-benchmark#95]
## ❓ Questions and Help
I try train_net.py with COCO datasets according to the README.
After "Loading and preparing results...", it has errer as below.
Do you have idea about it ?
So I'm sorry if I asked questions about strange things.....
Thank you for in advance.

Loading and preparing results...
Traceback (most recent call last):
  File "tools/train_net.py", line 170, in <module>
    main()
  File "tools/train_net.py", line 166, in main
    test(cfg, model, args.distributed)
  File "tools/train_net.py", line 103, in test
    output_folder=output_folder,
  File "/home/ikedalab/Documents/pytorch/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 422, in inference
    dataset.coco, coco_results[iou_type], file_path, iou_type
  File "/home/ikedalab/Documents/pytorch/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 251, in evaluate_predictions_on_coco
    coco_dt = coco_gt.loadRes(str(json_result_file))
  File "/home/ikedalab/anaconda3/envs/maskrcnn/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 318, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by fmassa** [comment]
Something went wrong with you COCO dataset, as the `anns` object is empty.

Also, your training seems to have jumped directly to testing?

**Comment by TigertigerTigertiger** [comment]
I have the same issue! Can you tell me how much are the adjusted STEPS and MAX_ITER ? And why does it work? Thanks in advance! @hgsyo76
