### ISSUE TITLE
Keypoints with FBNet backbone error

### ISSUE THREAD

**Issue by TamirBaidasov** [facebookresearch/maskrcnn-benchmark#960]
## 🐛 Bug

Hi everyone, I encountered a bug where I get errors while trying to run training script with fbnet backbone for keypoint detection.

Following errors occur:

```
maskrcnn_benchmark.trainer INFO: Start training
/opt/conda/conda-bld/pytorch-nightly_1556168745906/work/aten/src/THCUNN/ClassNLLCriterion.cu:105
: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [5,0,0]
Assertion `t >= 0 && t < n_classes` failed.

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch-nightly_1556168745906/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu line=110 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/132/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/132/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user/maskrcnn-benchmark/tools/train_net.py", line 190, in <module>
    main()
  File "/home/user/maskrcnn-benchmark/tools/train_net.py", line 183, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "/home/user/maskrcnn-benchmark/tools/train_net.py", line 88, in train
    arguments,
  File "/home/user/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 85, in do_train
    loss_dict = model(images, targets)
  File "/home/user/anaconda3/envs/tf_python_37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/tf_python_37/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/amp/_initialize.py", line 193, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/user/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 52, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/home/user/anaconda3/envs/tf_python_37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 53, in forward
    x, detections, loss_keypoint = self.keypoint(keypoint_features, detections, targets)
  File "/home/user/anaconda3/envs/tf_python_37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/keypoint_head/keypoint_head.py", line 45, in forward
    loss_kp = self.loss_evaluator(proposals, kp_logits)
  File "/home/user/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/keypoint_head/loss.py", line 168, in __call__
    keypoint_loss = F.cross_entropy(keypoint_logits[valid], keypoint_targets[valid])
  File "/home/user/anaconda3/envs/tf_python_37/lib/python3.7/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/user/anaconda3/envs/tf_python_37/lib/python3.7/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-
bld/pytorch-nightly_1556168745906/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110
```

## To Reproduce

1.Run training with the following script:
```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    CONV_BODY: FBNet
  FBNET:
    ARCH: "default"
    BN_TYPE: "bn"
    WIDTH_DIVISOR: 8
    DW_CONV_SKIP_BN: True
    DW_CONV_SKIP_RELU: True
  RPN:
    ANCHOR_SIZES: (16, 32, 64, 128, 256)
    ANCHOR_STRIDE: (16, )
    BATCH_SIZE_PER_IMAGE: 256
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 100
    RPN_HEAD: FBNet.rpn_head
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 6
    FEATURE_EXTRACTOR: FBNet.roi_head
    NUM_CLASSES: 2
  ROI_KEYPOINT_HEAD:
    FEATURE_EXTRACTOR: FBNet.roi_head_keypoints
    NUM_CLASSES: 17
    SHARE_BOX_FEATURE_EXTRACTOR: False
  KEYPOINT_ON: True
DATASETS:
  TRAIN: ("keypoints_coco_2014_train", "keypoints_coco_2014_valminusminival",)
  TEST: ("keypoints_coco_2014_minival",)
SOLVER:
  BASE_LR: 0.0025
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
  IMS_PER_BATCH: 4
# TEST:
#   IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (320, )
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 640
  PIXEL_MEAN: [103.53, 116.28, 123.675]
  PIXEL_STD: [57.375, 57.12, 58.395]
```

## Environment
```
Collecting environment information...
PyTorch version: 1.1.0.dev20190425
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0.dev20190425
[pip] torchvision-nightly==0.2.3
[conda] mkl                       2019.3                      199
[conda] mkl_fft                   1.0.13           py37h516909a_1    conda-forge
[conda] mkl_random                1.0.4            py37hf2d7682_0    conda-forge
[conda] pytorch-nightly           1.1.0.dev20190425 py3.7_cuda10.0.130_cudnn7.4.2_0    pytorch
[conda] torchvision-nightly       0.2.3                    pypi_0    pypi
```

## Additional context

I can train faster rcnn fbnet config and keypoint rcnn with resnet-50-fpn backbone with no problems.

From what I understand so far, in  "/home/user/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/keypoint_head/loss.py", line 153, in `__call__` heatmaps are being generated with values already bigger, than the keypoint_logits[n] size we get in line 166 which causes this error.

Did anyone succeed in training keypoint RCNN with fbnet backbone? Maybe I am doing something completely wrong here.

**Comment by jiangwqcooler** [comment]
You can try add ‘RESOLUTION’ size：
ROI_KEYPOINT_HEAD:
    RESOLUTION: 12

**Comment by mathpopo** [comment]
> cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-
> bld/pytorch-nightly_1556168745906/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110

i check this issue ,loss in keypint is error,so total loss cannot computer

Do you solve it ?

**Comment by mathpopo** [comment]
class KeypointRCNNPredictor(nn.Module) donot support the fbnet.keypoint prediction
mask have another predict api
