### ISSUE TITLE
AttributeError: STAGE_WITH_DCN

### ISSUE THREAD

**Issue by YuhanLiu11** [facebookresearch/maskrcnn-benchmark#968]
## ❓ Questions and Help
Hi!
I was able to train the model with customized datasets but recently when I tried to train the model with pretrained Mask RCNN Res101 weights with last layers deleted, the error "Traceback (most recent call last):
  File "tools/train_net.py", line 179, in <module>
    main()
  File "tools/train_net.py", line 172, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 35, in train
    model = build_detection_model(cfg)
  File "/srv/home/yliu/newMask/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py", line 10, in build_detection_model
    return meta_arch(cfg)
  File "/srv/home/yliu/newMask/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 29, in __init__
    self.backbone = build_backbone(cfg)
  File "/srv/home/yliu/newMask/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/backbone.py", line 79, in build_backbone
    return registry.BACKBONES[cfg.MODEL.BACKBONE.CONV_BODY](cfg)
  File "/srv/home/yliu/newMask/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/backbone.py", line 27, in build_resnet_fpn_backbone
    body = resnet.ResNet(cfg)
  File "/srv/home/yliu/newMask/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/resnet.py", line 110, in __init__
    stage_with_dcn = cfg.MODEL.RESNETS.STAGE_WITH_DCN[stage_spec.index -1]
  File "/srv/home/yliu/anaconda3/envs/mask/lib/python3.6/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: STAGE_WITH_DCN" occurs. 
Any ideas on what's the problem?

Thanks a lot for your help!

**Comment by yx3266** [comment]
Hello, do you know how to solve the error? I have the same problem.

**Comment by yx3266** [comment]
@YuhanLiu11

**Comment by Ericwyl** [comment]
I have the same problem.
