### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by github14343** [facebookresearch/maskrcnn-benchmark#986]
## ❓ Questions and Help
When I run the demo  webcam.py ,I got the problem:
(maskrcnn_benchmark) txl@txl-ThinkCentre:~/maskrcnn-benchmark/demo$ python webcam.py
Traceback (most recent call last):
  File "webcam.py", line 80, in <module>
    main()
  File "webcam.py", line 64, in main
    min_image_size=args.min_image_size,
  File "/home/txl/maskrcnn-benchmark/demo/predictor.py", line 143, in __init__
    self.model.to(self.device)
  File "/home/txl/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/txl/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/txl/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/txl/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/txl/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/txl/anaconda2/envs/maskrcnn_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: unknown error

And I don't know what's wrong, could someone help me?

My environment:
Ubuntu 16.04
cuda: 9.0.176
drive:384.130
pytorch:1.1.0
gcc:5.4.0
Python 3.6.7

**Comment by yx3266** [comment]
Hello, @github14343. Do you know how to solve the error? I've met the same problem. Thank you.
