### ISSUE TITLE
Runtime Error, Tensor size problem

### ISSUE THREAD

**Issue by SeanZChen** [facebookresearch/maskrcnn-benchmark#997]
## To Reproduce

I installed according to install.md, but when I try to train e2e_faster _rcnn, I encounterd following problem: 
RuntimeError: The size of tensor a (167) must match the size of tensor b (168) at non-singleton dimension 3

Command:  python tools/train_net.py --config-file 'configs/e2e_faster_rcnn_R_50_FPN_1x.yaml'

Full Error Report:

2019-07-26 10:57:30,920 maskrcnn_benchmark.utils.miscellaneous WARNING: Dataset [ConcatDataset] has no categories attribute, labels.json file won't be created
2019-07-26 10:57:31,191 maskrcnn_benchmark.trainer INFO: Start training
/home/chenzixuan/anaconda3/envs/chenzixuan/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "tools/train_net.py", line 191, in <module>
    main()
  File "tools/train_net.py", line 184, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 85, in train
    arguments,
  File "/home/chenzixuan/detection/maskrcnn-benchmark/maskrcnn_benchmark/engine/trainer.py", line 71, in do_train
    loss_dict = model(images, targets)
  File "/home/chenzixuan/anaconda3/envs/chenzixuan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenzixuan/anaconda3/envs/chenzixuan/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/amp/_initialize.py", line 204, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/chenzixuan/detection/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 49, in forward
    features = self.backbone(images.tensors)
  File "/home/chenzixuan/anaconda3/envs/chenzixuan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenzixuan/anaconda3/envs/chenzixuan/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/chenzixuan/anaconda3/envs/chenzixuan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenzixuan/detection/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/fpn.py", line 64, in forward
    last_inner = inner_lateral + inner_top_down
RuntimeError: The size of tensor a (167) must match the size of tensor b (168) at non-singleton dimension 3

I've modified the config file to make it run on a single GPU.

## Environment

 - PyTorch Version: 1.2.0.dev20190722
 - Python version: 3.6.8
 - torchvision: 0.2.2
 - CUDA/cuDNN version: CUDA 9.0

**Comment by rnsandeep** [comment]
This happens when you change the input size of image and have your custom size. 
The solution is 
In this code https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/fpn.py
uncomment line 62, 63 and comment out line 64.
